<?php


/**
 * This class adds structure of 'audit_log' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue May 24 06:33:25 2011
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AuditLogMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AuditLogMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AuditLogPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AuditLogPeer::TABLE_NAME);
		$tMap->setPhpName('AuditLog');
		$tMap->setClassname('AuditLog');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11);

		$tMap->addColumn('DATE_TIME', 'DateTime', 'TIMESTAMP', false, null);

		$tMap->addColumn('PERSON_ID', 'PersonId', 'INTEGER', false, 11);

		$tMap->addColumn('EVENT', 'Event', 'VARCHAR', false, 15);

		$tMap->addColumn('EVENT_REASON', 'EventReason', 'VARCHAR', false, 1000);

	} // doBuild()

} // AuditLogMapBuilder
