<?php

/**
 * Base class that represents a row from the 'mission_type' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue May 24 06:33:29 2011
 *
 * @package    lib.model.om
 */
abstract class BaseMissionType extends BaseObject  implements Persistent {


  const PEER = 'MissionTypePeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        MissionTypePeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the stat_count field.
	 * @var        int
	 */
	protected $stat_count;

	/**
	 * The value for the color field.
	 * @var        string
	 */
	protected $color;

	/**
	 * @var        array Mission[] Collection to store aggregation of Mission objects.
	 */
	protected $collMissions;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMissions.
	 */
	private $lastMissionCriteria = null;

	/**
	 * @var        array MissionRequest[] Collection to store aggregation of MissionRequest objects.
	 */
	protected $collMissionRequests;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMissionRequests.
	 */
	private $lastMissionRequestCriteria = null;

	/**
	 * @var        array MissionTypeWingStats[] Collection to store aggregation of MissionTypeWingStats objects.
	 */
	protected $collMissionTypeWingStatss;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMissionTypeWingStatss.
	 */
	private $lastMissionTypeWingStatsCriteria = null;

	/**
	 * @var        array UserFilterMissionTypes[] Collection to store aggregation of UserFilterMissionTypes objects.
	 */
	protected $collUserFilterMissionTypess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collUserFilterMissionTypess.
	 */
	private $lastUserFilterMissionTypesCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseMissionType object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [stat_count] column value.
	 * 
	 * @return     int
	 */
	public function getStatCount()
	{
		return $this->stat_count;
	}

	/**
	 * Get the [color] column value.
	 * 
	 * @return     string
	 */
	public function getColor()
	{
		return $this->color;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionType The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = MissionTypePeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     MissionType The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = MissionTypePeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [stat_count] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionType The current object (for fluent API support)
	 */
	public function setStatCount($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->stat_count !== $v) {
			$this->stat_count = $v;
			$this->modifiedColumns[] = MissionTypePeer::STAT_COUNT;
		}

		return $this;
	} // setStatCount()

	/**
	 * Set the value of [color] column.
	 * 
	 * @param      string $v new value
	 * @return     MissionType The current object (for fluent API support)
	 */
	public function setColor($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->color !== $v) {
			$this->color = $v;
			$this->modifiedColumns[] = MissionTypePeer::COLOR;
		}

		return $this;
	} // setColor()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->stat_count = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->color = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 4; // 4 = MissionTypePeer::NUM_COLUMNS - MissionTypePeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating MissionType object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MissionTypePeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = MissionTypePeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collMissions = null;
			$this->lastMissionCriteria = null;

			$this->collMissionRequests = null;
			$this->lastMissionRequestCriteria = null;

			$this->collMissionTypeWingStatss = null;
			$this->lastMissionTypeWingStatsCriteria = null;

			$this->collUserFilterMissionTypess = null;
			$this->lastUserFilterMissionTypesCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseMissionType:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MissionTypePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			MissionTypePeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseMissionType:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseMissionType:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MissionTypePeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseMissionType:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			MissionTypePeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = MissionTypePeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = MissionTypePeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += MissionTypePeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collMissions !== null) {
				foreach ($this->collMissions as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMissionRequests !== null) {
				foreach ($this->collMissionRequests as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMissionTypeWingStatss !== null) {
				foreach ($this->collMissionTypeWingStatss as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collUserFilterMissionTypess !== null) {
				foreach ($this->collUserFilterMissionTypess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = MissionTypePeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collMissions !== null) {
					foreach ($this->collMissions as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMissionRequests !== null) {
					foreach ($this->collMissionRequests as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMissionTypeWingStatss !== null) {
					foreach ($this->collMissionTypeWingStatss as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collUserFilterMissionTypess !== null) {
					foreach ($this->collUserFilterMissionTypess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = MissionTypePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getName();
				break;
			case 2:
				return $this->getStatCount();
				break;
			case 3:
				return $this->getColor();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = MissionTypePeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getName(),
			$keys[2] => $this->getStatCount(),
			$keys[3] => $this->getColor(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = MissionTypePeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setName($value);
				break;
			case 2:
				$this->setStatCount($value);
				break;
			case 3:
				$this->setColor($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = MissionTypePeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setStatCount($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setColor($arr[$keys[3]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);

		if ($this->isColumnModified(MissionTypePeer::ID)) $criteria->add(MissionTypePeer::ID, $this->id);
		if ($this->isColumnModified(MissionTypePeer::NAME)) $criteria->add(MissionTypePeer::NAME, $this->name);
		if ($this->isColumnModified(MissionTypePeer::STAT_COUNT)) $criteria->add(MissionTypePeer::STAT_COUNT, $this->stat_count);
		if ($this->isColumnModified(MissionTypePeer::COLOR)) $criteria->add(MissionTypePeer::COLOR, $this->color);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);

		$criteria->add(MissionTypePeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of MissionType (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setName($this->name);

		$copyObj->setStatCount($this->stat_count);

		$copyObj->setColor($this->color);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getMissions() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMission($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMissionRequests() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMissionRequest($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMissionTypeWingStatss() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMissionTypeWingStats($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getUserFilterMissionTypess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addUserFilterMissionTypes($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     MissionType Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     MissionTypePeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new MissionTypePeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collMissions collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMissions()
	 */
	public function clearMissions()
	{
		$this->collMissions = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMissions collection (array).
	 *
	 * By default this just sets the collMissions collection to an empty array (like clearcollMissions());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMissions()
	{
		$this->collMissions = array();
	}

	/**
	 * Gets an array of Mission objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this MissionType has previously been saved, it will retrieve
	 * related Missions from storage. If this MissionType is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Mission[]
	 * @throws     PropelException
	 */
	public function getMissions($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissions === null) {
			if ($this->isNew()) {
			   $this->collMissions = array();
			} else {

				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				MissionPeer::addSelectColumns($criteria);
				$this->collMissions = MissionPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				MissionPeer::addSelectColumns($criteria);
				if (!isset($this->lastMissionCriteria) || !$this->lastMissionCriteria->equals($criteria)) {
					$this->collMissions = MissionPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMissionCriteria = $criteria;
		return $this->collMissions;
	}

	/**
	 * Returns the number of related Mission objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Mission objects.
	 * @throws     PropelException
	 */
	public function countMissions(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMissions === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				$count = MissionPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				if (!isset($this->lastMissionCriteria) || !$this->lastMissionCriteria->equals($criteria)) {
					$count = MissionPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collMissions);
				}
			} else {
				$count = count($this->collMissions);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Mission object to this object
	 * through the Mission foreign key attribute.
	 *
	 * @param      Mission $l Mission
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMission(Mission $l)
	{
		if ($this->collMissions === null) {
			$this->initMissions();
		}
		if (!in_array($l, $this->collMissions, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMissions, $l);
			$l->setMissionType($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MissionType is new, it will return
	 * an empty collection; or if this MissionType has previously
	 * been saved, it will retrieve related Missions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MissionType.
	 */
	public function getMissionsJoinMissionRequest($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissions === null) {
			if ($this->isNew()) {
				$this->collMissions = array();
			} else {

				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				$this->collMissions = MissionPeer::doSelectJoinMissionRequest($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

			if (!isset($this->lastMissionCriteria) || !$this->lastMissionCriteria->equals($criteria)) {
				$this->collMissions = MissionPeer::doSelectJoinMissionRequest($criteria, $con, $join_behavior);
			}
		}
		$this->lastMissionCriteria = $criteria;

		return $this->collMissions;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MissionType is new, it will return
	 * an empty collection; or if this MissionType has previously
	 * been saved, it will retrieve related Missions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MissionType.
	 */
	public function getMissionsJoinItinerary($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissions === null) {
			if ($this->isNew()) {
				$this->collMissions = array();
			} else {

				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				$this->collMissions = MissionPeer::doSelectJoinItinerary($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

			if (!isset($this->lastMissionCriteria) || !$this->lastMissionCriteria->equals($criteria)) {
				$this->collMissions = MissionPeer::doSelectJoinItinerary($criteria, $con, $join_behavior);
			}
		}
		$this->lastMissionCriteria = $criteria;

		return $this->collMissions;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MissionType is new, it will return
	 * an empty collection; or if this MissionType has previously
	 * been saved, it will retrieve related Missions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MissionType.
	 */
	public function getMissionsJoinPassenger($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissions === null) {
			if ($this->isNew()) {
				$this->collMissions = array();
			} else {

				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				$this->collMissions = MissionPeer::doSelectJoinPassenger($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

			if (!isset($this->lastMissionCriteria) || !$this->lastMissionCriteria->equals($criteria)) {
				$this->collMissions = MissionPeer::doSelectJoinPassenger($criteria, $con, $join_behavior);
			}
		}
		$this->lastMissionCriteria = $criteria;

		return $this->collMissions;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MissionType is new, it will return
	 * an empty collection; or if this MissionType has previously
	 * been saved, it will retrieve related Missions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MissionType.
	 */
	public function getMissionsJoinRequesterRelatedByRequesterId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissions === null) {
			if ($this->isNew()) {
				$this->collMissions = array();
			} else {

				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				$this->collMissions = MissionPeer::doSelectJoinRequesterRelatedByRequesterId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

			if (!isset($this->lastMissionCriteria) || !$this->lastMissionCriteria->equals($criteria)) {
				$this->collMissions = MissionPeer::doSelectJoinRequesterRelatedByRequesterId($criteria, $con, $join_behavior);
			}
		}
		$this->lastMissionCriteria = $criteria;

		return $this->collMissions;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MissionType is new, it will return
	 * an empty collection; or if this MissionType has previously
	 * been saved, it will retrieve related Missions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MissionType.
	 */
	public function getMissionsJoinAgencyRelatedByAgencyId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissions === null) {
			if ($this->isNew()) {
				$this->collMissions = array();
			} else {

				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				$this->collMissions = MissionPeer::doSelectJoinAgencyRelatedByAgencyId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

			if (!isset($this->lastMissionCriteria) || !$this->lastMissionCriteria->equals($criteria)) {
				$this->collMissions = MissionPeer::doSelectJoinAgencyRelatedByAgencyId($criteria, $con, $join_behavior);
			}
		}
		$this->lastMissionCriteria = $criteria;

		return $this->collMissions;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MissionType is new, it will return
	 * an empty collection; or if this MissionType has previously
	 * been saved, it will retrieve related Missions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MissionType.
	 */
	public function getMissionsJoinRequesterRelatedByOtherRequesterId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissions === null) {
			if ($this->isNew()) {
				$this->collMissions = array();
			} else {

				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				$this->collMissions = MissionPeer::doSelectJoinRequesterRelatedByOtherRequesterId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

			if (!isset($this->lastMissionCriteria) || !$this->lastMissionCriteria->equals($criteria)) {
				$this->collMissions = MissionPeer::doSelectJoinRequesterRelatedByOtherRequesterId($criteria, $con, $join_behavior);
			}
		}
		$this->lastMissionCriteria = $criteria;

		return $this->collMissions;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MissionType is new, it will return
	 * an empty collection; or if this MissionType has previously
	 * been saved, it will retrieve related Missions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MissionType.
	 */
	public function getMissionsJoinAgencyRelatedByOtherAgencyId($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissions === null) {
			if ($this->isNew()) {
				$this->collMissions = array();
			} else {

				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				$this->collMissions = MissionPeer::doSelectJoinAgencyRelatedByOtherAgencyId($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

			if (!isset($this->lastMissionCriteria) || !$this->lastMissionCriteria->equals($criteria)) {
				$this->collMissions = MissionPeer::doSelectJoinAgencyRelatedByOtherAgencyId($criteria, $con, $join_behavior);
			}
		}
		$this->lastMissionCriteria = $criteria;

		return $this->collMissions;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MissionType is new, it will return
	 * an empty collection; or if this MissionType has previously
	 * been saved, it will retrieve related Missions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MissionType.
	 */
	public function getMissionsJoinCamp($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissions === null) {
			if ($this->isNew()) {
				$this->collMissions = array();
			} else {

				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				$this->collMissions = MissionPeer::doSelectJoinCamp($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

			if (!isset($this->lastMissionCriteria) || !$this->lastMissionCriteria->equals($criteria)) {
				$this->collMissions = MissionPeer::doSelectJoinCamp($criteria, $con, $join_behavior);
			}
		}
		$this->lastMissionCriteria = $criteria;

		return $this->collMissions;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MissionType is new, it will return
	 * an empty collection; or if this MissionType has previously
	 * been saved, it will retrieve related Missions from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MissionType.
	 */
	public function getMissionsJoinCoordinator($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissions === null) {
			if ($this->isNew()) {
				$this->collMissions = array();
			} else {

				$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

				$this->collMissions = MissionPeer::doSelectJoinCoordinator($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MissionPeer::MISSION_TYPE_ID, $this->id);

			if (!isset($this->lastMissionCriteria) || !$this->lastMissionCriteria->equals($criteria)) {
				$this->collMissions = MissionPeer::doSelectJoinCoordinator($criteria, $con, $join_behavior);
			}
		}
		$this->lastMissionCriteria = $criteria;

		return $this->collMissions;
	}

	/**
	 * Clears out the collMissionRequests collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMissionRequests()
	 */
	public function clearMissionRequests()
	{
		$this->collMissionRequests = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMissionRequests collection (array).
	 *
	 * By default this just sets the collMissionRequests collection to an empty array (like clearcollMissionRequests());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMissionRequests()
	{
		$this->collMissionRequests = array();
	}

	/**
	 * Gets an array of MissionRequest objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this MissionType has previously been saved, it will retrieve
	 * related MissionRequests from storage. If this MissionType is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array MissionRequest[]
	 * @throws     PropelException
	 */
	public function getMissionRequests($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissionRequests === null) {
			if ($this->isNew()) {
			   $this->collMissionRequests = array();
			} else {

				$criteria->add(MissionRequestPeer::MISSION_REQUEST_TYPE_ID, $this->id);

				MissionRequestPeer::addSelectColumns($criteria);
				$this->collMissionRequests = MissionRequestPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MissionRequestPeer::MISSION_REQUEST_TYPE_ID, $this->id);

				MissionRequestPeer::addSelectColumns($criteria);
				if (!isset($this->lastMissionRequestCriteria) || !$this->lastMissionRequestCriteria->equals($criteria)) {
					$this->collMissionRequests = MissionRequestPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMissionRequestCriteria = $criteria;
		return $this->collMissionRequests;
	}

	/**
	 * Returns the number of related MissionRequest objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related MissionRequest objects.
	 * @throws     PropelException
	 */
	public function countMissionRequests(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMissionRequests === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MissionRequestPeer::MISSION_REQUEST_TYPE_ID, $this->id);

				$count = MissionRequestPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MissionRequestPeer::MISSION_REQUEST_TYPE_ID, $this->id);

				if (!isset($this->lastMissionRequestCriteria) || !$this->lastMissionRequestCriteria->equals($criteria)) {
					$count = MissionRequestPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collMissionRequests);
				}
			} else {
				$count = count($this->collMissionRequests);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a MissionRequest object to this object
	 * through the MissionRequest foreign key attribute.
	 *
	 * @param      MissionRequest $l MissionRequest
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMissionRequest(MissionRequest $l)
	{
		if ($this->collMissionRequests === null) {
			$this->initMissionRequests();
		}
		if (!in_array($l, $this->collMissionRequests, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMissionRequests, $l);
			$l->setMissionType($this);
		}
	}

	/**
	 * Clears out the collMissionTypeWingStatss collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMissionTypeWingStatss()
	 */
	public function clearMissionTypeWingStatss()
	{
		$this->collMissionTypeWingStatss = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMissionTypeWingStatss collection (array).
	 *
	 * By default this just sets the collMissionTypeWingStatss collection to an empty array (like clearcollMissionTypeWingStatss());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMissionTypeWingStatss()
	{
		$this->collMissionTypeWingStatss = array();
	}

	/**
	 * Gets an array of MissionTypeWingStats objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this MissionType has previously been saved, it will retrieve
	 * related MissionTypeWingStatss from storage. If this MissionType is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array MissionTypeWingStats[]
	 * @throws     PropelException
	 */
	public function getMissionTypeWingStatss($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissionTypeWingStatss === null) {
			if ($this->isNew()) {
			   $this->collMissionTypeWingStatss = array();
			} else {

				$criteria->add(MissionTypeWingStatsPeer::MISSION_TYPE_ID, $this->id);

				MissionTypeWingStatsPeer::addSelectColumns($criteria);
				$this->collMissionTypeWingStatss = MissionTypeWingStatsPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MissionTypeWingStatsPeer::MISSION_TYPE_ID, $this->id);

				MissionTypeWingStatsPeer::addSelectColumns($criteria);
				if (!isset($this->lastMissionTypeWingStatsCriteria) || !$this->lastMissionTypeWingStatsCriteria->equals($criteria)) {
					$this->collMissionTypeWingStatss = MissionTypeWingStatsPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMissionTypeWingStatsCriteria = $criteria;
		return $this->collMissionTypeWingStatss;
	}

	/**
	 * Returns the number of related MissionTypeWingStats objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related MissionTypeWingStats objects.
	 * @throws     PropelException
	 */
	public function countMissionTypeWingStatss(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMissionTypeWingStatss === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MissionTypeWingStatsPeer::MISSION_TYPE_ID, $this->id);

				$count = MissionTypeWingStatsPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MissionTypeWingStatsPeer::MISSION_TYPE_ID, $this->id);

				if (!isset($this->lastMissionTypeWingStatsCriteria) || !$this->lastMissionTypeWingStatsCriteria->equals($criteria)) {
					$count = MissionTypeWingStatsPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collMissionTypeWingStatss);
				}
			} else {
				$count = count($this->collMissionTypeWingStatss);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a MissionTypeWingStats object to this object
	 * through the MissionTypeWingStats foreign key attribute.
	 *
	 * @param      MissionTypeWingStats $l MissionTypeWingStats
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMissionTypeWingStats(MissionTypeWingStats $l)
	{
		if ($this->collMissionTypeWingStatss === null) {
			$this->initMissionTypeWingStatss();
		}
		if (!in_array($l, $this->collMissionTypeWingStatss, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMissionTypeWingStatss, $l);
			$l->setMissionType($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MissionType is new, it will return
	 * an empty collection; or if this MissionType has previously
	 * been saved, it will retrieve related MissionTypeWingStatss from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MissionType.
	 */
	public function getMissionTypeWingStatssJoinWing($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMissionTypeWingStatss === null) {
			if ($this->isNew()) {
				$this->collMissionTypeWingStatss = array();
			} else {

				$criteria->add(MissionTypeWingStatsPeer::MISSION_TYPE_ID, $this->id);

				$this->collMissionTypeWingStatss = MissionTypeWingStatsPeer::doSelectJoinWing($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(MissionTypeWingStatsPeer::MISSION_TYPE_ID, $this->id);

			if (!isset($this->lastMissionTypeWingStatsCriteria) || !$this->lastMissionTypeWingStatsCriteria->equals($criteria)) {
				$this->collMissionTypeWingStatss = MissionTypeWingStatsPeer::doSelectJoinWing($criteria, $con, $join_behavior);
			}
		}
		$this->lastMissionTypeWingStatsCriteria = $criteria;

		return $this->collMissionTypeWingStatss;
	}

	/**
	 * Clears out the collUserFilterMissionTypess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addUserFilterMissionTypess()
	 */
	public function clearUserFilterMissionTypess()
	{
		$this->collUserFilterMissionTypess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collUserFilterMissionTypess collection (array).
	 *
	 * By default this just sets the collUserFilterMissionTypess collection to an empty array (like clearcollUserFilterMissionTypess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initUserFilterMissionTypess()
	{
		$this->collUserFilterMissionTypess = array();
	}

	/**
	 * Gets an array of UserFilterMissionTypes objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this MissionType has previously been saved, it will retrieve
	 * related UserFilterMissionTypess from storage. If this MissionType is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array UserFilterMissionTypes[]
	 * @throws     PropelException
	 */
	public function getUserFilterMissionTypess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserFilterMissionTypess === null) {
			if ($this->isNew()) {
			   $this->collUserFilterMissionTypess = array();
			} else {

				$criteria->add(UserFilterMissionTypesPeer::MISSION_TYPE_ID, $this->id);

				UserFilterMissionTypesPeer::addSelectColumns($criteria);
				$this->collUserFilterMissionTypess = UserFilterMissionTypesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(UserFilterMissionTypesPeer::MISSION_TYPE_ID, $this->id);

				UserFilterMissionTypesPeer::addSelectColumns($criteria);
				if (!isset($this->lastUserFilterMissionTypesCriteria) || !$this->lastUserFilterMissionTypesCriteria->equals($criteria)) {
					$this->collUserFilterMissionTypess = UserFilterMissionTypesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastUserFilterMissionTypesCriteria = $criteria;
		return $this->collUserFilterMissionTypess;
	}

	/**
	 * Returns the number of related UserFilterMissionTypes objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related UserFilterMissionTypes objects.
	 * @throws     PropelException
	 */
	public function countUserFilterMissionTypess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collUserFilterMissionTypess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(UserFilterMissionTypesPeer::MISSION_TYPE_ID, $this->id);

				$count = UserFilterMissionTypesPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(UserFilterMissionTypesPeer::MISSION_TYPE_ID, $this->id);

				if (!isset($this->lastUserFilterMissionTypesCriteria) || !$this->lastUserFilterMissionTypesCriteria->equals($criteria)) {
					$count = UserFilterMissionTypesPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collUserFilterMissionTypess);
				}
			} else {
				$count = count($this->collUserFilterMissionTypess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a UserFilterMissionTypes object to this object
	 * through the UserFilterMissionTypes foreign key attribute.
	 *
	 * @param      UserFilterMissionTypes $l UserFilterMissionTypes
	 * @return     void
	 * @throws     PropelException
	 */
	public function addUserFilterMissionTypes(UserFilterMissionTypes $l)
	{
		if ($this->collUserFilterMissionTypess === null) {
			$this->initUserFilterMissionTypess();
		}
		if (!in_array($l, $this->collUserFilterMissionTypess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collUserFilterMissionTypess, $l);
			$l->setMissionType($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this MissionType is new, it will return
	 * an empty collection; or if this MissionType has previously
	 * been saved, it will retrieve related UserFilterMissionTypess from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in MissionType.
	 */
	public function getUserFilterMissionTypessJoinUserFilter($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MissionTypePeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collUserFilterMissionTypess === null) {
			if ($this->isNew()) {
				$this->collUserFilterMissionTypess = array();
			} else {

				$criteria->add(UserFilterMissionTypesPeer::MISSION_TYPE_ID, $this->id);

				$this->collUserFilterMissionTypess = UserFilterMissionTypesPeer::doSelectJoinUserFilter($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(UserFilterMissionTypesPeer::MISSION_TYPE_ID, $this->id);

			if (!isset($this->lastUserFilterMissionTypesCriteria) || !$this->lastUserFilterMissionTypesCriteria->equals($criteria)) {
				$this->collUserFilterMissionTypess = UserFilterMissionTypesPeer::doSelectJoinUserFilter($criteria, $con, $join_behavior);
			}
		}
		$this->lastUserFilterMissionTypesCriteria = $criteria;

		return $this->collUserFilterMissionTypess;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collMissions) {
				foreach ((array) $this->collMissions as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMissionRequests) {
				foreach ((array) $this->collMissionRequests as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMissionTypeWingStatss) {
				foreach ((array) $this->collMissionTypeWingStatss as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collUserFilterMissionTypess) {
				foreach ((array) $this->collUserFilterMissionTypess as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collMissions = null;
		$this->collMissionRequests = null;
		$this->collMissionTypeWingStatss = null;
		$this->collUserFilterMissionTypess = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseMissionType:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseMissionType::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseMissionType
