<?php

/**
 * Base class that represents a row from the 'rp_member_application_reconciliation' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue May 24 06:33:32 2011
 *
 * @package    lib.model.om
 */
abstract class BaseRpMemberApplicationReconciliation extends BaseObject  implements Persistent {


  const PEER = 'RpMemberApplicationReconciliationPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        RpMemberApplicationReconciliationPeer
	 */
	protected static $peer;

	/**
	 * The value for the first_name field.
	 * @var        string
	 */
	protected $first_name;

	/**
	 * The value for the last_name field.
	 * @var        string
	 */
	protected $last_name;

	/**
	 * The value for the external_id field.
	 * @var        int
	 */
	protected $external_id;

	/**
	 * The value for the renewal field.
	 * @var        int
	 */
	protected $renewal;

	/**
	 * The value for the dues_amount_paid field.
	 * Note: this column has a database default value of: 0
	 * @var        double
	 */
	protected $dues_amount_paid;

	/**
	 * The value for the method_of_payment field.
	 * @var        string
	 */
	protected $method_of_payment;

	/**
	 * The value for the check_number field.
	 * @var        int
	 */
	protected $check_number;

	/**
	 * The value for the donation_amount_paid field.
	 * @var        double
	 */
	protected $donation_amount_paid;

	/**
	 * The value for the application_date field.
	 * @var        string
	 */
	protected $application_date;

	/**
	 * The value for the applicationdatedisplay field.
	 * @var        string
	 */
	protected $applicationdatedisplay;

	/**
	 * The value for the processeddate field.
	 * @var        string
	 */
	protected $processeddate;

	/**
	 * The value for the ccard_approval_number field.
	 * @var        string
	 */
	protected $ccard_approval_number;

	/**
	 * The value for the payment_transaction_id field.
	 * @var        int
	 */
	protected $payment_transaction_id;

	/**
	 * The value for the member_class_id field.
	 * @var        int
	 */
	protected $member_class_id;

	/**
	 * The value for the memberclass field.
	 * @var        string
	 */
	protected $memberclass;

	/**
	 * The value for the master_member_id field.
	 * @var        int
	 */
	protected $master_member_id;

	/**
	 * The value for the mastermemberexternalid field.
	 * @var        int
	 */
	protected $mastermemberexternalid;

	/**
	 * The value for the mastermemberfirstname field.
	 * @var        string
	 */
	protected $mastermemberfirstname;

	/**
	 * The value for the mastermemberlastname field.
	 * @var        string
	 */
	protected $mastermemberlastname;

	/**
	 * The value for the renewal_date field.
	 * @var        string
	 */
	protected $renewal_date;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseRpMemberApplicationReconciliation object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->dues_amount_paid = 0;
	}

	/**
	 * Get the [first_name] column value.
	 * 
	 * @return     string
	 */
	public function getFirstName()
	{
		return $this->first_name;
	}

	/**
	 * Get the [last_name] column value.
	 * 
	 * @return     string
	 */
	public function getLastName()
	{
		return $this->last_name;
	}

	/**
	 * Get the [external_id] column value.
	 * 
	 * @return     int
	 */
	public function getExternalId()
	{
		return $this->external_id;
	}

	/**
	 * Get the [renewal] column value.
	 * 
	 * @return     int
	 */
	public function getRenewal()
	{
		return $this->renewal;
	}

	/**
	 * Get the [dues_amount_paid] column value.
	 * 
	 * @return     double
	 */
	public function getDuesAmountPaid()
	{
		return $this->dues_amount_paid;
	}

	/**
	 * Get the [method_of_payment] column value.
	 * 
	 * @return     string
	 */
	public function getMethodOfPayment()
	{
		return $this->method_of_payment;
	}

	/**
	 * Get the [check_number] column value.
	 * 
	 * @return     int
	 */
	public function getCheckNumber()
	{
		return $this->check_number;
	}

	/**
	 * Get the [donation_amount_paid] column value.
	 * 
	 * @return     double
	 */
	public function getDonationAmountPaid()
	{
		return $this->donation_amount_paid;
	}

	/**
	 * Get the [optionally formatted] temporal [application_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getApplicationDate($format = 'Y-m-d H:i:s')
	{
		if ($this->application_date === null) {
			return null;
		}


		if ($this->application_date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->application_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->application_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [applicationdatedisplay] column value.
	 * 
	 * @return     string
	 */
	public function getApplicationdatedisplay()
	{
		return $this->applicationdatedisplay;
	}

	/**
	 * Get the [processeddate] column value.
	 * 
	 * @return     string
	 */
	public function getProcesseddate()
	{
		return $this->processeddate;
	}

	/**
	 * Get the [ccard_approval_number] column value.
	 * 
	 * @return     string
	 */
	public function getCcardApprovalNumber()
	{
		return $this->ccard_approval_number;
	}

	/**
	 * Get the [payment_transaction_id] column value.
	 * 
	 * @return     int
	 */
	public function getPaymentTransactionId()
	{
		return $this->payment_transaction_id;
	}

	/**
	 * Get the [member_class_id] column value.
	 * 
	 * @return     int
	 */
	public function getMemberClassId()
	{
		return $this->member_class_id;
	}

	/**
	 * Get the [memberclass] column value.
	 * 
	 * @return     string
	 */
	public function getMemberclass()
	{
		return $this->memberclass;
	}

	/**
	 * Get the [master_member_id] column value.
	 * 
	 * @return     int
	 */
	public function getMasterMemberId()
	{
		return $this->master_member_id;
	}

	/**
	 * Get the [mastermemberexternalid] column value.
	 * 
	 * @return     int
	 */
	public function getMastermemberexternalid()
	{
		return $this->mastermemberexternalid;
	}

	/**
	 * Get the [mastermemberfirstname] column value.
	 * 
	 * @return     string
	 */
	public function getMastermemberfirstname()
	{
		return $this->mastermemberfirstname;
	}

	/**
	 * Get the [mastermemberlastname] column value.
	 * 
	 * @return     string
	 */
	public function getMastermemberlastname()
	{
		return $this->mastermemberlastname;
	}

	/**
	 * Get the [optionally formatted] temporal [renewal_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getRenewalDate($format = 'Y-m-d')
	{
		if ($this->renewal_date === null) {
			return null;
		}


		if ($this->renewal_date === '0000-00-00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->renewal_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->renewal_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Set the value of [first_name] column.
	 * 
	 * @param      string $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setFirstName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->first_name !== $v) {
			$this->first_name = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::FIRST_NAME;
		}

		return $this;
	} // setFirstName()

	/**
	 * Set the value of [last_name] column.
	 * 
	 * @param      string $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setLastName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->last_name !== $v) {
			$this->last_name = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::LAST_NAME;
		}

		return $this;
	} // setLastName()

	/**
	 * Set the value of [external_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setExternalId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->external_id !== $v) {
			$this->external_id = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::EXTERNAL_ID;
		}

		return $this;
	} // setExternalId()

	/**
	 * Set the value of [renewal] column.
	 * 
	 * @param      int $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setRenewal($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->renewal !== $v) {
			$this->renewal = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::RENEWAL;
		}

		return $this;
	} // setRenewal()

	/**
	 * Set the value of [dues_amount_paid] column.
	 * 
	 * @param      double $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setDuesAmountPaid($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->dues_amount_paid !== $v || $v === 0) {
			$this->dues_amount_paid = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::DUES_AMOUNT_PAID;
		}

		return $this;
	} // setDuesAmountPaid()

	/**
	 * Set the value of [method_of_payment] column.
	 * 
	 * @param      string $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setMethodOfPayment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->method_of_payment !== $v) {
			$this->method_of_payment = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::METHOD_OF_PAYMENT;
		}

		return $this;
	} // setMethodOfPayment()

	/**
	 * Set the value of [check_number] column.
	 * 
	 * @param      int $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setCheckNumber($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->check_number !== $v) {
			$this->check_number = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::CHECK_NUMBER;
		}

		return $this;
	} // setCheckNumber()

	/**
	 * Set the value of [donation_amount_paid] column.
	 * 
	 * @param      double $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setDonationAmountPaid($v)
	{
		if ($v !== null) {
			$v = (double) $v;
		}

		if ($this->donation_amount_paid !== $v) {
			$this->donation_amount_paid = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::DONATION_AMOUNT_PAID;
		}

		return $this;
	} // setDonationAmountPaid()

	/**
	 * Sets the value of [application_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setApplicationDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->application_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->application_date !== null && $tmpDt = new DateTime($this->application_date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->application_date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::APPLICATION_DATE;
			}
		} // if either are not null

		return $this;
	} // setApplicationDate()

	/**
	 * Set the value of [applicationdatedisplay] column.
	 * 
	 * @param      string $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setApplicationdatedisplay($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->applicationdatedisplay !== $v) {
			$this->applicationdatedisplay = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::APPLICATIONDATEDISPLAY;
		}

		return $this;
	} // setApplicationdatedisplay()

	/**
	 * Set the value of [processeddate] column.
	 * 
	 * @param      string $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setProcesseddate($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->processeddate !== $v) {
			$this->processeddate = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::PROCESSEDDATE;
		}

		return $this;
	} // setProcesseddate()

	/**
	 * Set the value of [ccard_approval_number] column.
	 * 
	 * @param      string $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setCcardApprovalNumber($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->ccard_approval_number !== $v) {
			$this->ccard_approval_number = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::CCARD_APPROVAL_NUMBER;
		}

		return $this;
	} // setCcardApprovalNumber()

	/**
	 * Set the value of [payment_transaction_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setPaymentTransactionId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->payment_transaction_id !== $v) {
			$this->payment_transaction_id = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::PAYMENT_TRANSACTION_ID;
		}

		return $this;
	} // setPaymentTransactionId()

	/**
	 * Set the value of [member_class_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setMemberClassId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->member_class_id !== $v) {
			$this->member_class_id = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::MEMBER_CLASS_ID;
		}

		return $this;
	} // setMemberClassId()

	/**
	 * Set the value of [memberclass] column.
	 * 
	 * @param      string $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setMemberclass($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->memberclass !== $v) {
			$this->memberclass = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::MEMBERCLASS;
		}

		return $this;
	} // setMemberclass()

	/**
	 * Set the value of [master_member_id] column.
	 * 
	 * @param      int $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setMasterMemberId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->master_member_id !== $v) {
			$this->master_member_id = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::MASTER_MEMBER_ID;
		}

		return $this;
	} // setMasterMemberId()

	/**
	 * Set the value of [mastermemberexternalid] column.
	 * 
	 * @param      int $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setMastermemberexternalid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->mastermemberexternalid !== $v) {
			$this->mastermemberexternalid = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::MASTERMEMBEREXTERNALID;
		}

		return $this;
	} // setMastermemberexternalid()

	/**
	 * Set the value of [mastermemberfirstname] column.
	 * 
	 * @param      string $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setMastermemberfirstname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mastermemberfirstname !== $v) {
			$this->mastermemberfirstname = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::MASTERMEMBERFIRSTNAME;
		}

		return $this;
	} // setMastermemberfirstname()

	/**
	 * Set the value of [mastermemberlastname] column.
	 * 
	 * @param      string $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setMastermemberlastname($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mastermemberlastname !== $v) {
			$this->mastermemberlastname = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::MASTERMEMBERLASTNAME;
		}

		return $this;
	} // setMastermemberlastname()

	/**
	 * Sets the value of [renewal_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setRenewalDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->renewal_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->renewal_date !== null && $tmpDt = new DateTime($this->renewal_date)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->renewal_date = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::RENEWAL_DATE;
			}
		} // if either are not null

		return $this;
	} // setRenewalDate()

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     RpMemberApplicationReconciliation The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array(RpMemberApplicationReconciliationPeer::DUES_AMOUNT_PAID))) {
				return false;
			}

			if ($this->dues_amount_paid !== 0) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->first_name = ($row[$startcol + 0] !== null) ? (string) $row[$startcol + 0] : null;
			$this->last_name = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->external_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->renewal = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->dues_amount_paid = ($row[$startcol + 4] !== null) ? (double) $row[$startcol + 4] : null;
			$this->method_of_payment = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->check_number = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->donation_amount_paid = ($row[$startcol + 7] !== null) ? (double) $row[$startcol + 7] : null;
			$this->application_date = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->applicationdatedisplay = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->processeddate = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->ccard_approval_number = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->payment_transaction_id = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->member_class_id = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->memberclass = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->master_member_id = ($row[$startcol + 15] !== null) ? (int) $row[$startcol + 15] : null;
			$this->mastermemberexternalid = ($row[$startcol + 16] !== null) ? (int) $row[$startcol + 16] : null;
			$this->mastermemberfirstname = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->mastermemberlastname = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->renewal_date = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->id = ($row[$startcol + 20] !== null) ? (int) $row[$startcol + 20] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 21; // 21 = RpMemberApplicationReconciliationPeer::NUM_COLUMNS - RpMemberApplicationReconciliationPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating RpMemberApplicationReconciliation object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RpMemberApplicationReconciliationPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = RpMemberApplicationReconciliationPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRpMemberApplicationReconciliation:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RpMemberApplicationReconciliationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			RpMemberApplicationReconciliationPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseRpMemberApplicationReconciliation:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRpMemberApplicationReconciliation:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(RpMemberApplicationReconciliationPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseRpMemberApplicationReconciliation:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			RpMemberApplicationReconciliationPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = RpMemberApplicationReconciliationPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = RpMemberApplicationReconciliationPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += RpMemberApplicationReconciliationPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = RpMemberApplicationReconciliationPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RpMemberApplicationReconciliationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getFirstName();
				break;
			case 1:
				return $this->getLastName();
				break;
			case 2:
				return $this->getExternalId();
				break;
			case 3:
				return $this->getRenewal();
				break;
			case 4:
				return $this->getDuesAmountPaid();
				break;
			case 5:
				return $this->getMethodOfPayment();
				break;
			case 6:
				return $this->getCheckNumber();
				break;
			case 7:
				return $this->getDonationAmountPaid();
				break;
			case 8:
				return $this->getApplicationDate();
				break;
			case 9:
				return $this->getApplicationdatedisplay();
				break;
			case 10:
				return $this->getProcesseddate();
				break;
			case 11:
				return $this->getCcardApprovalNumber();
				break;
			case 12:
				return $this->getPaymentTransactionId();
				break;
			case 13:
				return $this->getMemberClassId();
				break;
			case 14:
				return $this->getMemberclass();
				break;
			case 15:
				return $this->getMasterMemberId();
				break;
			case 16:
				return $this->getMastermemberexternalid();
				break;
			case 17:
				return $this->getMastermemberfirstname();
				break;
			case 18:
				return $this->getMastermemberlastname();
				break;
			case 19:
				return $this->getRenewalDate();
				break;
			case 20:
				return $this->getId();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = RpMemberApplicationReconciliationPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getFirstName(),
			$keys[1] => $this->getLastName(),
			$keys[2] => $this->getExternalId(),
			$keys[3] => $this->getRenewal(),
			$keys[4] => $this->getDuesAmountPaid(),
			$keys[5] => $this->getMethodOfPayment(),
			$keys[6] => $this->getCheckNumber(),
			$keys[7] => $this->getDonationAmountPaid(),
			$keys[8] => $this->getApplicationDate(),
			$keys[9] => $this->getApplicationdatedisplay(),
			$keys[10] => $this->getProcesseddate(),
			$keys[11] => $this->getCcardApprovalNumber(),
			$keys[12] => $this->getPaymentTransactionId(),
			$keys[13] => $this->getMemberClassId(),
			$keys[14] => $this->getMemberclass(),
			$keys[15] => $this->getMasterMemberId(),
			$keys[16] => $this->getMastermemberexternalid(),
			$keys[17] => $this->getMastermemberfirstname(),
			$keys[18] => $this->getMastermemberlastname(),
			$keys[19] => $this->getRenewalDate(),
			$keys[20] => $this->getId(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = RpMemberApplicationReconciliationPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setFirstName($value);
				break;
			case 1:
				$this->setLastName($value);
				break;
			case 2:
				$this->setExternalId($value);
				break;
			case 3:
				$this->setRenewal($value);
				break;
			case 4:
				$this->setDuesAmountPaid($value);
				break;
			case 5:
				$this->setMethodOfPayment($value);
				break;
			case 6:
				$this->setCheckNumber($value);
				break;
			case 7:
				$this->setDonationAmountPaid($value);
				break;
			case 8:
				$this->setApplicationDate($value);
				break;
			case 9:
				$this->setApplicationdatedisplay($value);
				break;
			case 10:
				$this->setProcesseddate($value);
				break;
			case 11:
				$this->setCcardApprovalNumber($value);
				break;
			case 12:
				$this->setPaymentTransactionId($value);
				break;
			case 13:
				$this->setMemberClassId($value);
				break;
			case 14:
				$this->setMemberclass($value);
				break;
			case 15:
				$this->setMasterMemberId($value);
				break;
			case 16:
				$this->setMastermemberexternalid($value);
				break;
			case 17:
				$this->setMastermemberfirstname($value);
				break;
			case 18:
				$this->setMastermemberlastname($value);
				break;
			case 19:
				$this->setRenewalDate($value);
				break;
			case 20:
				$this->setId($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = RpMemberApplicationReconciliationPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setFirstName($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setLastName($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setExternalId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setRenewal($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDuesAmountPaid($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setMethodOfPayment($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setCheckNumber($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDonationAmountPaid($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setApplicationDate($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setApplicationdatedisplay($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setProcesseddate($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setCcardApprovalNumber($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setPaymentTransactionId($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setMemberClassId($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setMemberclass($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setMasterMemberId($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setMastermemberexternalid($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setMastermemberfirstname($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setMastermemberlastname($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setRenewalDate($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setId($arr[$keys[20]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(RpMemberApplicationReconciliationPeer::DATABASE_NAME);

		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::FIRST_NAME)) $criteria->add(RpMemberApplicationReconciliationPeer::FIRST_NAME, $this->first_name);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::LAST_NAME)) $criteria->add(RpMemberApplicationReconciliationPeer::LAST_NAME, $this->last_name);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::EXTERNAL_ID)) $criteria->add(RpMemberApplicationReconciliationPeer::EXTERNAL_ID, $this->external_id);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::RENEWAL)) $criteria->add(RpMemberApplicationReconciliationPeer::RENEWAL, $this->renewal);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::DUES_AMOUNT_PAID)) $criteria->add(RpMemberApplicationReconciliationPeer::DUES_AMOUNT_PAID, $this->dues_amount_paid);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::METHOD_OF_PAYMENT)) $criteria->add(RpMemberApplicationReconciliationPeer::METHOD_OF_PAYMENT, $this->method_of_payment);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::CHECK_NUMBER)) $criteria->add(RpMemberApplicationReconciliationPeer::CHECK_NUMBER, $this->check_number);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::DONATION_AMOUNT_PAID)) $criteria->add(RpMemberApplicationReconciliationPeer::DONATION_AMOUNT_PAID, $this->donation_amount_paid);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::APPLICATION_DATE)) $criteria->add(RpMemberApplicationReconciliationPeer::APPLICATION_DATE, $this->application_date);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::APPLICATIONDATEDISPLAY)) $criteria->add(RpMemberApplicationReconciliationPeer::APPLICATIONDATEDISPLAY, $this->applicationdatedisplay);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::PROCESSEDDATE)) $criteria->add(RpMemberApplicationReconciliationPeer::PROCESSEDDATE, $this->processeddate);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::CCARD_APPROVAL_NUMBER)) $criteria->add(RpMemberApplicationReconciliationPeer::CCARD_APPROVAL_NUMBER, $this->ccard_approval_number);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::PAYMENT_TRANSACTION_ID)) $criteria->add(RpMemberApplicationReconciliationPeer::PAYMENT_TRANSACTION_ID, $this->payment_transaction_id);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::MEMBER_CLASS_ID)) $criteria->add(RpMemberApplicationReconciliationPeer::MEMBER_CLASS_ID, $this->member_class_id);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::MEMBERCLASS)) $criteria->add(RpMemberApplicationReconciliationPeer::MEMBERCLASS, $this->memberclass);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::MASTER_MEMBER_ID)) $criteria->add(RpMemberApplicationReconciliationPeer::MASTER_MEMBER_ID, $this->master_member_id);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::MASTERMEMBEREXTERNALID)) $criteria->add(RpMemberApplicationReconciliationPeer::MASTERMEMBEREXTERNALID, $this->mastermemberexternalid);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::MASTERMEMBERFIRSTNAME)) $criteria->add(RpMemberApplicationReconciliationPeer::MASTERMEMBERFIRSTNAME, $this->mastermemberfirstname);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::MASTERMEMBERLASTNAME)) $criteria->add(RpMemberApplicationReconciliationPeer::MASTERMEMBERLASTNAME, $this->mastermemberlastname);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::RENEWAL_DATE)) $criteria->add(RpMemberApplicationReconciliationPeer::RENEWAL_DATE, $this->renewal_date);
		if ($this->isColumnModified(RpMemberApplicationReconciliationPeer::ID)) $criteria->add(RpMemberApplicationReconciliationPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(RpMemberApplicationReconciliationPeer::DATABASE_NAME);

		$criteria->add(RpMemberApplicationReconciliationPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of RpMemberApplicationReconciliation (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setFirstName($this->first_name);

		$copyObj->setLastName($this->last_name);

		$copyObj->setExternalId($this->external_id);

		$copyObj->setRenewal($this->renewal);

		$copyObj->setDuesAmountPaid($this->dues_amount_paid);

		$copyObj->setMethodOfPayment($this->method_of_payment);

		$copyObj->setCheckNumber($this->check_number);

		$copyObj->setDonationAmountPaid($this->donation_amount_paid);

		$copyObj->setApplicationDate($this->application_date);

		$copyObj->setApplicationdatedisplay($this->applicationdatedisplay);

		$copyObj->setProcesseddate($this->processeddate);

		$copyObj->setCcardApprovalNumber($this->ccard_approval_number);

		$copyObj->setPaymentTransactionId($this->payment_transaction_id);

		$copyObj->setMemberClassId($this->member_class_id);

		$copyObj->setMemberclass($this->memberclass);

		$copyObj->setMasterMemberId($this->master_member_id);

		$copyObj->setMastermemberexternalid($this->mastermemberexternalid);

		$copyObj->setMastermemberfirstname($this->mastermemberfirstname);

		$copyObj->setMastermemberlastname($this->mastermemberlastname);

		$copyObj->setRenewalDate($this->renewal_date);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     RpMemberApplicationReconciliation Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     RpMemberApplicationReconciliationPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new RpMemberApplicationReconciliationPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseRpMemberApplicationReconciliation:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseRpMemberApplicationReconciliation::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseRpMemberApplicationReconciliation
