<?php

/**
 * Base static class for performing query and update operations on the 'afa_org' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue May 24 06:33:24 2011
 *
 * @package    lib.model.om
 */
abstract class BaseAfaOrgPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'afa_org';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.AfaOrg';

	/** The total number of columns. */
	const NUM_COLUMNS = 18;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'afa_org.ID';

	/** the column name for the NAME field */
	const NAME = 'afa_org.NAME';

	/** the column name for the ORG_PHONE field */
	const ORG_PHONE = 'afa_org.ORG_PHONE';

	/** the column name for the HOME_PAGE_URL field */
	const HOME_PAGE_URL = 'afa_org.HOME_PAGE_URL';

	/** the column name for the ORG_FAX field */
	const ORG_FAX = 'afa_org.ORG_FAX';

	/** the column name for the REF_CONTACT_NAME field */
	const REF_CONTACT_NAME = 'afa_org.REF_CONTACT_NAME';

	/** the column name for the REF_CONTACT_EMAIL field */
	const REF_CONTACT_EMAIL = 'afa_org.REF_CONTACT_EMAIL';

	/** the column name for the VPO_SOAP_SERVER_URL field */
	const VPO_SOAP_SERVER_URL = 'afa_org.VPO_SOAP_SERVER_URL';

	/** the column name for the VPO_REQUEST_POST_EMAIL field */
	const VPO_REQUEST_POST_EMAIL = 'afa_org.VPO_REQUEST_POST_EMAIL';

	/** the column name for the VPO_USER_ID field */
	const VPO_USER_ID = 'afa_org.VPO_USER_ID';

	/** the column name for the VPO_USER_PASSWORD field */
	const VPO_USER_PASSWORD = 'afa_org.VPO_USER_PASSWORD';

	/** the column name for the VPO_ORG_ID field */
	const VPO_ORG_ID = 'afa_org.VPO_ORG_ID';

	/** the column name for the AFIDS_REQUESTER_USER_NAME field */
	const AFIDS_REQUESTER_USER_NAME = 'afa_org.AFIDS_REQUESTER_USER_NAME';

	/** the column name for the AFIDS_REQUESTER_PASSWORD field */
	const AFIDS_REQUESTER_PASSWORD = 'afa_org.AFIDS_REQUESTER_PASSWORD';

	/** the column name for the AFIDS_SOAP_SERVER_URL field */
	const AFIDS_SOAP_SERVER_URL = 'afa_org.AFIDS_SOAP_SERVER_URL';

	/** the column name for the AFIDS_REQUEST_POST_EMAIL field */
	const AFIDS_REQUEST_POST_EMAIL = 'afa_org.AFIDS_REQUEST_POST_EMAIL';

	/** the column name for the PHONE_NUMBER1 field */
	const PHONE_NUMBER1 = 'afa_org.PHONE_NUMBER1';

	/** the column name for the PHONE_NUMBER2 field */
	const PHONE_NUMBER2 = 'afa_org.PHONE_NUMBER2';

	/**
	 * An identiy map to hold any loaded instances of AfaOrg objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array AfaOrg[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Name', 'OrgPhone', 'HomePageUrl', 'OrgFax', 'RefContactName', 'RefContactEmail', 'VpoSoapServerUrl', 'VpoRequestPostEmail', 'VpoUserId', 'VpoUserPassword', 'VpoOrgId', 'AfidsRequesterUserName', 'AfidsRequesterPassword', 'AfidsSoapServerUrl', 'AfidsRequestPostEmail', 'PhoneNumber1', 'PhoneNumber2', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'name', 'orgPhone', 'homePageUrl', 'orgFax', 'refContactName', 'refContactEmail', 'vpoSoapServerUrl', 'vpoRequestPostEmail', 'vpoUserId', 'vpoUserPassword', 'vpoOrgId', 'afidsRequesterUserName', 'afidsRequesterPassword', 'afidsSoapServerUrl', 'afidsRequestPostEmail', 'phoneNumber1', 'phoneNumber2', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::NAME, self::ORG_PHONE, self::HOME_PAGE_URL, self::ORG_FAX, self::REF_CONTACT_NAME, self::REF_CONTACT_EMAIL, self::VPO_SOAP_SERVER_URL, self::VPO_REQUEST_POST_EMAIL, self::VPO_USER_ID, self::VPO_USER_PASSWORD, self::VPO_ORG_ID, self::AFIDS_REQUESTER_USER_NAME, self::AFIDS_REQUESTER_PASSWORD, self::AFIDS_SOAP_SERVER_URL, self::AFIDS_REQUEST_POST_EMAIL, self::PHONE_NUMBER1, self::PHONE_NUMBER2, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'name', 'org_phone', 'home_page_url', 'org_fax', 'ref_contact_name', 'ref_contact_email', 'vpo_soap_server_url', 'vpo_request_post_email', 'vpo_user_id', 'vpo_user_password', 'vpo_org_id', 'afids_requester_user_name', 'afids_requester_password', 'afids_soap_server_url', 'afids_request_post_email', 'phone_number1', 'phone_number2', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Name' => 1, 'OrgPhone' => 2, 'HomePageUrl' => 3, 'OrgFax' => 4, 'RefContactName' => 5, 'RefContactEmail' => 6, 'VpoSoapServerUrl' => 7, 'VpoRequestPostEmail' => 8, 'VpoUserId' => 9, 'VpoUserPassword' => 10, 'VpoOrgId' => 11, 'AfidsRequesterUserName' => 12, 'AfidsRequesterPassword' => 13, 'AfidsSoapServerUrl' => 14, 'AfidsRequestPostEmail' => 15, 'PhoneNumber1' => 16, 'PhoneNumber2' => 17, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'name' => 1, 'orgPhone' => 2, 'homePageUrl' => 3, 'orgFax' => 4, 'refContactName' => 5, 'refContactEmail' => 6, 'vpoSoapServerUrl' => 7, 'vpoRequestPostEmail' => 8, 'vpoUserId' => 9, 'vpoUserPassword' => 10, 'vpoOrgId' => 11, 'afidsRequesterUserName' => 12, 'afidsRequesterPassword' => 13, 'afidsSoapServerUrl' => 14, 'afidsRequestPostEmail' => 15, 'phoneNumber1' => 16, 'phoneNumber2' => 17, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::NAME => 1, self::ORG_PHONE => 2, self::HOME_PAGE_URL => 3, self::ORG_FAX => 4, self::REF_CONTACT_NAME => 5, self::REF_CONTACT_EMAIL => 6, self::VPO_SOAP_SERVER_URL => 7, self::VPO_REQUEST_POST_EMAIL => 8, self::VPO_USER_ID => 9, self::VPO_USER_PASSWORD => 10, self::VPO_ORG_ID => 11, self::AFIDS_REQUESTER_USER_NAME => 12, self::AFIDS_REQUESTER_PASSWORD => 13, self::AFIDS_SOAP_SERVER_URL => 14, self::AFIDS_REQUEST_POST_EMAIL => 15, self::PHONE_NUMBER1 => 16, self::PHONE_NUMBER2 => 17, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'name' => 1, 'org_phone' => 2, 'home_page_url' => 3, 'org_fax' => 4, 'ref_contact_name' => 5, 'ref_contact_email' => 6, 'vpo_soap_server_url' => 7, 'vpo_request_post_email' => 8, 'vpo_user_id' => 9, 'vpo_user_password' => 10, 'vpo_org_id' => 11, 'afids_requester_user_name' => 12, 'afids_requester_password' => 13, 'afids_soap_server_url' => 14, 'afids_request_post_email' => 15, 'phone_number1' => 16, 'phone_number2' => 17, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new AfaOrgMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. AfaOrgPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(AfaOrgPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(AfaOrgPeer::ID);

		$criteria->addSelectColumn(AfaOrgPeer::NAME);

		$criteria->addSelectColumn(AfaOrgPeer::ORG_PHONE);

		$criteria->addSelectColumn(AfaOrgPeer::HOME_PAGE_URL);

		$criteria->addSelectColumn(AfaOrgPeer::ORG_FAX);

		$criteria->addSelectColumn(AfaOrgPeer::REF_CONTACT_NAME);

		$criteria->addSelectColumn(AfaOrgPeer::REF_CONTACT_EMAIL);

		$criteria->addSelectColumn(AfaOrgPeer::VPO_SOAP_SERVER_URL);

		$criteria->addSelectColumn(AfaOrgPeer::VPO_REQUEST_POST_EMAIL);

		$criteria->addSelectColumn(AfaOrgPeer::VPO_USER_ID);

		$criteria->addSelectColumn(AfaOrgPeer::VPO_USER_PASSWORD);

		$criteria->addSelectColumn(AfaOrgPeer::VPO_ORG_ID);

		$criteria->addSelectColumn(AfaOrgPeer::AFIDS_REQUESTER_USER_NAME);

		$criteria->addSelectColumn(AfaOrgPeer::AFIDS_REQUESTER_PASSWORD);

		$criteria->addSelectColumn(AfaOrgPeer::AFIDS_SOAP_SERVER_URL);

		$criteria->addSelectColumn(AfaOrgPeer::AFIDS_REQUEST_POST_EMAIL);

		$criteria->addSelectColumn(AfaOrgPeer::PHONE_NUMBER1);

		$criteria->addSelectColumn(AfaOrgPeer::PHONE_NUMBER2);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AfaOrgPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AfaOrgPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(AfaOrgPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseAfaOrgPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseAfaOrgPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     AfaOrg
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = AfaOrgPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return AfaOrgPeer::populateObjects(AfaOrgPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAfaOrgPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseAfaOrgPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(AfaOrgPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			AfaOrgPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      AfaOrg $value A AfaOrg object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(AfaOrg $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A AfaOrg object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof AfaOrg) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or AfaOrg object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     AfaOrg Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = AfaOrgPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = AfaOrgPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = AfaOrgPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				AfaOrgPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return AfaOrgPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a AfaOrg or Criteria object.
	 *
	 * @param      mixed $values Criteria or AfaOrg object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAfaOrgPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseAfaOrgPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(AfaOrgPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from AfaOrg object
		}

		if ($criteria->containsKey(AfaOrgPeer::ID) && $criteria->keyContainsValue(AfaOrgPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.AfaOrgPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseAfaOrgPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseAfaOrgPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a AfaOrg or Criteria object.
	 *
	 * @param      mixed $values Criteria or AfaOrg object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAfaOrgPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseAfaOrgPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(AfaOrgPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(AfaOrgPeer::ID);
			$selectCriteria->add(AfaOrgPeer::ID, $criteria->remove(AfaOrgPeer::ID), $comparison);

		} else { // $values is AfaOrg object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseAfaOrgPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseAfaOrgPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the afa_org table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AfaOrgPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(AfaOrgPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a AfaOrg or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or AfaOrg object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(AfaOrgPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			AfaOrgPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof AfaOrg) {
			// invalidate the cache for this single object
			AfaOrgPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(AfaOrgPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				AfaOrgPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given AfaOrg object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      AfaOrg $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(AfaOrg $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(AfaOrgPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(AfaOrgPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(AfaOrgPeer::DATABASE_NAME, AfaOrgPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = AfaOrgPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     AfaOrg
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = AfaOrgPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(AfaOrgPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(AfaOrgPeer::DATABASE_NAME);
		$criteria->add(AfaOrgPeer::ID, $pk);

		$v = AfaOrgPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AfaOrgPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(AfaOrgPeer::DATABASE_NAME);
			$criteria->add(AfaOrgPeer::ID, $pks, Criteria::IN);
			$objs = AfaOrgPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseAfaOrgPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the AfaOrgPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the AfaOrgPeer class:
//
// Propel::getDatabaseMap(AfaOrgPeer::DATABASE_NAME)->addTableBuilder(AfaOrgPeer::TABLE_NAME, AfaOrgPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseAfaOrgPeer::DATABASE_NAME)->addTableBuilder(BaseAfaOrgPeer::TABLE_NAME, BaseAfaOrgPeer::getMapBuilder());

