<?php

/**
 * Base static class for performing query and update operations on the 'rp_children_passengers' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue May 24 06:33:32 2011
 *
 * @package    lib.model.om
 */
abstract class BaseRpChildrenPassengersPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'rp_children_passengers';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.RpChildrenPassengers';

	/** The total number of columns. */
	const NUM_COLUMNS = 24;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the MISSION_DATE field */
	const MISSION_DATE = 'rp_children_passengers.MISSION_DATE';

	/** the column name for the DISPLAYDATE field */
	const DISPLAYDATE = 'rp_children_passengers.DISPLAYDATE';

	/** the column name for the FIRST_NAME field */
	const FIRST_NAME = 'rp_children_passengers.FIRST_NAME';

	/** the column name for the INITIAL field */
	const INITIAL = 'rp_children_passengers.INITIAL';

	/** the column name for the LAST_NAME field */
	const LAST_NAME = 'rp_children_passengers.LAST_NAME';

	/** the column name for the PASSCITY field */
	const PASSCITY = 'rp_children_passengers.PASSCITY';

	/** the column name for the PASSSTATE field */
	const PASSSTATE = 'rp_children_passengers.PASSSTATE';

	/** the column name for the PASSCOUNTY field */
	const PASSCOUNTY = 'rp_children_passengers.PASSCOUNTY';

	/** the column name for the ORIGINIDENT field */
	const ORIGINIDENT = 'rp_children_passengers.ORIGINIDENT';

	/** the column name for the ORIGINNAME field */
	const ORIGINNAME = 'rp_children_passengers.ORIGINNAME';

	/** the column name for the ORIGINCITY field */
	const ORIGINCITY = 'rp_children_passengers.ORIGINCITY';

	/** the column name for the ORIGINSTATE field */
	const ORIGINSTATE = 'rp_children_passengers.ORIGINSTATE';

	/** the column name for the DESTIDENT field */
	const DESTIDENT = 'rp_children_passengers.DESTIDENT';

	/** the column name for the DESTNAME field */
	const DESTNAME = 'rp_children_passengers.DESTNAME';

	/** the column name for the DESTCITY field */
	const DESTCITY = 'rp_children_passengers.DESTCITY';

	/** the column name for the DESTSTATE field */
	const DESTSTATE = 'rp_children_passengers.DESTSTATE';

	/** the column name for the AGENCYNAME field */
	const AGENCYNAME = 'rp_children_passengers.AGENCYNAME';

	/** the column name for the FACILITY_NAME field */
	const FACILITY_NAME = 'rp_children_passengers.FACILITY_NAME';

	/** the column name for the ILLNESS field */
	const ILLNESS = 'rp_children_passengers.ILLNESS';

	/** the column name for the PASSAGE field */
	const PASSAGE = 'rp_children_passengers.PASSAGE';

	/** the column name for the WING_ID field */
	const WING_ID = 'rp_children_passengers.WING_ID';

	/** the column name for the PASSENGERILLNESS field */
	const PASSENGERILLNESS = 'rp_children_passengers.PASSENGERILLNESS';

	/** the column name for the PASSENGERILLNESSID field */
	const PASSENGERILLNESSID = 'rp_children_passengers.PASSENGERILLNESSID';

	/** the column name for the ID field */
	const ID = 'rp_children_passengers.ID';

	/**
	 * An identiy map to hold any loaded instances of RpChildrenPassengers objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array RpChildrenPassengers[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('MissionDate', 'Displaydate', 'FirstName', 'Initial', 'LastName', 'Passcity', 'Passstate', 'Passcounty', 'Originident', 'Originname', 'Origincity', 'Originstate', 'Destident', 'Destname', 'Destcity', 'Deststate', 'Agencyname', 'FacilityName', 'Illness', 'Passage', 'WingId', 'Passengerillness', 'Passengerillnessid', 'Id', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('missionDate', 'displaydate', 'firstName', 'initial', 'lastName', 'passcity', 'passstate', 'passcounty', 'originident', 'originname', 'origincity', 'originstate', 'destident', 'destname', 'destcity', 'deststate', 'agencyname', 'facilityName', 'illness', 'passage', 'wingId', 'passengerillness', 'passengerillnessid', 'id', ),
		BasePeer::TYPE_COLNAME => array (self::MISSION_DATE, self::DISPLAYDATE, self::FIRST_NAME, self::INITIAL, self::LAST_NAME, self::PASSCITY, self::PASSSTATE, self::PASSCOUNTY, self::ORIGINIDENT, self::ORIGINNAME, self::ORIGINCITY, self::ORIGINSTATE, self::DESTIDENT, self::DESTNAME, self::DESTCITY, self::DESTSTATE, self::AGENCYNAME, self::FACILITY_NAME, self::ILLNESS, self::PASSAGE, self::WING_ID, self::PASSENGERILLNESS, self::PASSENGERILLNESSID, self::ID, ),
		BasePeer::TYPE_FIELDNAME => array ('mission_date', 'displayDate', 'first_name', 'initial', 'last_name', 'passCity', 'passState', 'passCounty', 'originIdent', 'originName', 'originCity', 'originState', 'destIdent', 'destName', 'destCity', 'destState', 'agencyName', 'facility_name', 'illness', 'passAge', 'wing_id', 'passengerIllness', 'passengerIllnessID', 'id', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('MissionDate' => 0, 'Displaydate' => 1, 'FirstName' => 2, 'Initial' => 3, 'LastName' => 4, 'Passcity' => 5, 'Passstate' => 6, 'Passcounty' => 7, 'Originident' => 8, 'Originname' => 9, 'Origincity' => 10, 'Originstate' => 11, 'Destident' => 12, 'Destname' => 13, 'Destcity' => 14, 'Deststate' => 15, 'Agencyname' => 16, 'FacilityName' => 17, 'Illness' => 18, 'Passage' => 19, 'WingId' => 20, 'Passengerillness' => 21, 'Passengerillnessid' => 22, 'Id' => 23, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('missionDate' => 0, 'displaydate' => 1, 'firstName' => 2, 'initial' => 3, 'lastName' => 4, 'passcity' => 5, 'passstate' => 6, 'passcounty' => 7, 'originident' => 8, 'originname' => 9, 'origincity' => 10, 'originstate' => 11, 'destident' => 12, 'destname' => 13, 'destcity' => 14, 'deststate' => 15, 'agencyname' => 16, 'facilityName' => 17, 'illness' => 18, 'passage' => 19, 'wingId' => 20, 'passengerillness' => 21, 'passengerillnessid' => 22, 'id' => 23, ),
		BasePeer::TYPE_COLNAME => array (self::MISSION_DATE => 0, self::DISPLAYDATE => 1, self::FIRST_NAME => 2, self::INITIAL => 3, self::LAST_NAME => 4, self::PASSCITY => 5, self::PASSSTATE => 6, self::PASSCOUNTY => 7, self::ORIGINIDENT => 8, self::ORIGINNAME => 9, self::ORIGINCITY => 10, self::ORIGINSTATE => 11, self::DESTIDENT => 12, self::DESTNAME => 13, self::DESTCITY => 14, self::DESTSTATE => 15, self::AGENCYNAME => 16, self::FACILITY_NAME => 17, self::ILLNESS => 18, self::PASSAGE => 19, self::WING_ID => 20, self::PASSENGERILLNESS => 21, self::PASSENGERILLNESSID => 22, self::ID => 23, ),
		BasePeer::TYPE_FIELDNAME => array ('mission_date' => 0, 'displayDate' => 1, 'first_name' => 2, 'initial' => 3, 'last_name' => 4, 'passCity' => 5, 'passState' => 6, 'passCounty' => 7, 'originIdent' => 8, 'originName' => 9, 'originCity' => 10, 'originState' => 11, 'destIdent' => 12, 'destName' => 13, 'destCity' => 14, 'destState' => 15, 'agencyName' => 16, 'facility_name' => 17, 'illness' => 18, 'passAge' => 19, 'wing_id' => 20, 'passengerIllness' => 21, 'passengerIllnessID' => 22, 'id' => 23, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new RpChildrenPassengersMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. RpChildrenPassengersPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(RpChildrenPassengersPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(RpChildrenPassengersPeer::MISSION_DATE);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::DISPLAYDATE);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::FIRST_NAME);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::INITIAL);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::LAST_NAME);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::PASSCITY);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::PASSSTATE);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::PASSCOUNTY);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::ORIGINIDENT);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::ORIGINNAME);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::ORIGINCITY);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::ORIGINSTATE);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::DESTIDENT);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::DESTNAME);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::DESTCITY);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::DESTSTATE);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::AGENCYNAME);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::FACILITY_NAME);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::ILLNESS);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::PASSAGE);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::WING_ID);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::PASSENGERILLNESS);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::PASSENGERILLNESSID);

		$criteria->addSelectColumn(RpChildrenPassengersPeer::ID);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(RpChildrenPassengersPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			RpChildrenPassengersPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(RpChildrenPassengersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseRpChildrenPassengersPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseRpChildrenPassengersPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     RpChildrenPassengers
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = RpChildrenPassengersPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return RpChildrenPassengersPeer::populateObjects(RpChildrenPassengersPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRpChildrenPassengersPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseRpChildrenPassengersPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(RpChildrenPassengersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			RpChildrenPassengersPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      RpChildrenPassengers $value A RpChildrenPassengers object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(RpChildrenPassengers $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A RpChildrenPassengers object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof RpChildrenPassengers) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or RpChildrenPassengers object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     RpChildrenPassengers Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 23] === null) {
			return null;
		}
		return (string) $row[$startcol + 23];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = RpChildrenPassengersPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = RpChildrenPassengersPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = RpChildrenPassengersPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				RpChildrenPassengersPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return RpChildrenPassengersPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a RpChildrenPassengers or Criteria object.
	 *
	 * @param      mixed $values Criteria or RpChildrenPassengers object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRpChildrenPassengersPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseRpChildrenPassengersPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(RpChildrenPassengersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from RpChildrenPassengers object
		}

		if ($criteria->containsKey(RpChildrenPassengersPeer::ID) && $criteria->keyContainsValue(RpChildrenPassengersPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.RpChildrenPassengersPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseRpChildrenPassengersPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseRpChildrenPassengersPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a RpChildrenPassengers or Criteria object.
	 *
	 * @param      mixed $values Criteria or RpChildrenPassengers object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseRpChildrenPassengersPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseRpChildrenPassengersPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(RpChildrenPassengersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(RpChildrenPassengersPeer::ID);
			$selectCriteria->add(RpChildrenPassengersPeer::ID, $criteria->remove(RpChildrenPassengersPeer::ID), $comparison);

		} else { // $values is RpChildrenPassengers object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseRpChildrenPassengersPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseRpChildrenPassengersPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the rp_children_passengers table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(RpChildrenPassengersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(RpChildrenPassengersPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a RpChildrenPassengers or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or RpChildrenPassengers object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(RpChildrenPassengersPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			RpChildrenPassengersPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof RpChildrenPassengers) {
			// invalidate the cache for this single object
			RpChildrenPassengersPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(RpChildrenPassengersPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				RpChildrenPassengersPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given RpChildrenPassengers object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      RpChildrenPassengers $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(RpChildrenPassengers $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(RpChildrenPassengersPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(RpChildrenPassengersPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(RpChildrenPassengersPeer::DATABASE_NAME, RpChildrenPassengersPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = RpChildrenPassengersPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     RpChildrenPassengers
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = RpChildrenPassengersPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(RpChildrenPassengersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(RpChildrenPassengersPeer::DATABASE_NAME);
		$criteria->add(RpChildrenPassengersPeer::ID, $pk);

		$v = RpChildrenPassengersPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(RpChildrenPassengersPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(RpChildrenPassengersPeer::DATABASE_NAME);
			$criteria->add(RpChildrenPassengersPeer::ID, $pks, Criteria::IN);
			$objs = RpChildrenPassengersPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseRpChildrenPassengersPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the RpChildrenPassengersPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the RpChildrenPassengersPeer class:
//
// Propel::getDatabaseMap(RpChildrenPassengersPeer::DATABASE_NAME)->addTableBuilder(RpChildrenPassengersPeer::TABLE_NAME, RpChildrenPassengersPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseRpChildrenPassengersPeer::DATABASE_NAME)->addTableBuilder(BaseRpChildrenPassengersPeer::TABLE_NAME, BaseRpChildrenPassengersPeer::getMapBuilder());

