<?php

/**
 * Base class that represents a row from the 'vpo_request_cargo' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue May 24 06:33:33 2011
 *
 * @package    lib.model.om
 */
abstract class BaseVpoRequestCargo extends BaseObject  implements Persistent {


  const PEER = 'VpoRequestCargoPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        VpoRequestCargoPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the request_id field.
	 * @var        int
	 */
	protected $request_id;

	/**
	 * The value for the hazardous field.
	 * @var        int
	 */
	protected $hazardous;

	/**
	 * The value for the cargo_type field.
	 * @var        string
	 */
	protected $cargo_type;

	/**
	 * The value for the weight field.
	 * @var        int
	 */
	protected $weight;

	/**
	 * The value for the height field.
	 * @var        int
	 */
	protected $height;

	/**
	 * The value for the length field.
	 * @var        int
	 */
	protected $length;

	/**
	 * The value for the width field.
	 * @var        int
	 */
	protected $width;

	/**
	 * The value for the special_handling field.
	 * @var        string
	 */
	protected $special_handling;

	/**
	 * The value for the oc_first_name field.
	 * @var        string
	 */
	protected $oc_first_name;

	/**
	 * The value for the oc_last_name field.
	 * @var        string
	 */
	protected $oc_last_name;

	/**
	 * The value for the oc_day_phone field.
	 * @var        string
	 */
	protected $oc_day_phone;

	/**
	 * The value for the oc_day_comment field.
	 * @var        string
	 */
	protected $oc_day_comment;

	/**
	 * The value for the oc_mobile_phone field.
	 * @var        string
	 */
	protected $oc_mobile_phone;

	/**
	 * The value for the oc_mobile_comment field.
	 * @var        string
	 */
	protected $oc_mobile_comment;

	/**
	 * The value for the oc_other_phone1 field.
	 * @var        string
	 */
	protected $oc_other_phone1;

	/**
	 * The value for the oc_other_comment1 field.
	 * @var        string
	 */
	protected $oc_other_comment1;

	/**
	 * The value for the oc_other_phone2 field.
	 * @var        string
	 */
	protected $oc_other_phone2;

	/**
	 * The value for the oc_other_comment2 field.
	 * @var        string
	 */
	protected $oc_other_comment2;

	/**
	 * The value for the oc_email field.
	 * @var        string
	 */
	protected $oc_email;

	/**
	 * The value for the oc_alt_email field.
	 * @var        string
	 */
	protected $oc_alt_email;

	/**
	 * The value for the dc_first_name field.
	 * @var        string
	 */
	protected $dc_first_name;

	/**
	 * The value for the dc_last_name field.
	 * @var        string
	 */
	protected $dc_last_name;

	/**
	 * The value for the dc_day_phone field.
	 * @var        string
	 */
	protected $dc_day_phone;

	/**
	 * The value for the dc_day_comment field.
	 * @var        string
	 */
	protected $dc_day_comment;

	/**
	 * The value for the dc_mobile_hone field.
	 * @var        int
	 */
	protected $dc_mobile_hone;

	/**
	 * The value for the dc_mobile_comment field.
	 * @var        string
	 */
	protected $dc_mobile_comment;

	/**
	 * The value for the dc_other_phone1 field.
	 * @var        string
	 */
	protected $dc_other_phone1;

	/**
	 * The value for the dc_other_comment1 field.
	 * @var        string
	 */
	protected $dc_other_comment1;

	/**
	 * The value for the dc_other_phone2 field.
	 * @var        string
	 */
	protected $dc_other_phone2;

	/**
	 * The value for the dc_other_comment2 field.
	 * @var        string
	 */
	protected $dc_other_comment2;

	/**
	 * The value for the dc_email field.
	 * @var        string
	 */
	protected $dc_email;

	/**
	 * The value for the dc_alt_email field.
	 * @var        string
	 */
	protected $dc_alt_email;

	/**
	 * The value for the item_description field.
	 * @var        string
	 */
	protected $item_description;

	/**
	 * @var        VpoRequest
	 */
	protected $aVpoRequest;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseVpoRequestCargo object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [request_id] column value.
	 * 
	 * @return     int
	 */
	public function getRequestId()
	{
		return $this->request_id;
	}

	/**
	 * Get the [hazardous] column value.
	 * 
	 * @return     int
	 */
	public function getHazardous()
	{
		return $this->hazardous;
	}

	/**
	 * Get the [cargo_type] column value.
	 * 
	 * @return     string
	 */
	public function getCargoType()
	{
		return $this->cargo_type;
	}

	/**
	 * Get the [weight] column value.
	 * 
	 * @return     int
	 */
	public function getWeight()
	{
		return $this->weight;
	}

	/**
	 * Get the [height] column value.
	 * 
	 * @return     int
	 */
	public function getHeight()
	{
		return $this->height;
	}

	/**
	 * Get the [length] column value.
	 * 
	 * @return     int
	 */
	public function getLength()
	{
		return $this->length;
	}

	/**
	 * Get the [width] column value.
	 * 
	 * @return     int
	 */
	public function getWidth()
	{
		return $this->width;
	}

	/**
	 * Get the [special_handling] column value.
	 * 
	 * @return     string
	 */
	public function getSpecialHandling()
	{
		return $this->special_handling;
	}

	/**
	 * Get the [oc_first_name] column value.
	 * 
	 * @return     string
	 */
	public function getOcFirstName()
	{
		return $this->oc_first_name;
	}

	/**
	 * Get the [oc_last_name] column value.
	 * 
	 * @return     string
	 */
	public function getOcLastName()
	{
		return $this->oc_last_name;
	}

	/**
	 * Get the [oc_day_phone] column value.
	 * 
	 * @return     string
	 */
	public function getOcDayPhone()
	{
		return $this->oc_day_phone;
	}

	/**
	 * Get the [oc_day_comment] column value.
	 * 
	 * @return     string
	 */
	public function getOcDayComment()
	{
		return $this->oc_day_comment;
	}

	/**
	 * Get the [oc_mobile_phone] column value.
	 * 
	 * @return     string
	 */
	public function getOcMobilePhone()
	{
		return $this->oc_mobile_phone;
	}

	/**
	 * Get the [oc_mobile_comment] column value.
	 * 
	 * @return     string
	 */
	public function getOcMobileComment()
	{
		return $this->oc_mobile_comment;
	}

	/**
	 * Get the [oc_other_phone1] column value.
	 * 
	 * @return     string
	 */
	public function getOcOtherPhone1()
	{
		return $this->oc_other_phone1;
	}

	/**
	 * Get the [oc_other_comment1] column value.
	 * 
	 * @return     string
	 */
	public function getOcOtherComment1()
	{
		return $this->oc_other_comment1;
	}

	/**
	 * Get the [oc_other_phone2] column value.
	 * 
	 * @return     string
	 */
	public function getOcOtherPhone2()
	{
		return $this->oc_other_phone2;
	}

	/**
	 * Get the [oc_other_comment2] column value.
	 * 
	 * @return     string
	 */
	public function getOcOtherComment2()
	{
		return $this->oc_other_comment2;
	}

	/**
	 * Get the [oc_email] column value.
	 * 
	 * @return     string
	 */
	public function getOcEmail()
	{
		return $this->oc_email;
	}

	/**
	 * Get the [oc_alt_email] column value.
	 * 
	 * @return     string
	 */
	public function getOcAltEmail()
	{
		return $this->oc_alt_email;
	}

	/**
	 * Get the [dc_first_name] column value.
	 * 
	 * @return     string
	 */
	public function getDcFirstName()
	{
		return $this->dc_first_name;
	}

	/**
	 * Get the [dc_last_name] column value.
	 * 
	 * @return     string
	 */
	public function getDcLastName()
	{
		return $this->dc_last_name;
	}

	/**
	 * Get the [dc_day_phone] column value.
	 * 
	 * @return     string
	 */
	public function getDcDayPhone()
	{
		return $this->dc_day_phone;
	}

	/**
	 * Get the [dc_day_comment] column value.
	 * 
	 * @return     string
	 */
	public function getDcDayComment()
	{
		return $this->dc_day_comment;
	}

	/**
	 * Get the [dc_mobile_hone] column value.
	 * 
	 * @return     int
	 */
	public function getDcMobileHone()
	{
		return $this->dc_mobile_hone;
	}

	/**
	 * Get the [dc_mobile_comment] column value.
	 * 
	 * @return     string
	 */
	public function getDcMobileComment()
	{
		return $this->dc_mobile_comment;
	}

	/**
	 * Get the [dc_other_phone1] column value.
	 * 
	 * @return     string
	 */
	public function getDcOtherPhone1()
	{
		return $this->dc_other_phone1;
	}

	/**
	 * Get the [dc_other_comment1] column value.
	 * 
	 * @return     string
	 */
	public function getDcOtherComment1()
	{
		return $this->dc_other_comment1;
	}

	/**
	 * Get the [dc_other_phone2] column value.
	 * 
	 * @return     string
	 */
	public function getDcOtherPhone2()
	{
		return $this->dc_other_phone2;
	}

	/**
	 * Get the [dc_other_comment2] column value.
	 * 
	 * @return     string
	 */
	public function getDcOtherComment2()
	{
		return $this->dc_other_comment2;
	}

	/**
	 * Get the [dc_email] column value.
	 * 
	 * @return     string
	 */
	public function getDcEmail()
	{
		return $this->dc_email;
	}

	/**
	 * Get the [dc_alt_email] column value.
	 * 
	 * @return     string
	 */
	public function getDcAltEmail()
	{
		return $this->dc_alt_email;
	}

	/**
	 * Get the [item_description] column value.
	 * 
	 * @return     string
	 */
	public function getItemDescription()
	{
		return $this->item_description;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [request_id] column.
	 * 
	 * @param      int $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setRequestId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->request_id !== $v) {
			$this->request_id = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::REQUEST_ID;
		}

		if ($this->aVpoRequest !== null && $this->aVpoRequest->getId() !== $v) {
			$this->aVpoRequest = null;
		}

		return $this;
	} // setRequestId()

	/**
	 * Set the value of [hazardous] column.
	 * 
	 * @param      int $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setHazardous($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->hazardous !== $v) {
			$this->hazardous = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::HAZARDOUS;
		}

		return $this;
	} // setHazardous()

	/**
	 * Set the value of [cargo_type] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setCargoType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cargo_type !== $v) {
			$this->cargo_type = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::CARGO_TYPE;
		}

		return $this;
	} // setCargoType()

	/**
	 * Set the value of [weight] column.
	 * 
	 * @param      int $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setWeight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->weight !== $v) {
			$this->weight = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::WEIGHT;
		}

		return $this;
	} // setWeight()

	/**
	 * Set the value of [height] column.
	 * 
	 * @param      int $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setHeight($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->height !== $v) {
			$this->height = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::HEIGHT;
		}

		return $this;
	} // setHeight()

	/**
	 * Set the value of [length] column.
	 * 
	 * @param      int $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setLength($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->length !== $v) {
			$this->length = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::LENGTH;
		}

		return $this;
	} // setLength()

	/**
	 * Set the value of [width] column.
	 * 
	 * @param      int $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setWidth($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->width !== $v) {
			$this->width = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::WIDTH;
		}

		return $this;
	} // setWidth()

	/**
	 * Set the value of [special_handling] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setSpecialHandling($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->special_handling !== $v) {
			$this->special_handling = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::SPECIAL_HANDLING;
		}

		return $this;
	} // setSpecialHandling()

	/**
	 * Set the value of [oc_first_name] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcFirstName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_first_name !== $v) {
			$this->oc_first_name = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_FIRST_NAME;
		}

		return $this;
	} // setOcFirstName()

	/**
	 * Set the value of [oc_last_name] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcLastName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_last_name !== $v) {
			$this->oc_last_name = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_LAST_NAME;
		}

		return $this;
	} // setOcLastName()

	/**
	 * Set the value of [oc_day_phone] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcDayPhone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_day_phone !== $v) {
			$this->oc_day_phone = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_DAY_PHONE;
		}

		return $this;
	} // setOcDayPhone()

	/**
	 * Set the value of [oc_day_comment] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcDayComment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_day_comment !== $v) {
			$this->oc_day_comment = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_DAY_COMMENT;
		}

		return $this;
	} // setOcDayComment()

	/**
	 * Set the value of [oc_mobile_phone] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcMobilePhone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_mobile_phone !== $v) {
			$this->oc_mobile_phone = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_MOBILE_PHONE;
		}

		return $this;
	} // setOcMobilePhone()

	/**
	 * Set the value of [oc_mobile_comment] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcMobileComment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_mobile_comment !== $v) {
			$this->oc_mobile_comment = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_MOBILE_COMMENT;
		}

		return $this;
	} // setOcMobileComment()

	/**
	 * Set the value of [oc_other_phone1] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcOtherPhone1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_other_phone1 !== $v) {
			$this->oc_other_phone1 = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_OTHER_PHONE1;
		}

		return $this;
	} // setOcOtherPhone1()

	/**
	 * Set the value of [oc_other_comment1] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcOtherComment1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_other_comment1 !== $v) {
			$this->oc_other_comment1 = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_OTHER_COMMENT1;
		}

		return $this;
	} // setOcOtherComment1()

	/**
	 * Set the value of [oc_other_phone2] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcOtherPhone2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_other_phone2 !== $v) {
			$this->oc_other_phone2 = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_OTHER_PHONE2;
		}

		return $this;
	} // setOcOtherPhone2()

	/**
	 * Set the value of [oc_other_comment2] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcOtherComment2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_other_comment2 !== $v) {
			$this->oc_other_comment2 = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_OTHER_COMMENT2;
		}

		return $this;
	} // setOcOtherComment2()

	/**
	 * Set the value of [oc_email] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_email !== $v) {
			$this->oc_email = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_EMAIL;
		}

		return $this;
	} // setOcEmail()

	/**
	 * Set the value of [oc_alt_email] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setOcAltEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->oc_alt_email !== $v) {
			$this->oc_alt_email = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::OC_ALT_EMAIL;
		}

		return $this;
	} // setOcAltEmail()

	/**
	 * Set the value of [dc_first_name] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcFirstName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dc_first_name !== $v) {
			$this->dc_first_name = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_FIRST_NAME;
		}

		return $this;
	} // setDcFirstName()

	/**
	 * Set the value of [dc_last_name] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcLastName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dc_last_name !== $v) {
			$this->dc_last_name = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_LAST_NAME;
		}

		return $this;
	} // setDcLastName()

	/**
	 * Set the value of [dc_day_phone] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcDayPhone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dc_day_phone !== $v) {
			$this->dc_day_phone = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_DAY_PHONE;
		}

		return $this;
	} // setDcDayPhone()

	/**
	 * Set the value of [dc_day_comment] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcDayComment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dc_day_comment !== $v) {
			$this->dc_day_comment = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_DAY_COMMENT;
		}

		return $this;
	} // setDcDayComment()

	/**
	 * Set the value of [dc_mobile_hone] column.
	 * 
	 * @param      int $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcMobileHone($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->dc_mobile_hone !== $v) {
			$this->dc_mobile_hone = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_MOBILE_HONE;
		}

		return $this;
	} // setDcMobileHone()

	/**
	 * Set the value of [dc_mobile_comment] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcMobileComment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dc_mobile_comment !== $v) {
			$this->dc_mobile_comment = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_MOBILE_COMMENT;
		}

		return $this;
	} // setDcMobileComment()

	/**
	 * Set the value of [dc_other_phone1] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcOtherPhone1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dc_other_phone1 !== $v) {
			$this->dc_other_phone1 = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_OTHER_PHONE1;
		}

		return $this;
	} // setDcOtherPhone1()

	/**
	 * Set the value of [dc_other_comment1] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcOtherComment1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dc_other_comment1 !== $v) {
			$this->dc_other_comment1 = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_OTHER_COMMENT1;
		}

		return $this;
	} // setDcOtherComment1()

	/**
	 * Set the value of [dc_other_phone2] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcOtherPhone2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dc_other_phone2 !== $v) {
			$this->dc_other_phone2 = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_OTHER_PHONE2;
		}

		return $this;
	} // setDcOtherPhone2()

	/**
	 * Set the value of [dc_other_comment2] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcOtherComment2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dc_other_comment2 !== $v) {
			$this->dc_other_comment2 = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_OTHER_COMMENT2;
		}

		return $this;
	} // setDcOtherComment2()

	/**
	 * Set the value of [dc_email] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dc_email !== $v) {
			$this->dc_email = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_EMAIL;
		}

		return $this;
	} // setDcEmail()

	/**
	 * Set the value of [dc_alt_email] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setDcAltEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->dc_alt_email !== $v) {
			$this->dc_alt_email = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::DC_ALT_EMAIL;
		}

		return $this;
	} // setDcAltEmail()

	/**
	 * Set the value of [item_description] column.
	 * 
	 * @param      string $v new value
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 */
	public function setItemDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->item_description !== $v) {
			$this->item_description = $v;
			$this->modifiedColumns[] = VpoRequestCargoPeer::ITEM_DESCRIPTION;
		}

		return $this;
	} // setItemDescription()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->request_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->hazardous = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->cargo_type = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->weight = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->height = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->length = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->width = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->special_handling = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->oc_first_name = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->oc_last_name = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->oc_day_phone = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->oc_day_comment = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->oc_mobile_phone = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->oc_mobile_comment = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->oc_other_phone1 = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->oc_other_comment1 = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->oc_other_phone2 = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->oc_other_comment2 = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->oc_email = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->oc_alt_email = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
			$this->dc_first_name = ($row[$startcol + 21] !== null) ? (string) $row[$startcol + 21] : null;
			$this->dc_last_name = ($row[$startcol + 22] !== null) ? (string) $row[$startcol + 22] : null;
			$this->dc_day_phone = ($row[$startcol + 23] !== null) ? (string) $row[$startcol + 23] : null;
			$this->dc_day_comment = ($row[$startcol + 24] !== null) ? (string) $row[$startcol + 24] : null;
			$this->dc_mobile_hone = ($row[$startcol + 25] !== null) ? (int) $row[$startcol + 25] : null;
			$this->dc_mobile_comment = ($row[$startcol + 26] !== null) ? (string) $row[$startcol + 26] : null;
			$this->dc_other_phone1 = ($row[$startcol + 27] !== null) ? (string) $row[$startcol + 27] : null;
			$this->dc_other_comment1 = ($row[$startcol + 28] !== null) ? (string) $row[$startcol + 28] : null;
			$this->dc_other_phone2 = ($row[$startcol + 29] !== null) ? (string) $row[$startcol + 29] : null;
			$this->dc_other_comment2 = ($row[$startcol + 30] !== null) ? (string) $row[$startcol + 30] : null;
			$this->dc_email = ($row[$startcol + 31] !== null) ? (string) $row[$startcol + 31] : null;
			$this->dc_alt_email = ($row[$startcol + 32] !== null) ? (string) $row[$startcol + 32] : null;
			$this->item_description = ($row[$startcol + 33] !== null) ? (string) $row[$startcol + 33] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 34; // 34 = VpoRequestCargoPeer::NUM_COLUMNS - VpoRequestCargoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating VpoRequestCargo object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aVpoRequest !== null && $this->request_id !== $this->aVpoRequest->getId()) {
			$this->aVpoRequest = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VpoRequestCargoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = VpoRequestCargoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aVpoRequest = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseVpoRequestCargo:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VpoRequestCargoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			VpoRequestCargoPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseVpoRequestCargo:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseVpoRequestCargo:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(VpoRequestCargoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseVpoRequestCargo:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			VpoRequestCargoPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aVpoRequest !== null) {
				if ($this->aVpoRequest->isModified() || $this->aVpoRequest->isNew()) {
					$affectedRows += $this->aVpoRequest->save($con);
				}
				$this->setVpoRequest($this->aVpoRequest);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = VpoRequestCargoPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = VpoRequestCargoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += VpoRequestCargoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aVpoRequest !== null) {
				if (!$this->aVpoRequest->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aVpoRequest->getValidationFailures());
				}
			}


			if (($retval = VpoRequestCargoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = VpoRequestCargoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getRequestId();
				break;
			case 2:
				return $this->getHazardous();
				break;
			case 3:
				return $this->getCargoType();
				break;
			case 4:
				return $this->getWeight();
				break;
			case 5:
				return $this->getHeight();
				break;
			case 6:
				return $this->getLength();
				break;
			case 7:
				return $this->getWidth();
				break;
			case 8:
				return $this->getSpecialHandling();
				break;
			case 9:
				return $this->getOcFirstName();
				break;
			case 10:
				return $this->getOcLastName();
				break;
			case 11:
				return $this->getOcDayPhone();
				break;
			case 12:
				return $this->getOcDayComment();
				break;
			case 13:
				return $this->getOcMobilePhone();
				break;
			case 14:
				return $this->getOcMobileComment();
				break;
			case 15:
				return $this->getOcOtherPhone1();
				break;
			case 16:
				return $this->getOcOtherComment1();
				break;
			case 17:
				return $this->getOcOtherPhone2();
				break;
			case 18:
				return $this->getOcOtherComment2();
				break;
			case 19:
				return $this->getOcEmail();
				break;
			case 20:
				return $this->getOcAltEmail();
				break;
			case 21:
				return $this->getDcFirstName();
				break;
			case 22:
				return $this->getDcLastName();
				break;
			case 23:
				return $this->getDcDayPhone();
				break;
			case 24:
				return $this->getDcDayComment();
				break;
			case 25:
				return $this->getDcMobileHone();
				break;
			case 26:
				return $this->getDcMobileComment();
				break;
			case 27:
				return $this->getDcOtherPhone1();
				break;
			case 28:
				return $this->getDcOtherComment1();
				break;
			case 29:
				return $this->getDcOtherPhone2();
				break;
			case 30:
				return $this->getDcOtherComment2();
				break;
			case 31:
				return $this->getDcEmail();
				break;
			case 32:
				return $this->getDcAltEmail();
				break;
			case 33:
				return $this->getItemDescription();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = VpoRequestCargoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getRequestId(),
			$keys[2] => $this->getHazardous(),
			$keys[3] => $this->getCargoType(),
			$keys[4] => $this->getWeight(),
			$keys[5] => $this->getHeight(),
			$keys[6] => $this->getLength(),
			$keys[7] => $this->getWidth(),
			$keys[8] => $this->getSpecialHandling(),
			$keys[9] => $this->getOcFirstName(),
			$keys[10] => $this->getOcLastName(),
			$keys[11] => $this->getOcDayPhone(),
			$keys[12] => $this->getOcDayComment(),
			$keys[13] => $this->getOcMobilePhone(),
			$keys[14] => $this->getOcMobileComment(),
			$keys[15] => $this->getOcOtherPhone1(),
			$keys[16] => $this->getOcOtherComment1(),
			$keys[17] => $this->getOcOtherPhone2(),
			$keys[18] => $this->getOcOtherComment2(),
			$keys[19] => $this->getOcEmail(),
			$keys[20] => $this->getOcAltEmail(),
			$keys[21] => $this->getDcFirstName(),
			$keys[22] => $this->getDcLastName(),
			$keys[23] => $this->getDcDayPhone(),
			$keys[24] => $this->getDcDayComment(),
			$keys[25] => $this->getDcMobileHone(),
			$keys[26] => $this->getDcMobileComment(),
			$keys[27] => $this->getDcOtherPhone1(),
			$keys[28] => $this->getDcOtherComment1(),
			$keys[29] => $this->getDcOtherPhone2(),
			$keys[30] => $this->getDcOtherComment2(),
			$keys[31] => $this->getDcEmail(),
			$keys[32] => $this->getDcAltEmail(),
			$keys[33] => $this->getItemDescription(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = VpoRequestCargoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setRequestId($value);
				break;
			case 2:
				$this->setHazardous($value);
				break;
			case 3:
				$this->setCargoType($value);
				break;
			case 4:
				$this->setWeight($value);
				break;
			case 5:
				$this->setHeight($value);
				break;
			case 6:
				$this->setLength($value);
				break;
			case 7:
				$this->setWidth($value);
				break;
			case 8:
				$this->setSpecialHandling($value);
				break;
			case 9:
				$this->setOcFirstName($value);
				break;
			case 10:
				$this->setOcLastName($value);
				break;
			case 11:
				$this->setOcDayPhone($value);
				break;
			case 12:
				$this->setOcDayComment($value);
				break;
			case 13:
				$this->setOcMobilePhone($value);
				break;
			case 14:
				$this->setOcMobileComment($value);
				break;
			case 15:
				$this->setOcOtherPhone1($value);
				break;
			case 16:
				$this->setOcOtherComment1($value);
				break;
			case 17:
				$this->setOcOtherPhone2($value);
				break;
			case 18:
				$this->setOcOtherComment2($value);
				break;
			case 19:
				$this->setOcEmail($value);
				break;
			case 20:
				$this->setOcAltEmail($value);
				break;
			case 21:
				$this->setDcFirstName($value);
				break;
			case 22:
				$this->setDcLastName($value);
				break;
			case 23:
				$this->setDcDayPhone($value);
				break;
			case 24:
				$this->setDcDayComment($value);
				break;
			case 25:
				$this->setDcMobileHone($value);
				break;
			case 26:
				$this->setDcMobileComment($value);
				break;
			case 27:
				$this->setDcOtherPhone1($value);
				break;
			case 28:
				$this->setDcOtherComment1($value);
				break;
			case 29:
				$this->setDcOtherPhone2($value);
				break;
			case 30:
				$this->setDcOtherComment2($value);
				break;
			case 31:
				$this->setDcEmail($value);
				break;
			case 32:
				$this->setDcAltEmail($value);
				break;
			case 33:
				$this->setItemDescription($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = VpoRequestCargoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setRequestId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setHazardous($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCargoType($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setWeight($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setHeight($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setLength($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setWidth($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setSpecialHandling($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setOcFirstName($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setOcLastName($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setOcDayPhone($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setOcDayComment($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setOcMobilePhone($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setOcMobileComment($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setOcOtherPhone1($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setOcOtherComment1($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setOcOtherPhone2($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setOcOtherComment2($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setOcEmail($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setOcAltEmail($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setDcFirstName($arr[$keys[21]]);
		if (array_key_exists($keys[22], $arr)) $this->setDcLastName($arr[$keys[22]]);
		if (array_key_exists($keys[23], $arr)) $this->setDcDayPhone($arr[$keys[23]]);
		if (array_key_exists($keys[24], $arr)) $this->setDcDayComment($arr[$keys[24]]);
		if (array_key_exists($keys[25], $arr)) $this->setDcMobileHone($arr[$keys[25]]);
		if (array_key_exists($keys[26], $arr)) $this->setDcMobileComment($arr[$keys[26]]);
		if (array_key_exists($keys[27], $arr)) $this->setDcOtherPhone1($arr[$keys[27]]);
		if (array_key_exists($keys[28], $arr)) $this->setDcOtherComment1($arr[$keys[28]]);
		if (array_key_exists($keys[29], $arr)) $this->setDcOtherPhone2($arr[$keys[29]]);
		if (array_key_exists($keys[30], $arr)) $this->setDcOtherComment2($arr[$keys[30]]);
		if (array_key_exists($keys[31], $arr)) $this->setDcEmail($arr[$keys[31]]);
		if (array_key_exists($keys[32], $arr)) $this->setDcAltEmail($arr[$keys[32]]);
		if (array_key_exists($keys[33], $arr)) $this->setItemDescription($arr[$keys[33]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(VpoRequestCargoPeer::DATABASE_NAME);

		if ($this->isColumnModified(VpoRequestCargoPeer::ID)) $criteria->add(VpoRequestCargoPeer::ID, $this->id);
		if ($this->isColumnModified(VpoRequestCargoPeer::REQUEST_ID)) $criteria->add(VpoRequestCargoPeer::REQUEST_ID, $this->request_id);
		if ($this->isColumnModified(VpoRequestCargoPeer::HAZARDOUS)) $criteria->add(VpoRequestCargoPeer::HAZARDOUS, $this->hazardous);
		if ($this->isColumnModified(VpoRequestCargoPeer::CARGO_TYPE)) $criteria->add(VpoRequestCargoPeer::CARGO_TYPE, $this->cargo_type);
		if ($this->isColumnModified(VpoRequestCargoPeer::WEIGHT)) $criteria->add(VpoRequestCargoPeer::WEIGHT, $this->weight);
		if ($this->isColumnModified(VpoRequestCargoPeer::HEIGHT)) $criteria->add(VpoRequestCargoPeer::HEIGHT, $this->height);
		if ($this->isColumnModified(VpoRequestCargoPeer::LENGTH)) $criteria->add(VpoRequestCargoPeer::LENGTH, $this->length);
		if ($this->isColumnModified(VpoRequestCargoPeer::WIDTH)) $criteria->add(VpoRequestCargoPeer::WIDTH, $this->width);
		if ($this->isColumnModified(VpoRequestCargoPeer::SPECIAL_HANDLING)) $criteria->add(VpoRequestCargoPeer::SPECIAL_HANDLING, $this->special_handling);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_FIRST_NAME)) $criteria->add(VpoRequestCargoPeer::OC_FIRST_NAME, $this->oc_first_name);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_LAST_NAME)) $criteria->add(VpoRequestCargoPeer::OC_LAST_NAME, $this->oc_last_name);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_DAY_PHONE)) $criteria->add(VpoRequestCargoPeer::OC_DAY_PHONE, $this->oc_day_phone);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_DAY_COMMENT)) $criteria->add(VpoRequestCargoPeer::OC_DAY_COMMENT, $this->oc_day_comment);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_MOBILE_PHONE)) $criteria->add(VpoRequestCargoPeer::OC_MOBILE_PHONE, $this->oc_mobile_phone);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_MOBILE_COMMENT)) $criteria->add(VpoRequestCargoPeer::OC_MOBILE_COMMENT, $this->oc_mobile_comment);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_OTHER_PHONE1)) $criteria->add(VpoRequestCargoPeer::OC_OTHER_PHONE1, $this->oc_other_phone1);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_OTHER_COMMENT1)) $criteria->add(VpoRequestCargoPeer::OC_OTHER_COMMENT1, $this->oc_other_comment1);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_OTHER_PHONE2)) $criteria->add(VpoRequestCargoPeer::OC_OTHER_PHONE2, $this->oc_other_phone2);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_OTHER_COMMENT2)) $criteria->add(VpoRequestCargoPeer::OC_OTHER_COMMENT2, $this->oc_other_comment2);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_EMAIL)) $criteria->add(VpoRequestCargoPeer::OC_EMAIL, $this->oc_email);
		if ($this->isColumnModified(VpoRequestCargoPeer::OC_ALT_EMAIL)) $criteria->add(VpoRequestCargoPeer::OC_ALT_EMAIL, $this->oc_alt_email);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_FIRST_NAME)) $criteria->add(VpoRequestCargoPeer::DC_FIRST_NAME, $this->dc_first_name);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_LAST_NAME)) $criteria->add(VpoRequestCargoPeer::DC_LAST_NAME, $this->dc_last_name);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_DAY_PHONE)) $criteria->add(VpoRequestCargoPeer::DC_DAY_PHONE, $this->dc_day_phone);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_DAY_COMMENT)) $criteria->add(VpoRequestCargoPeer::DC_DAY_COMMENT, $this->dc_day_comment);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_MOBILE_HONE)) $criteria->add(VpoRequestCargoPeer::DC_MOBILE_HONE, $this->dc_mobile_hone);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_MOBILE_COMMENT)) $criteria->add(VpoRequestCargoPeer::DC_MOBILE_COMMENT, $this->dc_mobile_comment);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_OTHER_PHONE1)) $criteria->add(VpoRequestCargoPeer::DC_OTHER_PHONE1, $this->dc_other_phone1);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_OTHER_COMMENT1)) $criteria->add(VpoRequestCargoPeer::DC_OTHER_COMMENT1, $this->dc_other_comment1);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_OTHER_PHONE2)) $criteria->add(VpoRequestCargoPeer::DC_OTHER_PHONE2, $this->dc_other_phone2);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_OTHER_COMMENT2)) $criteria->add(VpoRequestCargoPeer::DC_OTHER_COMMENT2, $this->dc_other_comment2);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_EMAIL)) $criteria->add(VpoRequestCargoPeer::DC_EMAIL, $this->dc_email);
		if ($this->isColumnModified(VpoRequestCargoPeer::DC_ALT_EMAIL)) $criteria->add(VpoRequestCargoPeer::DC_ALT_EMAIL, $this->dc_alt_email);
		if ($this->isColumnModified(VpoRequestCargoPeer::ITEM_DESCRIPTION)) $criteria->add(VpoRequestCargoPeer::ITEM_DESCRIPTION, $this->item_description);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(VpoRequestCargoPeer::DATABASE_NAME);

		$criteria->add(VpoRequestCargoPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of VpoRequestCargo (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setRequestId($this->request_id);

		$copyObj->setHazardous($this->hazardous);

		$copyObj->setCargoType($this->cargo_type);

		$copyObj->setWeight($this->weight);

		$copyObj->setHeight($this->height);

		$copyObj->setLength($this->length);

		$copyObj->setWidth($this->width);

		$copyObj->setSpecialHandling($this->special_handling);

		$copyObj->setOcFirstName($this->oc_first_name);

		$copyObj->setOcLastName($this->oc_last_name);

		$copyObj->setOcDayPhone($this->oc_day_phone);

		$copyObj->setOcDayComment($this->oc_day_comment);

		$copyObj->setOcMobilePhone($this->oc_mobile_phone);

		$copyObj->setOcMobileComment($this->oc_mobile_comment);

		$copyObj->setOcOtherPhone1($this->oc_other_phone1);

		$copyObj->setOcOtherComment1($this->oc_other_comment1);

		$copyObj->setOcOtherPhone2($this->oc_other_phone2);

		$copyObj->setOcOtherComment2($this->oc_other_comment2);

		$copyObj->setOcEmail($this->oc_email);

		$copyObj->setOcAltEmail($this->oc_alt_email);

		$copyObj->setDcFirstName($this->dc_first_name);

		$copyObj->setDcLastName($this->dc_last_name);

		$copyObj->setDcDayPhone($this->dc_day_phone);

		$copyObj->setDcDayComment($this->dc_day_comment);

		$copyObj->setDcMobileHone($this->dc_mobile_hone);

		$copyObj->setDcMobileComment($this->dc_mobile_comment);

		$copyObj->setDcOtherPhone1($this->dc_other_phone1);

		$copyObj->setDcOtherComment1($this->dc_other_comment1);

		$copyObj->setDcOtherPhone2($this->dc_other_phone2);

		$copyObj->setDcOtherComment2($this->dc_other_comment2);

		$copyObj->setDcEmail($this->dc_email);

		$copyObj->setDcAltEmail($this->dc_alt_email);

		$copyObj->setItemDescription($this->item_description);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     VpoRequestCargo Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     VpoRequestCargoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new VpoRequestCargoPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a VpoRequest object.
	 *
	 * @param      VpoRequest $v
	 * @return     VpoRequestCargo The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setVpoRequest(VpoRequest $v = null)
	{
		if ($v === null) {
			$this->setRequestId(NULL);
		} else {
			$this->setRequestId($v->getId());
		}

		$this->aVpoRequest = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the VpoRequest object, it will not be re-added.
		if ($v !== null) {
			$v->addVpoRequestCargo($this);
		}

		return $this;
	}


	/**
	 * Get the associated VpoRequest object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     VpoRequest The associated VpoRequest object.
	 * @throws     PropelException
	 */
	public function getVpoRequest(PropelPDO $con = null)
	{
		if ($this->aVpoRequest === null && ($this->request_id !== null)) {
			$c = new Criteria(VpoRequestPeer::DATABASE_NAME);
			$c->add(VpoRequestPeer::ID, $this->request_id);
			$this->aVpoRequest = VpoRequestPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aVpoRequest->addVpoRequestCargos($this);
			 */
		}
		return $this->aVpoRequest;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aVpoRequest = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseVpoRequestCargo:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseVpoRequestCargo::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseVpoRequestCargo
