<?php

/**
 * Base class that represents a row from the 'mission_backup' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue May 24 06:33:27 2011
 *
 * @package    lib.model.om
 */
abstract class BaseMissionBackup extends BaseObject  implements Persistent {


  const PEER = 'MissionBackupPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        MissionBackupPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the external_id field.
	 * @var        int
	 */
	protected $external_id;

	/**
	 * The value for the request_id field.
	 * @var        int
	 */
	protected $request_id;

	/**
	 * The value for the itinerary_id field.
	 * @var        int
	 */
	protected $itinerary_id;

	/**
	 * The value for the mission_type_id field.
	 * @var        int
	 */
	protected $mission_type_id;

	/**
	 * The value for the mission_date field.
	 * @var        string
	 */
	protected $mission_date;

	/**
	 * The value for the date_requested field.
	 * @var        string
	 */
	protected $date_requested;

	/**
	 * The value for the passenger_id field.
	 * @var        int
	 */
	protected $passenger_id;

	/**
	 * The value for the requester_id field.
	 * @var        int
	 */
	protected $requester_id;

	/**
	 * The value for the agency_id field.
	 * @var        int
	 */
	protected $agency_id;

	/**
	 * The value for the other_requester_id field.
	 * @var        int
	 */
	protected $other_requester_id;

	/**
	 * The value for the other_agency_id field.
	 * @var        int
	 */
	protected $other_agency_id;

	/**
	 * The value for the camp_id field.
	 * @var        int
	 */
	protected $camp_id;

	/**
	 * The value for the coordinator_id field.
	 * @var        int
	 */
	protected $coordinator_id;

	/**
	 * The value for the appt_date field.
	 * @var        string
	 */
	protected $appt_date;

	/**
	 * The value for the flight_time field.
	 * @var        string
	 */
	protected $flight_time;

	/**
	 * The value for the treatment field.
	 * @var        string
	 */
	protected $treatment;

	/**
	 * The value for the comment field.
	 * @var        string
	 */
	protected $comment;

	/**
	 * The value for the appointment field.
	 * @var        string
	 */
	protected $appointment;

	/**
	 * The value for the mission_specific_comments field.
	 * @var        string
	 */
	protected $mission_specific_comments;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseMissionBackup object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [external_id] column value.
	 * 
	 * @return     int
	 */
	public function getExternalId()
	{
		return $this->external_id;
	}

	/**
	 * Get the [request_id] column value.
	 * 
	 * @return     int
	 */
	public function getRequestId()
	{
		return $this->request_id;
	}

	/**
	 * Get the [itinerary_id] column value.
	 * 
	 * @return     int
	 */
	public function getItineraryId()
	{
		return $this->itinerary_id;
	}

	/**
	 * Get the [mission_type_id] column value.
	 * 
	 * @return     int
	 */
	public function getMissionTypeId()
	{
		return $this->mission_type_id;
	}

	/**
	 * Get the [optionally formatted] temporal [mission_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getMissionDate($format = 'Y-m-d H:i:s')
	{
		if ($this->mission_date === null) {
			return null;
		}


		if ($this->mission_date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->mission_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->mission_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [date_requested] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDateRequested($format = 'Y-m-d H:i:s')
	{
		if ($this->date_requested === null) {
			return null;
		}


		if ($this->date_requested === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date_requested);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date_requested, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [passenger_id] column value.
	 * 
	 * @return     int
	 */
	public function getPassengerId()
	{
		return $this->passenger_id;
	}

	/**
	 * Get the [requester_id] column value.
	 * 
	 * @return     int
	 */
	public function getRequesterId()
	{
		return $this->requester_id;
	}

	/**
	 * Get the [agency_id] column value.
	 * 
	 * @return     int
	 */
	public function getAgencyId()
	{
		return $this->agency_id;
	}

	/**
	 * Get the [other_requester_id] column value.
	 * 
	 * @return     int
	 */
	public function getOtherRequesterId()
	{
		return $this->other_requester_id;
	}

	/**
	 * Get the [other_agency_id] column value.
	 * 
	 * @return     int
	 */
	public function getOtherAgencyId()
	{
		return $this->other_agency_id;
	}

	/**
	 * Get the [camp_id] column value.
	 * 
	 * @return     int
	 */
	public function getCampId()
	{
		return $this->camp_id;
	}

	/**
	 * Get the [coordinator_id] column value.
	 * 
	 * @return     int
	 */
	public function getCoordinatorId()
	{
		return $this->coordinator_id;
	}

	/**
	 * Get the [optionally formatted] temporal [appt_date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getApptDate($format = 'Y-m-d H:i:s')
	{
		if ($this->appt_date === null) {
			return null;
		}


		if ($this->appt_date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->appt_date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->appt_date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [flight_time] column value.
	 * 
	 * @return     string
	 */
	public function getFlightTime()
	{
		return $this->flight_time;
	}

	/**
	 * Get the [treatment] column value.
	 * 
	 * @return     string
	 */
	public function getTreatment()
	{
		return $this->treatment;
	}

	/**
	 * Get the [comment] column value.
	 * 
	 * @return     string
	 */
	public function getComment()
	{
		return $this->comment;
	}

	/**
	 * Get the [appointment] column value.
	 * 
	 * @return     string
	 */
	public function getAppointment()
	{
		return $this->appointment;
	}

	/**
	 * Get the [mission_specific_comments] column value.
	 * 
	 * @return     string
	 */
	public function getMissionSpecificComments()
	{
		return $this->mission_specific_comments;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [external_id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setExternalId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->external_id !== $v) {
			$this->external_id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::EXTERNAL_ID;
		}

		return $this;
	} // setExternalId()

	/**
	 * Set the value of [request_id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setRequestId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->request_id !== $v) {
			$this->request_id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::REQUEST_ID;
		}

		return $this;
	} // setRequestId()

	/**
	 * Set the value of [itinerary_id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setItineraryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->itinerary_id !== $v) {
			$this->itinerary_id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::ITINERARY_ID;
		}

		return $this;
	} // setItineraryId()

	/**
	 * Set the value of [mission_type_id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setMissionTypeId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->mission_type_id !== $v) {
			$this->mission_type_id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::MISSION_TYPE_ID;
		}

		return $this;
	} // setMissionTypeId()

	/**
	 * Sets the value of [mission_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setMissionDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->mission_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->mission_date !== null && $tmpDt = new DateTime($this->mission_date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->mission_date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = MissionBackupPeer::MISSION_DATE;
			}
		} // if either are not null

		return $this;
	} // setMissionDate()

	/**
	 * Sets the value of [date_requested] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setDateRequested($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date_requested !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date_requested !== null && $tmpDt = new DateTime($this->date_requested)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date_requested = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = MissionBackupPeer::DATE_REQUESTED;
			}
		} // if either are not null

		return $this;
	} // setDateRequested()

	/**
	 * Set the value of [passenger_id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setPassengerId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->passenger_id !== $v) {
			$this->passenger_id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::PASSENGER_ID;
		}

		return $this;
	} // setPassengerId()

	/**
	 * Set the value of [requester_id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setRequesterId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->requester_id !== $v) {
			$this->requester_id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::REQUESTER_ID;
		}

		return $this;
	} // setRequesterId()

	/**
	 * Set the value of [agency_id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setAgencyId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->agency_id !== $v) {
			$this->agency_id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::AGENCY_ID;
		}

		return $this;
	} // setAgencyId()

	/**
	 * Set the value of [other_requester_id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setOtherRequesterId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->other_requester_id !== $v) {
			$this->other_requester_id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::OTHER_REQUESTER_ID;
		}

		return $this;
	} // setOtherRequesterId()

	/**
	 * Set the value of [other_agency_id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setOtherAgencyId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->other_agency_id !== $v) {
			$this->other_agency_id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::OTHER_AGENCY_ID;
		}

		return $this;
	} // setOtherAgencyId()

	/**
	 * Set the value of [camp_id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setCampId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->camp_id !== $v) {
			$this->camp_id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::CAMP_ID;
		}

		return $this;
	} // setCampId()

	/**
	 * Set the value of [coordinator_id] column.
	 * 
	 * @param      int $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setCoordinatorId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->coordinator_id !== $v) {
			$this->coordinator_id = $v;
			$this->modifiedColumns[] = MissionBackupPeer::COORDINATOR_ID;
		}

		return $this;
	} // setCoordinatorId()

	/**
	 * Sets the value of [appt_date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setApptDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->appt_date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->appt_date !== null && $tmpDt = new DateTime($this->appt_date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->appt_date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = MissionBackupPeer::APPT_DATE;
			}
		} // if either are not null

		return $this;
	} // setApptDate()

	/**
	 * Set the value of [flight_time] column.
	 * 
	 * @param      string $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setFlightTime($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->flight_time !== $v) {
			$this->flight_time = $v;
			$this->modifiedColumns[] = MissionBackupPeer::FLIGHT_TIME;
		}

		return $this;
	} // setFlightTime()

	/**
	 * Set the value of [treatment] column.
	 * 
	 * @param      string $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setTreatment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->treatment !== $v) {
			$this->treatment = $v;
			$this->modifiedColumns[] = MissionBackupPeer::TREATMENT;
		}

		return $this;
	} // setTreatment()

	/**
	 * Set the value of [comment] column.
	 * 
	 * @param      string $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setComment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->comment !== $v) {
			$this->comment = $v;
			$this->modifiedColumns[] = MissionBackupPeer::COMMENT;
		}

		return $this;
	} // setComment()

	/**
	 * Set the value of [appointment] column.
	 * 
	 * @param      string $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setAppointment($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->appointment !== $v) {
			$this->appointment = $v;
			$this->modifiedColumns[] = MissionBackupPeer::APPOINTMENT;
		}

		return $this;
	} // setAppointment()

	/**
	 * Set the value of [mission_specific_comments] column.
	 * 
	 * @param      string $v new value
	 * @return     MissionBackup The current object (for fluent API support)
	 */
	public function setMissionSpecificComments($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mission_specific_comments !== $v) {
			$this->mission_specific_comments = $v;
			$this->modifiedColumns[] = MissionBackupPeer::MISSION_SPECIFIC_COMMENTS;
		}

		return $this;
	} // setMissionSpecificComments()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->external_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->request_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->itinerary_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->mission_type_id = ($row[$startcol + 4] !== null) ? (int) $row[$startcol + 4] : null;
			$this->mission_date = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->date_requested = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->passenger_id = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->requester_id = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->agency_id = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->other_requester_id = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->other_agency_id = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->camp_id = ($row[$startcol + 12] !== null) ? (int) $row[$startcol + 12] : null;
			$this->coordinator_id = ($row[$startcol + 13] !== null) ? (int) $row[$startcol + 13] : null;
			$this->appt_date = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->flight_time = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->treatment = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->comment = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->appointment = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->mission_specific_comments = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 20; // 20 = MissionBackupPeer::NUM_COLUMNS - MissionBackupPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating MissionBackup object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MissionBackupPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = MissionBackupPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseMissionBackup:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MissionBackupPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			MissionBackupPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseMissionBackup:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseMissionBackup:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MissionBackupPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseMissionBackup:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			MissionBackupPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = MissionBackupPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = MissionBackupPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += MissionBackupPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = MissionBackupPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = MissionBackupPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getExternalId();
				break;
			case 2:
				return $this->getRequestId();
				break;
			case 3:
				return $this->getItineraryId();
				break;
			case 4:
				return $this->getMissionTypeId();
				break;
			case 5:
				return $this->getMissionDate();
				break;
			case 6:
				return $this->getDateRequested();
				break;
			case 7:
				return $this->getPassengerId();
				break;
			case 8:
				return $this->getRequesterId();
				break;
			case 9:
				return $this->getAgencyId();
				break;
			case 10:
				return $this->getOtherRequesterId();
				break;
			case 11:
				return $this->getOtherAgencyId();
				break;
			case 12:
				return $this->getCampId();
				break;
			case 13:
				return $this->getCoordinatorId();
				break;
			case 14:
				return $this->getApptDate();
				break;
			case 15:
				return $this->getFlightTime();
				break;
			case 16:
				return $this->getTreatment();
				break;
			case 17:
				return $this->getComment();
				break;
			case 18:
				return $this->getAppointment();
				break;
			case 19:
				return $this->getMissionSpecificComments();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = MissionBackupPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getExternalId(),
			$keys[2] => $this->getRequestId(),
			$keys[3] => $this->getItineraryId(),
			$keys[4] => $this->getMissionTypeId(),
			$keys[5] => $this->getMissionDate(),
			$keys[6] => $this->getDateRequested(),
			$keys[7] => $this->getPassengerId(),
			$keys[8] => $this->getRequesterId(),
			$keys[9] => $this->getAgencyId(),
			$keys[10] => $this->getOtherRequesterId(),
			$keys[11] => $this->getOtherAgencyId(),
			$keys[12] => $this->getCampId(),
			$keys[13] => $this->getCoordinatorId(),
			$keys[14] => $this->getApptDate(),
			$keys[15] => $this->getFlightTime(),
			$keys[16] => $this->getTreatment(),
			$keys[17] => $this->getComment(),
			$keys[18] => $this->getAppointment(),
			$keys[19] => $this->getMissionSpecificComments(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = MissionBackupPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setExternalId($value);
				break;
			case 2:
				$this->setRequestId($value);
				break;
			case 3:
				$this->setItineraryId($value);
				break;
			case 4:
				$this->setMissionTypeId($value);
				break;
			case 5:
				$this->setMissionDate($value);
				break;
			case 6:
				$this->setDateRequested($value);
				break;
			case 7:
				$this->setPassengerId($value);
				break;
			case 8:
				$this->setRequesterId($value);
				break;
			case 9:
				$this->setAgencyId($value);
				break;
			case 10:
				$this->setOtherRequesterId($value);
				break;
			case 11:
				$this->setOtherAgencyId($value);
				break;
			case 12:
				$this->setCampId($value);
				break;
			case 13:
				$this->setCoordinatorId($value);
				break;
			case 14:
				$this->setApptDate($value);
				break;
			case 15:
				$this->setFlightTime($value);
				break;
			case 16:
				$this->setTreatment($value);
				break;
			case 17:
				$this->setComment($value);
				break;
			case 18:
				$this->setAppointment($value);
				break;
			case 19:
				$this->setMissionSpecificComments($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = MissionBackupPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setExternalId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setRequestId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setItineraryId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setMissionTypeId($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setMissionDate($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDateRequested($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setPassengerId($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setRequesterId($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setAgencyId($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setOtherRequesterId($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setOtherAgencyId($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setCampId($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setCoordinatorId($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setApptDate($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setFlightTime($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setTreatment($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setComment($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setAppointment($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setMissionSpecificComments($arr[$keys[19]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(MissionBackupPeer::DATABASE_NAME);

		if ($this->isColumnModified(MissionBackupPeer::ID)) $criteria->add(MissionBackupPeer::ID, $this->id);
		if ($this->isColumnModified(MissionBackupPeer::EXTERNAL_ID)) $criteria->add(MissionBackupPeer::EXTERNAL_ID, $this->external_id);
		if ($this->isColumnModified(MissionBackupPeer::REQUEST_ID)) $criteria->add(MissionBackupPeer::REQUEST_ID, $this->request_id);
		if ($this->isColumnModified(MissionBackupPeer::ITINERARY_ID)) $criteria->add(MissionBackupPeer::ITINERARY_ID, $this->itinerary_id);
		if ($this->isColumnModified(MissionBackupPeer::MISSION_TYPE_ID)) $criteria->add(MissionBackupPeer::MISSION_TYPE_ID, $this->mission_type_id);
		if ($this->isColumnModified(MissionBackupPeer::MISSION_DATE)) $criteria->add(MissionBackupPeer::MISSION_DATE, $this->mission_date);
		if ($this->isColumnModified(MissionBackupPeer::DATE_REQUESTED)) $criteria->add(MissionBackupPeer::DATE_REQUESTED, $this->date_requested);
		if ($this->isColumnModified(MissionBackupPeer::PASSENGER_ID)) $criteria->add(MissionBackupPeer::PASSENGER_ID, $this->passenger_id);
		if ($this->isColumnModified(MissionBackupPeer::REQUESTER_ID)) $criteria->add(MissionBackupPeer::REQUESTER_ID, $this->requester_id);
		if ($this->isColumnModified(MissionBackupPeer::AGENCY_ID)) $criteria->add(MissionBackupPeer::AGENCY_ID, $this->agency_id);
		if ($this->isColumnModified(MissionBackupPeer::OTHER_REQUESTER_ID)) $criteria->add(MissionBackupPeer::OTHER_REQUESTER_ID, $this->other_requester_id);
		if ($this->isColumnModified(MissionBackupPeer::OTHER_AGENCY_ID)) $criteria->add(MissionBackupPeer::OTHER_AGENCY_ID, $this->other_agency_id);
		if ($this->isColumnModified(MissionBackupPeer::CAMP_ID)) $criteria->add(MissionBackupPeer::CAMP_ID, $this->camp_id);
		if ($this->isColumnModified(MissionBackupPeer::COORDINATOR_ID)) $criteria->add(MissionBackupPeer::COORDINATOR_ID, $this->coordinator_id);
		if ($this->isColumnModified(MissionBackupPeer::APPT_DATE)) $criteria->add(MissionBackupPeer::APPT_DATE, $this->appt_date);
		if ($this->isColumnModified(MissionBackupPeer::FLIGHT_TIME)) $criteria->add(MissionBackupPeer::FLIGHT_TIME, $this->flight_time);
		if ($this->isColumnModified(MissionBackupPeer::TREATMENT)) $criteria->add(MissionBackupPeer::TREATMENT, $this->treatment);
		if ($this->isColumnModified(MissionBackupPeer::COMMENT)) $criteria->add(MissionBackupPeer::COMMENT, $this->comment);
		if ($this->isColumnModified(MissionBackupPeer::APPOINTMENT)) $criteria->add(MissionBackupPeer::APPOINTMENT, $this->appointment);
		if ($this->isColumnModified(MissionBackupPeer::MISSION_SPECIFIC_COMMENTS)) $criteria->add(MissionBackupPeer::MISSION_SPECIFIC_COMMENTS, $this->mission_specific_comments);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(MissionBackupPeer::DATABASE_NAME);

		$criteria->add(MissionBackupPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of MissionBackup (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setExternalId($this->external_id);

		$copyObj->setRequestId($this->request_id);

		$copyObj->setItineraryId($this->itinerary_id);

		$copyObj->setMissionTypeId($this->mission_type_id);

		$copyObj->setMissionDate($this->mission_date);

		$copyObj->setDateRequested($this->date_requested);

		$copyObj->setPassengerId($this->passenger_id);

		$copyObj->setRequesterId($this->requester_id);

		$copyObj->setAgencyId($this->agency_id);

		$copyObj->setOtherRequesterId($this->other_requester_id);

		$copyObj->setOtherAgencyId($this->other_agency_id);

		$copyObj->setCampId($this->camp_id);

		$copyObj->setCoordinatorId($this->coordinator_id);

		$copyObj->setApptDate($this->appt_date);

		$copyObj->setFlightTime($this->flight_time);

		$copyObj->setTreatment($this->treatment);

		$copyObj->setComment($this->comment);

		$copyObj->setAppointment($this->appointment);

		$copyObj->setMissionSpecificComments($this->mission_specific_comments);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     MissionBackup Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     MissionBackupPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new MissionBackupPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseMissionBackup:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseMissionBackup::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseMissionBackup
