default:
  http_metas:
    content-type: text/html

  metas:
    title:        Angel Flight West
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [all.css]

  javascripts:    [jquery-1.3.2.min.js, jquery.main.js]

  has_layout:     on
  layout:         layout
