<?php

/**
 * Application form base class.
 *
 * @package    angelflight
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseApplicationForm extends BaseFormPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'id'                           => new sfWidgetFormInputHidden(),
      'ccard_number'                 => new sfWidgetFormInput(),
      'ccard_code'                   => new sfWidgetFormInput(),
      'ccard_expire'                 => new sfWidgetFormDate(),
      'member_id'                    => new sfWidgetFormPropelChoice(array('model' => 'Member', 'add_empty' => false)),
      'renewal'                      => new sfWidgetFormInput(),
      'date'                         => new sfWidgetFormDateTime(),
      'vocation_class_id'            => new sfWidgetFormPropelChoice(array('model' => 'VocationClass', 'add_empty' => true)),
      'company'                      => new sfWidgetFormInput(),
      'license_type'                 => new sfWidgetFormInput(),
      'ifr'                          => new sfWidgetFormInput(),
      'multi_engine'                 => new sfWidgetFormInput(),
      'se_instructor'                => new sfWidgetFormInput(),
      'me_instructor'                => new sfWidgetFormInput(),
      'other_ratings'                => new sfWidgetFormInput(),
      'total_hours'                  => new sfWidgetFormInput(),
      'fbo'                          => new sfWidgetFormInput(),
      'mission_orientation'          => new sfWidgetFormInput(),
      'mission_coordination'         => new sfWidgetFormInput(),
      'pilot_recruitment'            => new sfWidgetFormInput(),
      'fund_raising'                 => new sfWidgetFormInput(),
      'celebrity_contacts'           => new sfWidgetFormInput(),
      'hospital_outreach'            => new sfWidgetFormInput(),
      'member_meetings'              => new sfWidgetFormInput(),
      'media_relations'              => new sfWidgetFormInput(),
      'telephone_work'               => new sfWidgetFormInput(),
      'computers'                    => new sfWidgetFormInput(),
      'clerical'                     => new sfWidgetFormInput(),
      'publicity'                    => new sfWidgetFormInput(),
      'writing'                      => new sfWidgetFormInput(),
      'speakers_bureau'              => new sfWidgetFormInput(),
      'executive_board'              => new sfWidgetFormInput(),
      'wing_team'                    => new sfWidgetFormInput(),
      'graphic_arts'                 => new sfWidgetFormInput(),
      'other_volunteer'              => new sfWidgetFormInput(),
      't_shirt_size'                 => new sfWidgetFormInput(),
      'dues_amount_paid'             => new sfWidgetFormInput(),
      'method_of_payment'            => new sfWidgetFormInput(),
      'check_number'                 => new sfWidgetFormInput(),
      'donation_amount_paid'         => new sfWidgetFormInput(),
      'title'                        => new sfWidgetFormInput(),
      'first_name'                   => new sfWidgetFormInput(),
      'last_name'                    => new sfWidgetFormInput(),
      'address1'                     => new sfWidgetFormInput(),
      'address2'                     => new sfWidgetFormInput(),
      'city'                         => new sfWidgetFormInput(),
      'state'                        => new sfWidgetFormInput(),
      'zipcode'                      => new sfWidgetFormInput(),
      'day_phone'                    => new sfWidgetFormInput(),
      'day_comment'                  => new sfWidgetFormInput(),
      'eve_phone'                    => new sfWidgetFormInput(),
      'eve_comment'                  => new sfWidgetFormInput(),
      'mobile_phone'                 => new sfWidgetFormInput(),
      'mobile_comment'               => new sfWidgetFormInput(),
      'pager_phone'                  => new sfWidgetFormInput(),
      'pager_comment'                => new sfWidgetFormInput(),
      'fax_phone1'                   => new sfWidgetFormInput(),
      'fax_comment1'                 => new sfWidgetFormInput(),
      'fax_phone2'                   => new sfWidgetFormInput(),
      'fax_comment2'                 => new sfWidgetFormInput(),
      'other_phone'                  => new sfWidgetFormInput(),
      'other_comment'                => new sfWidgetFormInput(),
      'email'                        => new sfWidgetFormInput(),
      'spouse_first_name'            => new sfWidgetFormInput(),
      'spouse_last_name'             => new sfWidgetFormInput(),
      'applicant_pilot'              => new sfWidgetFormInput(),
      'languages_spoken'             => new sfWidgetFormInput(),
      'home_base'                    => new sfWidgetFormInput(),
      'secondary_home_bases'         => new sfWidgetFormInput(),
      'aircraft_primary_id'          => new sfWidgetFormInput(),
      'aircraft_primary_own'         => new sfWidgetFormInput(),
      'aircraft_primary_ice'         => new sfWidgetFormInput(),
      'aircraft_primary_seats'       => new sfWidgetFormInput(),
      'aircraft_primary_n_number'    => new sfWidgetFormInput(),
      'aircraft_secondary_id'        => new sfWidgetFormInput(),
      'aircraft_secondary_own'       => new sfWidgetFormInput(),
      'aircraft_secondary_ice'       => new sfWidgetFormInput(),
      'aircraft_secondary_seats'     => new sfWidgetFormInput(),
      'aircraft_secondary_n_number'  => new sfWidgetFormInput(),
      'pilot_certificate'            => new sfWidgetFormInput(),
      'medical_class'                => new sfWidgetFormInput(),
      'ifr_hours'                    => new sfWidgetFormInput(),
      'multi_hours'                  => new sfWidgetFormInput(),
      'other_hours'                  => new sfWidgetFormInput(),
      'date_of_birth'                => new sfWidgetFormDate(),
      'height'                       => new sfWidgetFormInput(),
      'weight'                       => new sfWidgetFormInput(),
      'availability_weekdays'        => new sfWidgetFormInput(),
      'availability_weeknights'      => new sfWidgetFormInput(),
      'availability_weekends'        => new sfWidgetFormInput(),
      'availability_notice'          => new sfWidgetFormInput(),
      'availability_last_minute'     => new sfWidgetFormInput(),
      'availability_copilot'         => new sfWidgetFormInput(),
      'affirmation_agreed'           => new sfWidgetFormInput(),
      'insurance_agreed'             => new sfWidgetFormInput(),
      'volunteer_interest'           => new sfWidgetFormInput(),
      'company_position'             => new sfWidgetFormInput(),
      'company_match_funds'          => new sfWidgetFormInput(),
      'company_business_category_id' => new sfWidgetFormInput(),
      'referral_source'              => new sfWidgetFormPropelChoice(array('model' => 'RefSource', 'add_empty' => true)),
      'premium_choice'               => new sfWidgetFormInput(),
      'premium_size'                 => new sfWidgetFormInput(),
      'ccard_approval_number'        => new sfWidgetFormInput(),
      'ccard_error_code'             => new sfWidgetFormInput(),
      'ccard_avs_result'             => new sfWidgetFormInput(),
      'processed_date'               => new sfWidgetFormDateTime(),
      'event_planning'               => new sfWidgetFormInput(),
      'web_internet'                 => new sfWidgetFormInput(),
      'foundation_contacts'          => new sfWidgetFormInput(),
      'aviation_contacts'            => new sfWidgetFormInput(),
      'printing'                     => new sfWidgetFormInput(),
      'member_aopa'                  => new sfWidgetFormInput(),
      'member_kiwanis'               => new sfWidgetFormInput(),
      'member_rotary'                => new sfWidgetFormInput(),
      'member_lions'                 => new sfWidgetFormInput(),
      'novapointe_id'                => new sfWidgetFormInput(),
      'premium_ship_date'            => new sfWidgetFormDateTime(),
      'premium_ship_method'          => new sfWidgetFormInput(),
      'premium_ship_cost'            => new sfWidgetFormInput(),
      'premium_ship_tracking_number' => new sfWidgetFormInput(),
      'spouse_pilot'                 => new sfWidgetFormInput(),
      'applicant_copilot'            => new sfWidgetFormInput(),
      'pager_email'                  => new sfWidgetFormInput(),
      'member_99s'                   => new sfWidgetFormInput(),
      'member_wia'                   => new sfWidgetFormInput(),
      'mission_email_optin'          => new sfWidgetFormInput(),
      'hseats_interest'              => new sfWidgetFormInput(),
      'master_application_id'        => new sfWidgetFormInput(),
      'master_member_id'             => new sfWidgetFormInput(),
      'referral_source_other'        => new sfWidgetFormInput(),
      'secondary_email'              => new sfWidgetFormInput(),
      'payment_transaction_id'       => new sfWidgetFormInput(),
      'aircraft_third_ice'           => new sfWidgetFormInput(),
      'aircraft_third_id'            => new sfWidgetFormInput(),
      'aircraft_third_n_number'      => new sfWidgetFormInput(),
      'aircraft_third_own'           => new sfWidgetFormInput(),
      'aircraft_third_seats'         => new sfWidgetFormInput(),
      'drivers_license_number'       => new sfWidgetFormInput(),
      'drivers_license_state'        => new sfWidgetFormInput(),
      'emergency_contact_name'       => new sfWidgetFormInput(),
      'emergency_contact_phone'      => new sfWidgetFormInput(),
      'country'                      => new sfWidgetFormInput(),
      'middle_name'                  => new sfWidgetFormInput(),
      'suffix'                       => new sfWidgetFormInput(),
      'nickname'                     => new sfWidgetFormInput(),
      'veteran'                      => new sfWidgetFormInput(),
      'gender'                       => new sfWidgetFormInput(),
    ));

    $this->setValidators(array(
      'id'                           => new sfValidatorPropelChoice(array('model' => 'Application', 'column' => 'id', 'required' => false)),
      'ccard_number'                 => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'ccard_code'                   => new sfValidatorString(array('max_length' => 5, 'required' => false)),
      'ccard_expire'                 => new sfValidatorDate(array('required' => false)),
      'member_id'                    => new sfValidatorPropelChoice(array('model' => 'Member', 'column' => 'id')),
      'renewal'                      => new sfValidatorInteger(array('required' => false)),
      'date'                         => new sfValidatorDateTime(),
      'vocation_class_id'            => new sfValidatorPropelChoice(array('model' => 'VocationClass', 'column' => 'id', 'required' => false)),
      'company'                      => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'license_type'                 => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'ifr'                          => new sfValidatorInteger(array('required' => false)),
      'multi_engine'                 => new sfValidatorInteger(array('required' => false)),
      'se_instructor'                => new sfValidatorString(array('max_length' => 5, 'required' => false)),
      'me_instructor'                => new sfValidatorString(array('max_length' => 5, 'required' => false)),
      'other_ratings'                => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'total_hours'                  => new sfValidatorInteger(array('required' => false)),
      'fbo'                          => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'mission_orientation'          => new sfValidatorInteger(array('required' => false)),
      'mission_coordination'         => new sfValidatorInteger(array('required' => false)),
      'pilot_recruitment'            => new sfValidatorInteger(array('required' => false)),
      'fund_raising'                 => new sfValidatorInteger(array('required' => false)),
      'celebrity_contacts'           => new sfValidatorInteger(array('required' => false)),
      'hospital_outreach'            => new sfValidatorInteger(array('required' => false)),
      'member_meetings'              => new sfValidatorInteger(array('required' => false)),
      'media_relations'              => new sfValidatorInteger(array('required' => false)),
      'telephone_work'               => new sfValidatorInteger(array('required' => false)),
      'computers'                    => new sfValidatorInteger(array('required' => false)),
      'clerical'                     => new sfValidatorInteger(array('required' => false)),
      'publicity'                    => new sfValidatorInteger(array('required' => false)),
      'writing'                      => new sfValidatorInteger(array('required' => false)),
      'speakers_bureau'              => new sfValidatorInteger(array('required' => false)),
      'executive_board'              => new sfValidatorInteger(array('required' => false)),
      'wing_team'                    => new sfValidatorInteger(array('required' => false)),
      'graphic_arts'                 => new sfValidatorInteger(array('required' => false)),
      'other_volunteer'              => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      't_shirt_size'                 => new sfValidatorString(array('max_length' => 5, 'required' => false)),
      'dues_amount_paid'             => new sfValidatorNumber(),
      'method_of_payment'            => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'check_number'                 => new sfValidatorInteger(array('required' => false)),
      'donation_amount_paid'         => new sfValidatorNumber(array('required' => false)),
      'title'                        => new sfValidatorString(array('max_length' => 12, 'required' => false)),
      'first_name'                   => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'last_name'                    => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'address1'                     => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'address2'                     => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'city'                         => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'state'                        => new sfValidatorString(array('max_length' => 2, 'required' => false)),
      'zipcode'                      => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'day_phone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'day_comment'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'eve_phone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'eve_comment'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'mobile_phone'                 => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'mobile_comment'               => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'pager_phone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pager_comment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'fax_phone1'                   => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'fax_comment1'                 => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'fax_phone2'                   => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'fax_comment2'                 => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'other_phone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'other_comment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'email'                        => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'spouse_first_name'            => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'spouse_last_name'             => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'applicant_pilot'              => new sfValidatorInteger(array('required' => false)),
      'languages_spoken'             => new sfValidatorString(array('max_length' => 125, 'required' => false)),
      'home_base'                    => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'secondary_home_bases'         => new sfValidatorString(array('max_length' => 30)),
      'aircraft_primary_id'          => new sfValidatorInteger(array('required' => false)),
      'aircraft_primary_own'         => new sfValidatorInteger(array('required' => false)),
      'aircraft_primary_ice'         => new sfValidatorInteger(array('required' => false)),
      'aircraft_primary_seats'       => new sfValidatorInteger(array('required' => false)),
      'aircraft_primary_n_number'    => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'aircraft_secondary_id'        => new sfValidatorInteger(array('required' => false)),
      'aircraft_secondary_own'       => new sfValidatorInteger(array('required' => false)),
      'aircraft_secondary_ice'       => new sfValidatorInteger(array('required' => false)),
      'aircraft_secondary_seats'     => new sfValidatorInteger(array('required' => false)),
      'aircraft_secondary_n_number'  => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'pilot_certificate'            => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'medical_class'                => new sfValidatorInteger(array('required' => false)),
      'ifr_hours'                    => new sfValidatorInteger(array('required' => false)),
      'multi_hours'                  => new sfValidatorInteger(array('required' => false)),
      'other_hours'                  => new sfValidatorInteger(array('required' => false)),
      'date_of_birth'                => new sfValidatorDate(array('required' => false)),
      'height'                       => new sfValidatorInteger(array('required' => false)),
      'weight'                       => new sfValidatorInteger(array('required' => false)),
      'availability_weekdays'        => new sfValidatorInteger(array('required' => false)),
      'availability_weeknights'      => new sfValidatorInteger(array('required' => false)),
      'availability_weekends'        => new sfValidatorInteger(array('required' => false)),
      'availability_notice'          => new sfValidatorInteger(array('required' => false)),
      'availability_last_minute'     => new sfValidatorInteger(array('required' => false)),
      'availability_copilot'         => new sfValidatorInteger(array('required' => false)),
      'affirmation_agreed'           => new sfValidatorInteger(array('required' => false)),
      'insurance_agreed'             => new sfValidatorInteger(array('required' => false)),
      'volunteer_interest'           => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'company_position'             => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'company_match_funds'          => new sfValidatorInteger(array('required' => false)),
      'company_business_category_id' => new sfValidatorInteger(array('required' => false)),
      'referral_source'              => new sfValidatorPropelChoice(array('model' => 'RefSource', 'column' => 'id', 'required' => false)),
      'premium_choice'               => new sfValidatorInteger(array('required' => false)),
      'premium_size'                 => new sfValidatorInteger(array('required' => false)),
      'ccard_approval_number'        => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'ccard_error_code'             => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'ccard_avs_result'             => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'processed_date'               => new sfValidatorDateTime(array('required' => false)),
      'event_planning'               => new sfValidatorInteger(array('required' => false)),
      'web_internet'                 => new sfValidatorInteger(array('required' => false)),
      'foundation_contacts'          => new sfValidatorInteger(array('required' => false)),
      'aviation_contacts'            => new sfValidatorInteger(array('required' => false)),
      'printing'                     => new sfValidatorInteger(array('required' => false)),
      'member_aopa'                  => new sfValidatorInteger(array('required' => false)),
      'member_kiwanis'               => new sfValidatorInteger(array('required' => false)),
      'member_rotary'                => new sfValidatorInteger(array('required' => false)),
      'member_lions'                 => new sfValidatorInteger(array('required' => false)),
      'novapointe_id'                => new sfValidatorInteger(array('required' => false)),
      'premium_ship_date'            => new sfValidatorDateTime(array('required' => false)),
      'premium_ship_method'          => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'premium_ship_cost'            => new sfValidatorInteger(array('required' => false)),
      'premium_ship_tracking_number' => new sfValidatorString(array('max_length' => 35, 'required' => false)),
      'spouse_pilot'                 => new sfValidatorInteger(array('required' => false)),
      'applicant_copilot'            => new sfValidatorInteger(array('required' => false)),
      'pager_email'                  => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'member_99s'                   => new sfValidatorInteger(array('required' => false)),
      'member_wia'                   => new sfValidatorInteger(array('required' => false)),
      'mission_email_optin'          => new sfValidatorInteger(array('required' => false)),
      'hseats_interest'              => new sfValidatorInteger(array('required' => false)),
      'master_application_id'        => new sfValidatorInteger(array('required' => false)),
      'master_member_id'             => new sfValidatorInteger(array('required' => false)),
      'referral_source_other'        => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'secondary_email'              => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'payment_transaction_id'       => new sfValidatorInteger(array('required' => false)),
      'aircraft_third_ice'           => new sfValidatorInteger(array('required' => false)),
      'aircraft_third_id'            => new sfValidatorInteger(array('required' => false)),
      'aircraft_third_n_number'      => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'aircraft_third_own'           => new sfValidatorInteger(array('required' => false)),
      'aircraft_third_seats'         => new sfValidatorInteger(array('required' => false)),
      'drivers_license_number'       => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'drivers_license_state'        => new sfValidatorString(array('max_length' => 2, 'required' => false)),
      'emergency_contact_name'       => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'emergency_contact_phone'      => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'country'                      => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'middle_name'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'suffix'                       => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'nickname'                     => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'veteran'                      => new sfValidatorInteger(array('required' => false)),
      'gender'                       => new sfValidatorString(array('max_length' => 7, 'required' => false)),
    ));

    $this->widgetSchema->setNameFormat('application[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Application';
  }


}
