<?php

/**
 * RpMissionItinerary form base class.
 *
 * @package    angelflight
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseRpMissionItineraryForm extends BaseFormPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'Now'                              => new sfWidgetFormInput(),
      'missionID'                        => new sfWidgetFormInput(),
      'externalID'                       => new sfWidgetFormInput(),
      'missionTypeID'                    => new sfWidgetFormInput(),
      'missionDate'                      => new sfWidgetFormInput(),
      'apptDate'                         => new sfWidgetFormDateTime(),
      'flightTime'                       => new sfWidgetFormInput(),
      'releasingPhysician'               => new sfWidgetFormInput(),
      'releasingPhone'                   => new sfWidgetFormInput(),
      'releasingFax'                     => new sfWidgetFormInput(),
      'releasingFaxComment'              => new sfWidgetFormInput(),
      'releasingEmail'                   => new sfWidgetFormInput(),
      'lodging'                          => new sfWidgetFormInput(),
      'lodgingPhone'                     => new sfWidgetFormInput(),
      'lodging_phone_comment'            => new sfWidgetFormInput(),
      'facilityName'                     => new sfWidgetFormInput(),
      'facilityPhone'                    => new sfWidgetFormInput(),
      'facilityPhoneComment'             => new sfWidgetFormInput(),
      'publicConsiderations'             => new sfWidgetFormInput(),
      'privateConsiderations'            => new sfWidgetFormInput(),
      'illness'                          => new sfWidgetFormInput(),
      'groundTransportationComment'      => new sfWidgetFormInput(),
      'treatingPhysician'                => new sfWidgetFormInput(),
      'treatingPhone'                    => new sfWidgetFormInput(),
      'treatingFax'                      => new sfWidgetFormInput(),
      'treatingFaxComment'               => new sfWidgetFormInput(),
      'treatingEmail'                    => new sfWidgetFormInput(),
      'languageSpoken'                   => new sfWidgetFormInput(),
      'bestContactMethod'                => new sfWidgetFormInput(),
      'emergencyContactName'             => new sfWidgetFormInput(),
      'emergencyContactPrimaryPhone'     => new sfWidgetFormInput(),
      'emergencyContactSecondaryPhone'   => new sfWidgetFormInput(),
      'emergencyContactPrimaryComment'   => new sfWidgetFormInput(),
      'emergencyContactSecondaryComment' => new sfWidgetFormInput(),
      'passFirstName'                    => new sfWidgetFormInput(),
      'passLastName'                     => new sfWidgetFormInput(),
      'passCity'                         => new sfWidgetFormInput(),
      'passState'                        => new sfWidgetFormInput(),
      'passZipcode'                      => new sfWidgetFormInput(),
      'passAge'                          => new sfWidgetFormInput(),
      'passWeight'                       => new sfWidgetFormInput(),
      'passDayPhone'                     => new sfWidgetFormInput(),
      'passDayComment'                   => new sfWidgetFormInput(),
      'passEvePhone'                     => new sfWidgetFormInput(),
      'passEveComment'                   => new sfWidgetFormInput(),
      'passPagerPhone'                   => new sfWidgetFormInput(),
      'passPagerComment'                 => new sfWidgetFormInput(),
      'passMobilePhone'                  => new sfWidgetFormInput(),
      'passMobileComment'                => new sfWidgetFormInput(),
      'passOtherPhone'                   => new sfWidgetFormInput(),
      'passOtherComment'                 => new sfWidgetFormInput(),
      'passFaxPhone1'                    => new sfWidgetFormInput(),
      'passFax1Comment'                  => new sfWidgetFormInput(),
      'passEmail'                        => new sfWidgetFormInput(),
      'passAddressOne'                   => new sfWidgetFormInput(),
      'passAddressTwo'                   => new sfWidgetFormInput(),
      'comment'                          => new sfWidgetFormInput(),
      'id'                               => new sfWidgetFormInputHidden(),
      'legNumber'                        => new sfWidgetFormInput(),
      'passOnBoard'                      => new sfWidgetFormInput(),
      'baggageWeight'                    => new sfWidgetFormInput(),
      'baggageDesc'                      => new sfWidgetFormInput(),
      'publicCNote'                      => new sfWidgetFormInput(),
      'privateCNote'                     => new sfWidgetFormInput(),
      'copilotWanted'                    => new sfWidgetFormInput(),
      'fromAirportIdent'                 => new sfWidgetFormInput(),
      'fromAirportName'                  => new sfWidgetFormInput(),
      'fromAirportCity'                  => new sfWidgetFormInput(),
      'fromAirportState'                 => new sfWidgetFormInput(),
      'fromAirportGMTOffset'             => new sfWidgetFormInput(),
      'fromAirportDSTOffset'             => new sfWidgetFormInput(),
      'toAirportIdent'                   => new sfWidgetFormInput(),
      'toAirportName'                    => new sfWidgetFormInput(),
      'toAirportCity'                    => new sfWidgetFormInput(),
      'toAirportState'                   => new sfWidgetFormInput(),
      'toAirportGMTOffset'               => new sfWidgetFormInput(),
      'toAirportDSTOffset'               => new sfWidgetFormInput(),
      'pilotFirstName'                   => new sfWidgetFormInput(),
      'pilotLastName'                    => new sfWidgetFormInput(),
      'pilotDayPhone'                    => new sfWidgetFormInput(),
      'pilotDayComment'                  => new sfWidgetFormInput(),
      'pilotEvePhone'                    => new sfWidgetFormInput(),
      'pilotEveComment'                  => new sfWidgetFormInput(),
      'pilotFaxPhone'                    => new sfWidgetFormInput(),
      'pilotFaxComment'                  => new sfWidgetFormInput(),
      'pilotMobilePhone'                 => new sfWidgetFormInput(),
      'pilotMobileComment'               => new sfWidgetFormInput(),
      'pilotPagerPhone'                  => new sfWidgetFormInput(),
      'pilotPagerComment'                => new sfWidgetFormInput(),
      'pilotOtherPhone'                  => new sfWidgetFormInput(),
      'pilotOtherComment'                => new sfWidgetFormInput(),
      'pilotEmail'                       => new sfWidgetFormInput(),
      'coPilotFirstName'                 => new sfWidgetFormInput(),
      'coPilotLastName'                  => new sfWidgetFormInput(),
      'CoPilotDayPhone'                  => new sfWidgetFormInput(),
      'coPilotDayComment'                => new sfWidgetFormInput(),
      'CoPilotEvePhone'                  => new sfWidgetFormInput(),
      'coPilotEveComment'                => new sfWidgetFormInput(),
      'CoPilotMobilePhone'               => new sfWidgetFormInput(),
      'coPilotMobileComment'             => new sfWidgetFormInput(),
      'CoPilotPagerPhone'                => new sfWidgetFormInput(),
      'coPilotPagerComment'              => new sfWidgetFormInput(),
      'CoPilotOtherPhone'                => new sfWidgetFormInput(),
      'coPilotOtherComment'              => new sfWidgetFormInput(),
      'CoPilotFaxPhone'                  => new sfWidgetFormInput(),
      'coPilotFaxComment'                => new sfWidgetFormInput(),
      'coPilotEmail'                     => new sfWidgetFormInput(),
      'buPilotFirstName'                 => new sfWidgetFormInput(),
      'buPilotLastName'                  => new sfWidgetFormInput(),
      'buPilotDayPhone'                  => new sfWidgetFormInput(),
      'buPilotDayComment'                => new sfWidgetFormInput(),
      'buPilotEvePhone'                  => new sfWidgetFormInput(),
      'buPilotEveComment'                => new sfWidgetFormInput(),
      'buPilotMobilePhone'               => new sfWidgetFormInput(),
      'buPilotMobileComment'             => new sfWidgetFormInput(),
      'buPilotPagerPhone'                => new sfWidgetFormInput(),
      'buPilotPagerComment'              => new sfWidgetFormInput(),
      'buPilotOtherPhone'                => new sfWidgetFormInput(),
      'buPilotOtherComment'              => new sfWidgetFormInput(),
      'buPilotFaxPhone'                  => new sfWidgetFormInput(),
      'buPilotFaxComment'                => new sfWidgetFormInput(),
      'buPilotEmail'                     => new sfWidgetFormInput(),
      'coordFirstName'                   => new sfWidgetFormInput(),
      'coordLastName'                    => new sfWidgetFormInput(),
      'coordDayPhone'                    => new sfWidgetFormInput(),
      'coordDayComment'                  => new sfWidgetFormInput(),
      'coordEvePhone'                    => new sfWidgetFormInput(),
      'coordEveComment'                  => new sfWidgetFormInput(),
      'coordMobilePhone'                 => new sfWidgetFormInput(),
      'coordMobileComment'               => new sfWidgetFormInput(),
      'coordPagerPhone'                  => new sfWidgetFormInput(),
      'coordPagerComment'                => new sfWidgetFormInput(),
      'coordOtherPhone'                  => new sfWidgetFormInput(),
      'coordOtherComment'                => new sfWidgetFormInput(),
      'coordFaxPhone'                    => new sfWidgetFormInput(),
      'coordFaxComment'                  => new sfWidgetFormInput(),
      'coordEmail'                       => new sfWidgetFormInput(),
      'requesterName'                    => new sfWidgetFormInput(),
      'reqFirstName'                     => new sfWidgetFormInput(),
      'reqLastName'                      => new sfWidgetFormInput(),
      'reqDayPhone'                      => new sfWidgetFormInput(),
      'reqEvePhone'                      => new sfWidgetFormInput(),
      'reqMobilePhone'                   => new sfWidgetFormInput(),
      'reqPagerPhone'                    => new sfWidgetFormInput(),
      'reqOtherPhone'                    => new sfWidgetFormInput(),
      'reqFaxPhone'                      => new sfWidgetFormInput(),
      'reqDayComment'                    => new sfWidgetFormInput(),
      'reqEveComment'                    => new sfWidgetFormInput(),
      'reqPagerComment'                  => new sfWidgetFormInput(),
      'reqMobileComment'                 => new sfWidgetFormInput(),
      'reqFaxComment'                    => new sfWidgetFormInput(),
      'reqOtherComment'                  => new sfWidgetFormInput(),
      'reqEmail'                         => new sfWidgetFormInput(),
      'companionName'                    => new sfWidgetFormInput(),
      'companionRelationship'            => new sfWidgetFormInput(),
      'companionDOB'                     => new sfWidgetFormInput(),
      'companionAge'                     => new sfWidgetFormInput(),
      'companionWeight'                  => new sfWidgetFormInput(),
      'companionPhone'                   => new sfWidgetFormInput(),
      'companionPhoneComment'            => new sfWidgetFormInput(),
      'pilotName'                        => new sfWidgetFormInput(),
      'afaDayPhone'                      => new sfWidgetFormInput(),
      'afaNightPhone'                    => new sfWidgetFormInput(),
      'afaFaxPhone'                      => new sfWidgetFormInput(),
      'afaPilotMobilePhone'              => new sfWidgetFormInput(),
      'afaAircraft'                      => new sfWidgetFormInput(),
      'afaNNumber'                       => new sfWidgetFormInput(),
      'aircraftColor'                    => new sfWidgetFormInput(),
      'etd'                              => new sfWidgetFormInput(),
      'eta'                              => new sfWidgetFormInput(),
      'afaOrgName'                       => new sfWidgetFormInput(),
      'afaOrgPhone'                      => new sfWidgetFormInput(),
      'fboName'                          => new sfWidgetFormInput(),
      'fboPhone'                         => new sfWidgetFormInput(),
      'fboFax'                           => new sfWidgetFormInput(),
      'fboFuelDiscount'                  => new sfWidgetFormInput(),
      'fboAirportIdent'                  => new sfWidgetFormInput(),
      'aircraftSeats'                    => new sfWidgetFormInput(),
      'aircraftNNumber'                  => new sfWidgetFormInput(),
      'aircraftKnownIce'                 => new sfWidgetFormInput(),
      'aircraftMake'                     => new sfWidgetFormInput(),
      'aircraftModel'                    => new sfWidgetFormInput(),
      'campName'                         => new sfWidgetFormInput(),
      'campPhone'                        => new sfWidgetFormInput(),
      'campPhoneComment'                 => new sfWidgetFormInput(),
      'campLodgingName'                  => new sfWidgetFormInput(),
      'campLodgingPhone'                 => new sfWidgetFormInput(),
      'campLodgingPhoneComment'          => new sfWidgetFormInput(),
      'campComment'                      => new sfWidgetFormInput(),
      'flightInformation'                => new sfWidgetFormInput(),
    ));

    $this->setValidators(array(
      'Now'                              => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'missionID'                        => new sfValidatorInteger(),
      'externalID'                       => new sfValidatorInteger(array('required' => false)),
      'missionTypeID'                    => new sfValidatorInteger(),
      'missionDate'                      => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'apptDate'                         => new sfValidatorDateTime(array('required' => false)),
      'flightTime'                       => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'releasingPhysician'               => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'releasingPhone'                   => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'releasingFax'                     => new sfValidatorInteger(array('required' => false)),
      'releasingFaxComment'              => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'releasingEmail'                   => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'lodging'                          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'lodgingPhone'                     => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'lodging_phone_comment'            => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'facilityName'                     => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'facilityPhone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'facilityPhoneComment'             => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'publicConsiderations'             => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'privateConsiderations'            => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'illness'                          => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'groundTransportationComment'      => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'treatingPhysician'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'treatingPhone'                    => new sfValidatorInteger(array('required' => false)),
      'treatingFax'                      => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'treatingFaxComment'               => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'treatingEmail'                    => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'languageSpoken'                   => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'bestContactMethod'                => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'emergencyContactName'             => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'emergencyContactPrimaryPhone'     => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'emergencyContactSecondaryPhone'   => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'emergencyContactPrimaryComment'   => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'emergencyContactSecondaryComment' => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'passFirstName'                    => new sfValidatorString(array('max_length' => 40)),
      'passLastName'                     => new sfValidatorString(array('max_length' => 40)),
      'passCity'                         => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'passState'                        => new sfValidatorString(array('max_length' => 2, 'required' => false)),
      'passZipcode'                      => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'passAge'                          => new sfValidatorInteger(array('required' => false)),
      'passWeight'                       => new sfValidatorInteger(array('required' => false)),
      'passDayPhone'                     => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'passDayComment'                   => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'passEvePhone'                     => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'passEveComment'                   => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'passPagerPhone'                   => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'passPagerComment'                 => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'passMobilePhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'passMobileComment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'passOtherPhone'                   => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'passOtherComment'                 => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'passFaxPhone1'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'passFax1Comment'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'passEmail'                        => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'passAddressOne'                   => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'passAddressTwo'                   => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'comment'                          => new sfValidatorString(array('max_length' => 100, 'required' => false)),
      'id'                               => new sfValidatorPropelChoice(array('model' => 'RpMissionItinerary', 'column' => 'id', 'required' => false)),
      'legNumber'                        => new sfValidatorInteger(),
      'passOnBoard'                      => new sfValidatorInteger(),
      'baggageWeight'                    => new sfValidatorInteger(array('required' => false)),
      'baggageDesc'                      => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'publicCNote'                      => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'privateCNote'                     => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'copilotWanted'                    => new sfValidatorInteger(array('required' => false)),
      'fromAirportIdent'                 => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'fromAirportName'                  => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'fromAirportCity'                  => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'fromAirportState'                 => new sfValidatorString(array('max_length' => 2, 'required' => false)),
      'fromAirportGMTOffset'             => new sfValidatorInteger(array('required' => false)),
      'fromAirportDSTOffset'             => new sfValidatorInteger(array('required' => false)),
      'toAirportIdent'                   => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'toAirportName'                    => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'toAirportCity'                    => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'toAirportState'                   => new sfValidatorString(array('max_length' => 2, 'required' => false)),
      'toAirportGMTOffset'               => new sfValidatorInteger(array('required' => false)),
      'toAirportDSTOffset'               => new sfValidatorInteger(array('required' => false)),
      'pilotFirstName'                   => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'pilotLastName'                    => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'pilotDayPhone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotDayComment'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'pilotEvePhone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotEveComment'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'pilotFaxPhone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotFaxComment'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'pilotMobilePhone'                 => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotMobileComment'               => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'pilotPagerPhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotPagerComment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'pilotOtherPhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotOtherComment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'pilotEmail'                       => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'coPilotFirstName'                 => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'coPilotLastName'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'CoPilotDayPhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coPilotDayComment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'CoPilotEvePhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coPilotEveComment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'CoPilotMobilePhone'               => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coPilotMobileComment'             => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'CoPilotPagerPhone'                => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coPilotPagerComment'              => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'CoPilotOtherPhone'                => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coPilotOtherComment'              => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'CoPilotFaxPhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coPilotFaxComment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'coPilotEmail'                     => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'buPilotFirstName'                 => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'buPilotLastName'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'buPilotDayPhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'buPilotDayComment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'buPilotEvePhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'buPilotEveComment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'buPilotMobilePhone'               => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'buPilotMobileComment'             => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'buPilotPagerPhone'                => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'buPilotPagerComment'              => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'buPilotOtherPhone'                => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'buPilotOtherComment'              => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'buPilotFaxPhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'buPilotFaxComment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'buPilotEmail'                     => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'coordFirstName'                   => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'coordLastName'                    => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'coordDayPhone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coordDayComment'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'coordEvePhone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coordEveComment'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'coordMobilePhone'                 => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coordMobileComment'               => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'coordPagerPhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coordPagerComment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'coordOtherPhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coordOtherComment'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'coordFaxPhone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'coordFaxComment'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'coordEmail'                       => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'requesterName'                    => new sfValidatorString(array('max_length' => 81)),
      'reqFirstName'                     => new sfValidatorString(array('max_length' => 40)),
      'reqLastName'                      => new sfValidatorString(array('max_length' => 40)),
      'reqDayPhone'                      => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'reqEvePhone'                      => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'reqMobilePhone'                   => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'reqPagerPhone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'reqOtherPhone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'reqFaxPhone'                      => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'reqDayComment'                    => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'reqEveComment'                    => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'reqPagerComment'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'reqMobileComment'                 => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'reqFaxComment'                    => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'reqOtherComment'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'reqEmail'                         => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'companionName'                    => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'companionRelationship'            => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'companionDOB'                     => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'companionAge'                     => new sfValidatorInteger(array('required' => false)),
      'companionWeight'                  => new sfValidatorInteger(array('required' => false)),
      'companionPhone'                   => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'companionPhoneComment'            => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'pilotName'                        => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'afaDayPhone'                      => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'afaNightPhone'                    => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'afaFaxPhone'                      => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'afaPilotMobilePhone'              => new sfValidatorInteger(array('required' => false)),
      'afaAircraft'                      => new sfValidatorString(array('max_length' => 76, 'required' => false)),
      'afaNNumber'                       => new sfValidatorString(array('max_length' => 8, 'required' => false)),
      'aircraftColor'                    => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'etd'                              => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'eta'                              => new sfValidatorString(array('max_length' => 15, 'required' => false)),
      'afaOrgName'                       => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'afaOrgPhone'                      => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'fboName'                          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'fboPhone'                         => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'fboFax'                           => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'fboFuelDiscount'                  => new sfValidatorNumber(array('required' => false)),
      'fboAirportIdent'                  => new sfValidatorString(array('max_length' => 4, 'required' => false)),
      'aircraftSeats'                    => new sfValidatorInteger(array('required' => false)),
      'aircraftNNumber'                  => new sfValidatorString(array('max_length' => 8, 'required' => false)),
      'aircraftKnownIce'                 => new sfValidatorInteger(array('required' => false)),
      'aircraftMake'                     => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'aircraftModel'                    => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'campName'                         => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'campPhone'                        => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'campPhoneComment'                 => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'campLodgingName'                  => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'campLodgingPhone'                 => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'campLodgingPhoneComment'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'campComment'                      => new sfValidatorString(array('max_length' => 500, 'required' => false)),
      'flightInformation'                => new sfValidatorString(array('max_length' => 255, 'required' => false)),
    ));

    $this->widgetSchema->setNameFormat('rp_mission_itinerary[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'RpMissionItinerary';
  }


}
