<?php

/**
 * RpMemberApplication form base class.
 *
 * @package    angelflight
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseRpMemberApplicationForm extends BaseFormPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'applicationID'             => new sfWidgetFormInput(),
      'applicationDate'           => new sfWidgetFormInput(),
      'title'                     => new sfWidgetFormInput(),
      'firstName'                 => new sfWidgetFormInput(),
      'lastName'                  => new sfWidgetFormInput(),
      'addressOne'                => new sfWidgetFormInput(),
      'addressTwo'                => new sfWidgetFormInput(),
      'city'                      => new sfWidgetFormInput(),
      'state'                     => new sfWidgetFormInput(),
      'zipcode'                   => new sfWidgetFormInput(),
      'dayPhone'                  => new sfWidgetFormInput(),
      'pilotDayComment'           => new sfWidgetFormInput(),
      'evePhone'                  => new sfWidgetFormInput(),
      'pilotEveComment'           => new sfWidgetFormInput(),
      'faxPhone1'                 => new sfWidgetFormInput(),
      'pilotFaxComment'           => new sfWidgetFormInput(),
      'faxPhone2'                 => new sfWidgetFormInput(),
      'pilotFaxComment2'          => new sfWidgetFormInput(),
      'mobilePhone'               => new sfWidgetFormInput(),
      'pilotMobileComment'        => new sfWidgetFormInput(),
      'pagerPhone'                => new sfWidgetFormInput(),
      'pilotPagerComment'         => new sfWidgetFormInput(),
      'otherPhone'                => new sfWidgetFormInput(),
      'pilotOtherComment'         => new sfWidgetFormInput(),
      'email'                     => new sfWidgetFormInput(),
      'pageEmail'                 => new sfWidgetFormInput(),
      'secondaryEmail'            => new sfWidgetFormInput(),
      'spouseFirstName'           => new sfWidgetFormInput(),
      'spouseLastName'            => new sfWidgetFormInput(),
      'applicantPilot'            => new sfWidgetFormInput(),
      'spousePilot'               => new sfWidgetFormInput(),
      'applicantCopilot'          => new sfWidgetFormInput(),
      'languagesSpoken'           => new sfWidgetFormInput(),
      'homeBase'                  => new sfWidgetFormInput(),
      'fboName'                   => new sfWidgetFormInput(),
      'apMake'                    => new sfWidgetFormInput(),
      'apModel'                   => new sfWidgetFormInput(),
      'aircraftPrimaryOwn'        => new sfWidgetFormInput(),
      'aircraftPrimaryIce'        => new sfWidgetFormInput(),
      'aircraftPrimarySeats'      => new sfWidgetFormInput(),
      'aircraftPrimaryNNumber'    => new sfWidgetFormInput(),
      'asMake'                    => new sfWidgetFormInput(),
      'asModel'                   => new sfWidgetFormInput(),
      'aircraftSecondaryOwn'      => new sfWidgetFormInput(),
      'aircraftSecondaryIce'      => new sfWidgetFormInput(),
      'aircraftSecondarySeats'    => new sfWidgetFormInput(),
      'aircraftSecondaryNNumber'  => new sfWidgetFormInput(),
      'pilotCertificate'          => new sfWidgetFormInput(),
      'ratings'                   => new sfWidgetFormInput(),
      'medicalClass'              => new sfWidgetFormInput(),
      'licenseType'               => new sfWidgetFormInput(),
      'totalHours'                => new sfWidgetFormInput(),
      'ifrHours'                  => new sfWidgetFormInput(),
      'multiHours'                => new sfWidgetFormInput(),
      'otherHours'                => new sfWidgetFormInput(),
      'dateOfBirth'               => new sfWidgetFormInput(),
      'height'                    => new sfWidgetFormInput(),
      'weight'                    => new sfWidgetFormInput(),
      'availabilityWeekdays'      => new sfWidgetFormInput(),
      'availabilityWeeknights'    => new sfWidgetFormInput(),
      'availabilityWeekends'      => new sfWidgetFormInput(),
      'availabilityNotice'        => new sfWidgetFormInput(),
      'availabilityLastMinute'    => new sfWidgetFormInput(),
      'availabilityCopilot'       => new sfWidgetFormInput(),
      'affirmationAgreed'         => new sfWidgetFormInput(),
      'insuranceAgreed'           => new sfWidgetFormInput(),
      'hseatsInterest'            => new sfWidgetFormInput(),
      'volunteerInterest'         => new sfWidgetFormInput(),
      'companyPosition'           => new sfWidgetFormInput(),
      'companyMatchFunds'         => new sfWidgetFormInput(),
      'companyBusinessCategoryID' => new sfWidgetFormInput(),
      'referralSource'            => new sfWidgetFormInput(),
      'referralSourceOther'       => new sfWidgetFormInput(),
      'premiumChoice'             => new sfWidgetFormInput(),
      'premiumSize'               => new sfWidgetFormInput(),
      'duesAmountPaid'            => new sfWidgetFormInput(),
      'donationAmountPaid'        => new sfWidgetFormInput(),
      'methodOfPaymentID'         => new sfWidgetFormInput(),
      'ccardApprovalNumber'       => new sfWidgetFormInput(),
      'processedDate'             => new sfWidgetFormInput(),
      'missionOrientation'        => new sfWidgetFormInput(),
      'missionCoordination'       => new sfWidgetFormInput(),
      'pilotRecruitment'          => new sfWidgetFormInput(),
      'fundRaising'               => new sfWidgetFormInput(),
      'celebrityContacts'         => new sfWidgetFormInput(),
      'hospitalOutreach'          => new sfWidgetFormInput(),
      'mediaRelations'            => new sfWidgetFormInput(),
      'telephoneWork'             => new sfWidgetFormInput(),
      'computers'                 => new sfWidgetFormInput(),
      'clerical'                  => new sfWidgetFormInput(),
      'publicity'                 => new sfWidgetFormInput(),
      'writing'                   => new sfWidgetFormInput(),
      'speakersBureau'            => new sfWidgetFormInput(),
      'wingTeam'                  => new sfWidgetFormInput(),
      'graphicArts'               => new sfWidgetFormInput(),
      'eventPlanning'             => new sfWidgetFormInput(),
      'webInternet'               => new sfWidgetFormInput(),
      'foundationContacts'        => new sfWidgetFormInput(),
      'aviationContacts'          => new sfWidgetFormInput(),
      'printing'                  => new sfWidgetFormInput(),
      'memberAOPA'                => new sfWidgetFormInput(),
      'memberKiwanis'             => new sfWidgetFormInput(),
      'memberRotary'              => new sfWidgetFormInput(),
      'memberLions'               => new sfWidgetFormInput(),
      'memberNinetyNines'         => new sfWidgetFormInput(),
      'memberWIA'                 => new sfWidgetFormInput(),
      'EDNewMemberNotify'         => new sfWidgetFormInput(),
      'WNewMemberNotify'          => new sfWidgetFormInput(),
      'badgeMade'                 => new sfWidgetFormInput(),
      'notebookSent'              => new sfWidgetFormInput(),
      'externalID'                => new sfWidgetFormInput(),
      'novapointeID'              => new sfWidgetFormInput(),
      'premiumShipDate'           => new sfWidgetFormInput(),
      'premiumShipMethod'         => new sfWidgetFormInput(),
      'premiumShipTrackingNumber' => new sfWidgetFormInput(),
      'id'                        => new sfWidgetFormInputHidden(),
    ));

    $this->setValidators(array(
      'applicationID'             => new sfValidatorInteger(),
      'applicationDate'           => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'title'                     => new sfValidatorString(array('max_length' => 12, 'required' => false)),
      'firstName'                 => new sfValidatorString(array('max_length' => 40)),
      'lastName'                  => new sfValidatorString(array('max_length' => 40)),
      'addressOne'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'addressTwo'                => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'city'                      => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'state'                     => new sfValidatorString(array('max_length' => 2, 'required' => false)),
      'zipcode'                   => new sfValidatorString(array('max_length' => 30, 'required' => false)),
      'dayPhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotDayComment'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'evePhone'                  => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotEveComment'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faxPhone1'                 => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotFaxComment'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'faxPhone2'                 => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotFaxComment2'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'mobilePhone'               => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotMobileComment'        => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'pagerPhone'                => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotPagerComment'         => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'otherPhone'                => new sfValidatorString(array('max_length' => 16, 'required' => false)),
      'pilotOtherComment'         => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'email'                     => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'pageEmail'                 => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'secondaryEmail'            => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'spouseFirstName'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'spouseLastName'            => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'applicantPilot'            => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'spousePilot'               => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'applicantCopilot'          => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'languagesSpoken'           => new sfValidatorString(array('max_length' => 125, 'required' => false)),
      'homeBase'                  => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'fboName'                   => new sfValidatorString(array('max_length' => 80, 'required' => false)),
      'apMake'                    => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'apModel'                   => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'aircraftPrimaryOwn'        => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'aircraftPrimaryIce'        => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'aircraftPrimarySeats'      => new sfValidatorInteger(array('required' => false)),
      'aircraftPrimaryNNumber'    => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'asMake'                    => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'asModel'                   => new sfValidatorString(array('max_length' => 25, 'required' => false)),
      'aircraftSecondaryOwn'      => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'aircraftSecondaryIce'      => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'aircraftSecondarySeats'    => new sfValidatorInteger(array('required' => false)),
      'aircraftSecondaryNNumber'  => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'pilotCertificate'          => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'ratings'                   => new sfValidatorString(array('max_length' => 50, 'required' => false)),
      'medicalClass'              => new sfValidatorInteger(array('required' => false)),
      'licenseType'               => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'totalHours'                => new sfValidatorInteger(array('required' => false)),
      'ifrHours'                  => new sfValidatorInteger(array('required' => false)),
      'multiHours'                => new sfValidatorInteger(array('required' => false)),
      'otherHours'                => new sfValidatorInteger(array('required' => false)),
      'dateOfBirth'               => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'height'                    => new sfValidatorInteger(array('required' => false)),
      'weight'                    => new sfValidatorInteger(array('required' => false)),
      'availabilityWeekdays'      => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'availabilityWeeknights'    => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'availabilityWeekends'      => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'availabilityNotice'        => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'availabilityLastMinute'    => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'availabilityCopilot'       => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'affirmationAgreed'         => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'insuranceAgreed'           => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'hseatsInterest'            => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'volunteerInterest'         => new sfValidatorString(array('max_length' => 255, 'required' => false)),
      'companyPosition'           => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'companyMatchFunds'         => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'companyBusinessCategoryID' => new sfValidatorInteger(array('required' => false)),
      'referralSource'            => new sfValidatorString(array('max_length' => 60, 'required' => false)),
      'referralSourceOther'       => new sfValidatorString(array('max_length' => 40, 'required' => false)),
      'premiumChoice'             => new sfValidatorString(array('max_length' => 7, 'required' => false)),
      'premiumSize'               => new sfValidatorString(array('max_length' => 8, 'required' => false)),
      'duesAmountPaid'            => new sfValidatorNumber(),
      'donationAmountPaid'        => new sfValidatorNumber(array('required' => false)),
      'methodOfPaymentID'         => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'ccardApprovalNumber'       => new sfValidatorString(array('max_length' => 20, 'required' => false)),
      'processedDate'             => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'missionOrientation'        => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'missionCoordination'       => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'pilotRecruitment'          => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'fundRaising'               => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'celebrityContacts'         => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'hospitalOutreach'          => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'mediaRelations'            => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'telephoneWork'             => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'computers'                 => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'clerical'                  => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'publicity'                 => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'writing'                   => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'speakersBureau'            => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'wingTeam'                  => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'graphicArts'               => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'eventPlanning'             => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'webInternet'               => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'foundationContacts'        => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'aviationContacts'          => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'printing'                  => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'memberAOPA'                => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'memberKiwanis'             => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'memberRotary'              => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'memberLions'               => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'memberNinetyNines'         => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'memberWIA'                 => new sfValidatorString(array('max_length' => 3, 'required' => false)),
      'EDNewMemberNotify'         => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'WNewMemberNotify'          => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'badgeMade'                 => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'notebookSent'              => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'externalID'                => new sfValidatorInteger(array('required' => false)),
      'novapointeID'              => new sfValidatorInteger(array('required' => false)),
      'premiumShipDate'           => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'premiumShipMethod'         => new sfValidatorString(array('max_length' => 10, 'required' => false)),
      'premiumShipTrackingNumber' => new sfValidatorString(array('max_length' => 35, 'required' => false)),
      'id'                        => new sfValidatorPropelChoice(array('model' => 'RpMemberApplication', 'column' => 'id', 'required' => false)),
    ));

    $this->widgetSchema->setNameFormat('rp_member_application[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'RpMemberApplication';
  }


}
