<?php

require_once(sfConfig::get('sf_lib_dir').'/filter/base/BaseFormFilterPropel.class.php');

/**
 * RpCampPassengers filter form base class.
 *
 * @package    angelflight
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormFilterGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseRpCampPassengersFormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'passID'                 => new sfWidgetFormFilterInput(),
      'passName'               => new sfWidgetFormFilterInput(),
      'passLastName'           => new sfWidgetFormFilterInput(),
      'passFirstName'          => new sfWidgetFormFilterInput(),
      'weight'                 => new sfWidgetFormFilterInput(),
      'passDayPhone'           => new sfWidgetFormFilterInput(),
      'passEvePhone'           => new sfWidgetFormFilterInput(),
      'passMobilePhone'        => new sfWidgetFormFilterInput(),
      'passPagerPhone'         => new sfWidgetFormFilterInput(),
      'passOtherPhone'         => new sfWidgetFormFilterInput(),
      'passFaxPhone'           => new sfWidgetFormFilterInput(),
      'passDayComment'         => new sfWidgetFormFilterInput(),
      'passEveComment'         => new sfWidgetFormFilterInput(),
      'passMobileComment'      => new sfWidgetFormFilterInput(),
      'passPagerComment'       => new sfWidgetFormFilterInput(),
      'passOtherComment'       => new sfWidgetFormFilterInput(),
      'passFaxComment'         => new sfWidgetFormFilterInput(),
      'reqName'                => new sfWidgetFormFilterInput(),
      'reqFirstName'           => new sfWidgetFormFilterInput(),
      'reqLastName'            => new sfWidgetFormFilterInput(),
      'reqDayPhone'            => new sfWidgetFormFilterInput(),
      'reqEvePhone'            => new sfWidgetFormFilterInput(),
      'reqMobilePhone'         => new sfWidgetFormFilterInput(),
      'reqPagerPhone'          => new sfWidgetFormFilterInput(),
      'reqOtherPhone'          => new sfWidgetFormFilterInput(),
      'reqFaxPhone'            => new sfWidgetFormFilterInput(),
      'reqDayComment'          => new sfWidgetFormFilterInput(),
      'reqEveComment'          => new sfWidgetFormFilterInput(),
      'reqMobileComment'       => new sfWidgetFormFilterInput(),
      'reqPagerComment'        => new sfWidgetFormFilterInput(),
      'reqOtherComment'        => new sfWidgetFormFilterInput(),
      'reqFaxComment'          => new sfWidgetFormFilterInput(),
      'campName'               => new sfWidgetFormFilterInput(),
      'campPhone'              => new sfWidgetFormFilterInput(),
      'pilotName'              => new sfWidgetFormFilterInput(),
      'pilotFirstName'         => new sfWidgetFormFilterInput(),
      'pilotLastName'          => new sfWidgetFormFilterInput(),
      'pilotMemberID'          => new sfWidgetFormFilterInput(),
      'pilotDayPhone'          => new sfWidgetFormFilterInput(),
      'pilotEvePhone'          => new sfWidgetFormFilterInput(),
      'pilotMobilePhone'       => new sfWidgetFormFilterInput(),
      'pilotOtherPhone'        => new sfWidgetFormFilterInput(),
      'pilotPagerPhone'        => new sfWidgetFormFilterInput(),
      'pilotFaxPhone'          => new sfWidgetFormFilterInput(),
      'homeBase'               => new sfWidgetFormFilterInput(),
      'pilotDayComment'        => new sfWidgetFormFilterInput(),
      'pilotEveComment'        => new sfWidgetFormFilterInput(),
      'pilotMobileComment'     => new sfWidgetFormFilterInput(),
      'pilotPagerComment'      => new sfWidgetFormFilterInput(),
      'pilotOtherComment'      => new sfWidgetFormFilterInput(),
      'pilotFaxComment'        => new sfWidgetFormFilterInput(),
      'pilotEmail'             => new sfWidgetFormFilterInput(),
      'ifr'                    => new sfWidgetFormFilterInput(),
      'toAirportName'          => new sfWidgetFormFilterInput(),
      'toAirportIdent'         => new sfWidgetFormFilterInput(),
      'fromAirportName'        => new sfWidgetFormFilterInput(),
      'fromAirportIdent'       => new sfWidgetFormFilterInput(),
      'missionID'              => new sfWidgetFormFilterInput(),
      'missionSelectDate'      => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'missionDate'            => new sfWidgetFormFilterInput(),
      'medicalReleaseReceived' => new sfWidgetFormFilterInput(),
      'waiverReceived'         => new sfWidgetFormFilterInput(),
      'private_c_note'         => new sfWidgetFormFilterInput(),
      'cancelled'              => new sfWidgetFormFilterInput(),
      'n_number'               => new sfWidgetFormFilterInput(),
      'make'                   => new sfWidgetFormFilterInput(),
      'model'                  => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'passID'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'passName'               => new sfValidatorPass(array('required' => false)),
      'passLastName'           => new sfValidatorPass(array('required' => false)),
      'passFirstName'          => new sfValidatorPass(array('required' => false)),
      'weight'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'passDayPhone'           => new sfValidatorPass(array('required' => false)),
      'passEvePhone'           => new sfValidatorPass(array('required' => false)),
      'passMobilePhone'        => new sfValidatorPass(array('required' => false)),
      'passPagerPhone'         => new sfValidatorPass(array('required' => false)),
      'passOtherPhone'         => new sfValidatorPass(array('required' => false)),
      'passFaxPhone'           => new sfValidatorPass(array('required' => false)),
      'passDayComment'         => new sfValidatorPass(array('required' => false)),
      'passEveComment'         => new sfValidatorPass(array('required' => false)),
      'passMobileComment'      => new sfValidatorPass(array('required' => false)),
      'passPagerComment'       => new sfValidatorPass(array('required' => false)),
      'passOtherComment'       => new sfValidatorPass(array('required' => false)),
      'passFaxComment'         => new sfValidatorPass(array('required' => false)),
      'reqName'                => new sfValidatorPass(array('required' => false)),
      'reqFirstName'           => new sfValidatorPass(array('required' => false)),
      'reqLastName'            => new sfValidatorPass(array('required' => false)),
      'reqDayPhone'            => new sfValidatorPass(array('required' => false)),
      'reqEvePhone'            => new sfValidatorPass(array('required' => false)),
      'reqMobilePhone'         => new sfValidatorPass(array('required' => false)),
      'reqPagerPhone'          => new sfValidatorPass(array('required' => false)),
      'reqOtherPhone'          => new sfValidatorPass(array('required' => false)),
      'reqFaxPhone'            => new sfValidatorPass(array('required' => false)),
      'reqDayComment'          => new sfValidatorPass(array('required' => false)),
      'reqEveComment'          => new sfValidatorPass(array('required' => false)),
      'reqMobileComment'       => new sfValidatorPass(array('required' => false)),
      'reqPagerComment'        => new sfValidatorPass(array('required' => false)),
      'reqOtherComment'        => new sfValidatorPass(array('required' => false)),
      'reqFaxComment'          => new sfValidatorPass(array('required' => false)),
      'campName'               => new sfValidatorPass(array('required' => false)),
      'campPhone'              => new sfValidatorPass(array('required' => false)),
      'pilotName'              => new sfValidatorPass(array('required' => false)),
      'pilotFirstName'         => new sfValidatorPass(array('required' => false)),
      'pilotLastName'          => new sfValidatorPass(array('required' => false)),
      'pilotMemberID'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pilotDayPhone'          => new sfValidatorPass(array('required' => false)),
      'pilotEvePhone'          => new sfValidatorPass(array('required' => false)),
      'pilotMobilePhone'       => new sfValidatorPass(array('required' => false)),
      'pilotOtherPhone'        => new sfValidatorPass(array('required' => false)),
      'pilotPagerPhone'        => new sfValidatorPass(array('required' => false)),
      'pilotFaxPhone'          => new sfValidatorPass(array('required' => false)),
      'homeBase'               => new sfValidatorPass(array('required' => false)),
      'pilotDayComment'        => new sfValidatorPass(array('required' => false)),
      'pilotEveComment'        => new sfValidatorPass(array('required' => false)),
      'pilotMobileComment'     => new sfValidatorPass(array('required' => false)),
      'pilotPagerComment'      => new sfValidatorPass(array('required' => false)),
      'pilotOtherComment'      => new sfValidatorPass(array('required' => false)),
      'pilotFaxComment'        => new sfValidatorPass(array('required' => false)),
      'pilotEmail'             => new sfValidatorPass(array('required' => false)),
      'ifr'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'toAirportName'          => new sfValidatorPass(array('required' => false)),
      'toAirportIdent'         => new sfValidatorPass(array('required' => false)),
      'fromAirportName'        => new sfValidatorPass(array('required' => false)),
      'fromAirportIdent'       => new sfValidatorPass(array('required' => false)),
      'missionID'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'missionSelectDate'      => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'missionDate'            => new sfValidatorPass(array('required' => false)),
      'medicalReleaseReceived' => new sfValidatorPass(array('required' => false)),
      'waiverReceived'         => new sfValidatorPass(array('required' => false)),
      'private_c_note'         => new sfValidatorPass(array('required' => false)),
      'cancelled'              => new sfValidatorPass(array('required' => false)),
      'n_number'               => new sfValidatorPass(array('required' => false)),
      'make'                   => new sfValidatorPass(array('required' => false)),
      'model'                  => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('rp_camp_passengers_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'RpCampPassengers';
  }

  public function getFields()
  {
    return array(
      'passID'                 => 'Number',
      'passName'               => 'Text',
      'passLastName'           => 'Text',
      'passFirstName'          => 'Text',
      'weight'                 => 'Number',
      'passDayPhone'           => 'Text',
      'passEvePhone'           => 'Text',
      'passMobilePhone'        => 'Text',
      'passPagerPhone'         => 'Text',
      'passOtherPhone'         => 'Text',
      'passFaxPhone'           => 'Text',
      'passDayComment'         => 'Text',
      'passEveComment'         => 'Text',
      'passMobileComment'      => 'Text',
      'passPagerComment'       => 'Text',
      'passOtherComment'       => 'Text',
      'passFaxComment'         => 'Text',
      'reqName'                => 'Text',
      'reqFirstName'           => 'Text',
      'reqLastName'            => 'Text',
      'reqDayPhone'            => 'Text',
      'reqEvePhone'            => 'Text',
      'reqMobilePhone'         => 'Text',
      'reqPagerPhone'          => 'Text',
      'reqOtherPhone'          => 'Text',
      'reqFaxPhone'            => 'Text',
      'reqDayComment'          => 'Text',
      'reqEveComment'          => 'Text',
      'reqMobileComment'       => 'Text',
      'reqPagerComment'        => 'Text',
      'reqOtherComment'        => 'Text',
      'reqFaxComment'          => 'Text',
      'campName'               => 'Text',
      'campPhone'              => 'Text',
      'pilotName'              => 'Text',
      'pilotFirstName'         => 'Text',
      'pilotLastName'          => 'Text',
      'pilotMemberID'          => 'Number',
      'pilotDayPhone'          => 'Text',
      'pilotEvePhone'          => 'Text',
      'pilotMobilePhone'       => 'Text',
      'pilotOtherPhone'        => 'Text',
      'pilotPagerPhone'        => 'Text',
      'pilotFaxPhone'          => 'Text',
      'homeBase'               => 'Text',
      'pilotDayComment'        => 'Text',
      'pilotEveComment'        => 'Text',
      'pilotMobileComment'     => 'Text',
      'pilotPagerComment'      => 'Text',
      'pilotOtherComment'      => 'Text',
      'pilotFaxComment'        => 'Text',
      'pilotEmail'             => 'Text',
      'ifr'                    => 'Number',
      'toAirportName'          => 'Text',
      'toAirportIdent'         => 'Text',
      'fromAirportName'        => 'Text',
      'fromAirportIdent'       => 'Text',
      'missionID'              => 'Number',
      'missionSelectDate'      => 'Date',
      'missionDate'            => 'Text',
      'medicalReleaseReceived' => 'Text',
      'waiverReceived'         => 'Text',
      'private_c_note'         => 'Text',
      'cancelled'              => 'Text',
      'n_number'               => 'Text',
      'make'                   => 'Text',
      'model'                  => 'Text',
      'id'                     => 'Number',
    );
  }
}
