<?php

require_once(sfConfig::get('sf_lib_dir').'/filter/base/BaseFormFilterPropel.class.php');

/**
 * MissionRequestTemp filter form base class.
 *
 * @package    angelflight
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormFilterGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseMissionRequestTempFormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'request_date'                   => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'request_by'                     => new sfWidgetFormFilterInput(),
      'request_on_behalf'              => new sfWidgetFormFilterInput(),
      'appt_date'                      => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'return_date'                    => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'baggage_weight'                 => new sfWidgetFormFilterInput(),
      'baggage_desc'                   => new sfWidgetFormFilterInput(),
      'pass_title'                     => new sfWidgetFormFilterInput(),
      'pass_first_name'                => new sfWidgetFormFilterInput(),
      'pass_last_name'                 => new sfWidgetFormFilterInput(),
      'pass_address1'                  => new sfWidgetFormFilterInput(),
      'pass_address2'                  => new sfWidgetFormFilterInput(),
      'pass_city'                      => new sfWidgetFormFilterInput(),
      'pass_county'                    => new sfWidgetFormFilterInput(),
      'pass_state'                     => new sfWidgetFormFilterInput(),
      'pass_country'                   => new sfWidgetFormFilterInput(),
      'pass_zipcode'                   => new sfWidgetFormFilterInput(),
      'pass_day_phone'                 => new sfWidgetFormFilterInput(),
      'pass_day_comment'               => new sfWidgetFormFilterInput(),
      'pass_eve_phone'                 => new sfWidgetFormFilterInput(),
      'pass_eve_comment'               => new sfWidgetFormFilterInput(),
      'pass_mobile_phone'              => new sfWidgetFormFilterInput(),
      'pass_mobile_comment'            => new sfWidgetFormFilterInput(),
      'pass_pager_phone'               => new sfWidgetFormFilterInput(),
      'pass_pager_comment'             => new sfWidgetFormFilterInput(),
      'pass_other_phone'               => new sfWidgetFormFilterInput(),
      'pass_other_comment'             => new sfWidgetFormFilterInput(),
      'pass_email'                     => new sfWidgetFormFilterInput(),
      'pass_date_of_birth'             => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'illness'                        => new sfWidgetFormFilterInput(),
      'financial'                      => new sfWidgetFormFilterInput(),
      'pass_weight'                    => new sfWidgetFormFilterInput(),
      'releasing_physician'            => new sfWidgetFormFilterInput(),
      'release_phone'                  => new sfWidgetFormFilterInput(),
      'release_phone_comment'          => new sfWidgetFormFilterInput(),
      'release_fax'                    => new sfWidgetFormFilterInput(),
      'release_fax_comment'            => new sfWidgetFormFilterInput(),
      'release_email'                  => new sfWidgetFormFilterInput(),
      'treating_physician'             => new sfWidgetFormFilterInput(),
      'treating_phone'                 => new sfWidgetFormFilterInput(),
      'treating_phone_comment'         => new sfWidgetFormFilterInput(),
      'treating_fax'                   => new sfWidgetFormFilterInput(),
      'treating_fax_comment'           => new sfWidgetFormFilterInput(),
      'req_title'                      => new sfWidgetFormFilterInput(),
      'req_first_name'                 => new sfWidgetFormFilterInput(),
      'req_last_name'                  => new sfWidgetFormFilterInput(),
      'agency_name'                    => new sfWidgetFormFilterInput(),
      'req_address1'                   => new sfWidgetFormFilterInput(),
      'req_address2'                   => new sfWidgetFormFilterInput(),
      'req_city'                       => new sfWidgetFormFilterInput(),
      'req_county'                     => new sfWidgetFormFilterInput(),
      'req_state'                      => new sfWidgetFormFilterInput(),
      'req_country'                    => new sfWidgetFormFilterInput(),
      'req_zipcode'                    => new sfWidgetFormFilterInput(),
      'req_day_phone'                  => new sfWidgetFormFilterInput(),
      'req_day_comment'                => new sfWidgetFormFilterInput(),
      'req_eve_phone'                  => new sfWidgetFormFilterInput(),
      'req_eve_comment'                => new sfWidgetFormFilterInput(),
      'req_mobile_phone'               => new sfWidgetFormFilterInput(),
      'req_mobile_comment'             => new sfWidgetFormFilterInput(),
      'req_pager_phone'                => new sfWidgetFormFilterInput(),
      'req_pager_comment'              => new sfWidgetFormFilterInput(),
      'req_other_phone'                => new sfWidgetFormFilterInput(),
      'req_other_comment'              => new sfWidgetFormFilterInput(),
      'req_email'                      => new sfWidgetFormFilterInput(),
      'origin_ident'                   => new sfWidgetFormFilterInput(),
      'origin_id'                      => new sfWidgetFormFilterInput(),
      'origin_city'                    => new sfWidgetFormFilterInput(),
      'origin_state'                   => new sfWidgetFormFilterInput(),
      'origin_zipcode'                 => new sfWidgetFormFilterInput(),
      'dest_ident'                     => new sfWidgetFormFilterInput(),
      'dest_id'                        => new sfWidgetFormFilterInput(),
      'dest_city'                      => new sfWidgetFormFilterInput(),
      'dest_state'                     => new sfWidgetFormFilterInput(),
      'dest_zipcode'                   => new sfWidgetFormFilterInput(),
      'com1_name'                      => new sfWidgetFormFilterInput(),
      'com1_relationship'              => new sfWidgetFormFilterInput(),
      'com1_date_of_birth'             => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'com1_weight'                    => new sfWidgetFormFilterInput(),
      'com1_phone'                     => new sfWidgetFormFilterInput(),
      'com1_comment'                   => new sfWidgetFormFilterInput(),
      'com2_name'                      => new sfWidgetFormFilterInput(),
      'com2_relationship'              => new sfWidgetFormFilterInput(),
      'com2_date_of_birth'             => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'com2_weight'                    => new sfWidgetFormFilterInput(),
      'com2_phone'                     => new sfWidgetFormFilterInput(),
      'com2_comment'                   => new sfWidgetFormFilterInput(),
      'com3_name'                      => new sfWidgetFormFilterInput(),
      'com3_relationship'              => new sfWidgetFormFilterInput(),
      'com3_date_of_birth'             => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'com3_weight'                    => new sfWidgetFormFilterInput(),
      'com3_phone'                     => new sfWidgetFormFilterInput(),
      'com3_comment'                   => new sfWidgetFormFilterInput(),
      'com4_name'                      => new sfWidgetFormFilterInput(),
      'com4_relationship'              => new sfWidgetFormFilterInput(),
      'com4_date_of_birth'             => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'com4_weight'                    => new sfWidgetFormFilterInput(),
      'com4_phone'                     => new sfWidgetFormFilterInput(),
      'com4_comment'                   => new sfWidgetFormFilterInput(),
      'lodging_name'                   => new sfWidgetFormFilterInput(),
      'lodging_phone'                  => new sfWidgetFormFilterInput(),
      'facility_name'                  => new sfWidgetFormFilterInput(),
      'facility_phone'                 => new sfWidgetFormFilterInput(),
      'facility_phone_comment'         => new sfWidgetFormFilterInput(),
      'req_language_spoken'            => new sfWidgetFormFilterInput(),
      'best_contact'                   => new sfWidgetFormFilterInput(),
      'emergency_name'                 => new sfWidgetFormFilterInput(),
      'emergency_phone1'               => new sfWidgetFormFilterInput(),
      'emergency_phone2'               => new sfWidgetFormFilterInput(),
      'emergency_phone1_comment'       => new sfWidgetFormFilterInput(),
      'emergency_phone2_comment'       => new sfWidgetFormFilterInput(),
      'comment'                        => new sfWidgetFormFilterInput(),
      'processed_date'                 => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'session_id'                     => new sfWidgetFormFilterInput(),
      'ip_address'                     => new sfWidgetFormFilterInput(),
      'pass_fax_phone1'                => new sfWidgetFormFilterInput(),
      'pass_fax_comment1'              => new sfWidgetFormFilterInput(),
      'guar_first_name'                => new sfWidgetFormFilterInput(),
      'guar_last_name'                 => new sfWidgetFormFilterInput(),
      'guar_address1'                  => new sfWidgetFormFilterInput(),
      'guar_address2'                  => new sfWidgetFormFilterInput(),
      'guar_city'                      => new sfWidgetFormFilterInput(),
      'guar_state'                     => new sfWidgetFormFilterInput(),
      'guar_zipcode'                   => new sfWidgetFormFilterInput(),
      'guar_day_phone'                 => new sfWidgetFormFilterInput(),
      'guar_day_comment'               => new sfWidgetFormFilterInput(),
      'guar_eve_phone'                 => new sfWidgetFormFilterInput(),
      'guar_eve_comment'               => new sfWidgetFormFilterInput(),
      'guar_fax_phone1'                => new sfWidgetFormFilterInput(),
      'guar_fax_comment1'              => new sfWidgetFormFilterInput(),
      'guar_mobile_phone'              => new sfWidgetFormFilterInput(),
      'guar_mobile_comment'            => new sfWidgetFormFilterInput(),
      'guar_pager_phone'               => new sfWidgetFormFilterInput(),
      'guar_pager_comment'             => new sfWidgetFormFilterInput(),
      'guar_other_phone'               => new sfWidgetFormFilterInput(),
      'guar_other_comment'             => new sfWidgetFormFilterInput(),
      'guar_guar_email'                => new sfWidgetFormFilterInput(),
      'req_fax_phone1'                 => new sfWidgetFormFilterInput(),
      'req_fax_comment1'               => new sfWidgetFormFilterInput(),
      'pass_english'                   => new sfWidgetFormFilterInput(),
      'pass_language'                  => new sfWidgetFormFilterInput(),
      'appt_time'                      => new sfWidgetFormFilterInput(),
      'requester_id'                   => new sfWidgetFormFilterInput(),
      'passenger_id'                   => new sfWidgetFormFilterInput(),
      'mission_id'                     => new sfWidgetFormFilterInput(),
      'treating_email'                 => new sfWidgetFormFilterInput(),
      'pass_height'                    => new sfWidgetFormFilterInput(),
      'return_time'                    => new sfWidgetFormFilterInput(),
      'pass_oxygen'                    => new sfWidgetFormFilterInput(),
      'pass_medical'                   => new sfWidgetFormFilterInput(),
      'referral_source_id'             => new sfWidgetFormFilterInput(),
      'follow_up_contact_name'         => new sfWidgetFormFilterInput(),
      'follow_up_contact_phone'        => new sfWidgetFormFilterInput(),
      'follow_up_email'                => new sfWidgetFormFilterInput(),
      'miss_req_originator_afa_org_id' => new sfWidgetFormFilterInput(),
      'afa_org_id'                     => new sfWidgetFormFilterInput(),
      'afa_org_mission_id'             => new sfWidgetFormFilterInput(),
      'mission_request_type'           => new sfWidgetFormFilterInput(),
      'last_page_processed'            => new sfWidgetFormFilterInput(),
      'guardian_middle_name'           => new sfWidgetFormFilterInput(),
      'guardian_nickname'              => new sfWidgetFormFilterInput(),
      'guardian_pager_email'           => new sfWidgetFormFilterInput(),
      'guardian_secondary_email'       => new sfWidgetFormFilterInput(),
      'guardian_suffix'                => new sfWidgetFormFilterInput(),
      'guardian_title'                 => new sfWidgetFormFilterInput(),
      'guardian_veteran'               => new sfWidgetFormFilterInput(),
      'pass_gender'                    => new sfWidgetFormFilterInput(),
      'pass_middle_name'               => new sfWidgetFormFilterInput(),
      'pass_nickname'                  => new sfWidgetFormFilterInput(),
      'pass_pager_email'               => new sfWidgetFormFilterInput(),
      'pass_secondary_email'           => new sfWidgetFormFilterInput(),
      'pass_suffix'                    => new sfWidgetFormFilterInput(),
      'pass_veteran'                   => new sfWidgetFormFilterInput(),
      'req_middle_name'                => new sfWidgetFormFilterInput(),
      'req_nickname'                   => new sfWidgetFormFilterInput(),
      'req_pager_email'                => new sfWidgetFormFilterInput(),
      'req_secondary_email'            => new sfWidgetFormFilterInput(),
      'req_suffix'                     => new sfWidgetFormFilterInput(),
      'req_veteran'                    => new sfWidgetFormFilterInput(),
      'lodging_phone_comment'          => new sfWidgetFormFilterInput(),
      'req_gender'                     => new sfWidgetFormFilterInput(),
      'guardian_gender'                => new sfWidgetFormFilterInput(),
      'agency_position'                => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'request_date'                   => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'request_by'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'request_on_behalf'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'appt_date'                      => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'return_date'                    => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'baggage_weight'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'baggage_desc'                   => new sfValidatorPass(array('required' => false)),
      'pass_title'                     => new sfValidatorPass(array('required' => false)),
      'pass_first_name'                => new sfValidatorPass(array('required' => false)),
      'pass_last_name'                 => new sfValidatorPass(array('required' => false)),
      'pass_address1'                  => new sfValidatorPass(array('required' => false)),
      'pass_address2'                  => new sfValidatorPass(array('required' => false)),
      'pass_city'                      => new sfValidatorPass(array('required' => false)),
      'pass_county'                    => new sfValidatorPass(array('required' => false)),
      'pass_state'                     => new sfValidatorPass(array('required' => false)),
      'pass_country'                   => new sfValidatorPass(array('required' => false)),
      'pass_zipcode'                   => new sfValidatorPass(array('required' => false)),
      'pass_day_phone'                 => new sfValidatorPass(array('required' => false)),
      'pass_day_comment'               => new sfValidatorPass(array('required' => false)),
      'pass_eve_phone'                 => new sfValidatorPass(array('required' => false)),
      'pass_eve_comment'               => new sfValidatorPass(array('required' => false)),
      'pass_mobile_phone'              => new sfValidatorPass(array('required' => false)),
      'pass_mobile_comment'            => new sfValidatorPass(array('required' => false)),
      'pass_pager_phone'               => new sfValidatorPass(array('required' => false)),
      'pass_pager_comment'             => new sfValidatorPass(array('required' => false)),
      'pass_other_phone'               => new sfValidatorPass(array('required' => false)),
      'pass_other_comment'             => new sfValidatorPass(array('required' => false)),
      'pass_email'                     => new sfValidatorPass(array('required' => false)),
      'pass_date_of_birth'             => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'illness'                        => new sfValidatorPass(array('required' => false)),
      'financial'                      => new sfValidatorPass(array('required' => false)),
      'pass_weight'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'releasing_physician'            => new sfValidatorPass(array('required' => false)),
      'release_phone'                  => new sfValidatorPass(array('required' => false)),
      'release_phone_comment'          => new sfValidatorPass(array('required' => false)),
      'release_fax'                    => new sfValidatorPass(array('required' => false)),
      'release_fax_comment'            => new sfValidatorPass(array('required' => false)),
      'release_email'                  => new sfValidatorPass(array('required' => false)),
      'treating_physician'             => new sfValidatorPass(array('required' => false)),
      'treating_phone'                 => new sfValidatorPass(array('required' => false)),
      'treating_phone_comment'         => new sfValidatorPass(array('required' => false)),
      'treating_fax'                   => new sfValidatorPass(array('required' => false)),
      'treating_fax_comment'           => new sfValidatorPass(array('required' => false)),
      'req_title'                      => new sfValidatorPass(array('required' => false)),
      'req_first_name'                 => new sfValidatorPass(array('required' => false)),
      'req_last_name'                  => new sfValidatorPass(array('required' => false)),
      'agency_name'                    => new sfValidatorPass(array('required' => false)),
      'req_address1'                   => new sfValidatorPass(array('required' => false)),
      'req_address2'                   => new sfValidatorPass(array('required' => false)),
      'req_city'                       => new sfValidatorPass(array('required' => false)),
      'req_county'                     => new sfValidatorPass(array('required' => false)),
      'req_state'                      => new sfValidatorPass(array('required' => false)),
      'req_country'                    => new sfValidatorPass(array('required' => false)),
      'req_zipcode'                    => new sfValidatorPass(array('required' => false)),
      'req_day_phone'                  => new sfValidatorPass(array('required' => false)),
      'req_day_comment'                => new sfValidatorPass(array('required' => false)),
      'req_eve_phone'                  => new sfValidatorPass(array('required' => false)),
      'req_eve_comment'                => new sfValidatorPass(array('required' => false)),
      'req_mobile_phone'               => new sfValidatorPass(array('required' => false)),
      'req_mobile_comment'             => new sfValidatorPass(array('required' => false)),
      'req_pager_phone'                => new sfValidatorPass(array('required' => false)),
      'req_pager_comment'              => new sfValidatorPass(array('required' => false)),
      'req_other_phone'                => new sfValidatorPass(array('required' => false)),
      'req_other_comment'              => new sfValidatorPass(array('required' => false)),
      'req_email'                      => new sfValidatorPass(array('required' => false)),
      'origin_ident'                   => new sfValidatorPass(array('required' => false)),
      'origin_id'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'origin_city'                    => new sfValidatorPass(array('required' => false)),
      'origin_state'                   => new sfValidatorPass(array('required' => false)),
      'origin_zipcode'                 => new sfValidatorPass(array('required' => false)),
      'dest_ident'                     => new sfValidatorPass(array('required' => false)),
      'dest_id'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dest_city'                      => new sfValidatorPass(array('required' => false)),
      'dest_state'                     => new sfValidatorPass(array('required' => false)),
      'dest_zipcode'                   => new sfValidatorPass(array('required' => false)),
      'com1_name'                      => new sfValidatorPass(array('required' => false)),
      'com1_relationship'              => new sfValidatorPass(array('required' => false)),
      'com1_date_of_birth'             => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'com1_weight'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'com1_phone'                     => new sfValidatorPass(array('required' => false)),
      'com1_comment'                   => new sfValidatorPass(array('required' => false)),
      'com2_name'                      => new sfValidatorPass(array('required' => false)),
      'com2_relationship'              => new sfValidatorPass(array('required' => false)),
      'com2_date_of_birth'             => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'com2_weight'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'com2_phone'                     => new sfValidatorPass(array('required' => false)),
      'com2_comment'                   => new sfValidatorPass(array('required' => false)),
      'com3_name'                      => new sfValidatorPass(array('required' => false)),
      'com3_relationship'              => new sfValidatorPass(array('required' => false)),
      'com3_date_of_birth'             => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'com3_weight'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'com3_phone'                     => new sfValidatorPass(array('required' => false)),
      'com3_comment'                   => new sfValidatorPass(array('required' => false)),
      'com4_name'                      => new sfValidatorPass(array('required' => false)),
      'com4_relationship'              => new sfValidatorPass(array('required' => false)),
      'com4_date_of_birth'             => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'com4_weight'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'com4_phone'                     => new sfValidatorPass(array('required' => false)),
      'com4_comment'                   => new sfValidatorPass(array('required' => false)),
      'lodging_name'                   => new sfValidatorPass(array('required' => false)),
      'lodging_phone'                  => new sfValidatorPass(array('required' => false)),
      'facility_name'                  => new sfValidatorPass(array('required' => false)),
      'facility_phone'                 => new sfValidatorPass(array('required' => false)),
      'facility_phone_comment'         => new sfValidatorPass(array('required' => false)),
      'req_language_spoken'            => new sfValidatorPass(array('required' => false)),
      'best_contact'                   => new sfValidatorPass(array('required' => false)),
      'emergency_name'                 => new sfValidatorPass(array('required' => false)),
      'emergency_phone1'               => new sfValidatorPass(array('required' => false)),
      'emergency_phone2'               => new sfValidatorPass(array('required' => false)),
      'emergency_phone1_comment'       => new sfValidatorPass(array('required' => false)),
      'emergency_phone2_comment'       => new sfValidatorPass(array('required' => false)),
      'comment'                        => new sfValidatorPass(array('required' => false)),
      'processed_date'                 => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'session_id'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ip_address'                     => new sfValidatorPass(array('required' => false)),
      'pass_fax_phone1'                => new sfValidatorPass(array('required' => false)),
      'pass_fax_comment1'              => new sfValidatorPass(array('required' => false)),
      'guar_first_name'                => new sfValidatorPass(array('required' => false)),
      'guar_last_name'                 => new sfValidatorPass(array('required' => false)),
      'guar_address1'                  => new sfValidatorPass(array('required' => false)),
      'guar_address2'                  => new sfValidatorPass(array('required' => false)),
      'guar_city'                      => new sfValidatorPass(array('required' => false)),
      'guar_state'                     => new sfValidatorPass(array('required' => false)),
      'guar_zipcode'                   => new sfValidatorPass(array('required' => false)),
      'guar_day_phone'                 => new sfValidatorPass(array('required' => false)),
      'guar_day_comment'               => new sfValidatorPass(array('required' => false)),
      'guar_eve_phone'                 => new sfValidatorPass(array('required' => false)),
      'guar_eve_comment'               => new sfValidatorPass(array('required' => false)),
      'guar_fax_phone1'                => new sfValidatorPass(array('required' => false)),
      'guar_fax_comment1'              => new sfValidatorPass(array('required' => false)),
      'guar_mobile_phone'              => new sfValidatorPass(array('required' => false)),
      'guar_mobile_comment'            => new sfValidatorPass(array('required' => false)),
      'guar_pager_phone'               => new sfValidatorPass(array('required' => false)),
      'guar_pager_comment'             => new sfValidatorPass(array('required' => false)),
      'guar_other_phone'               => new sfValidatorPass(array('required' => false)),
      'guar_other_comment'             => new sfValidatorPass(array('required' => false)),
      'guar_guar_email'                => new sfValidatorPass(array('required' => false)),
      'req_fax_phone1'                 => new sfValidatorPass(array('required' => false)),
      'req_fax_comment1'               => new sfValidatorPass(array('required' => false)),
      'pass_english'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pass_language'                  => new sfValidatorPass(array('required' => false)),
      'appt_time'                      => new sfValidatorPass(array('required' => false)),
      'requester_id'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'passenger_id'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mission_id'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'treating_email'                 => new sfValidatorPass(array('required' => false)),
      'pass_height'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'return_time'                    => new sfValidatorPass(array('required' => false)),
      'pass_oxygen'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pass_medical'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'referral_source_id'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'follow_up_contact_name'         => new sfValidatorPass(array('required' => false)),
      'follow_up_contact_phone'        => new sfValidatorPass(array('required' => false)),
      'follow_up_email'                => new sfValidatorPass(array('required' => false)),
      'miss_req_originator_afa_org_id' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'afa_org_id'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'afa_org_mission_id'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mission_request_type'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'last_page_processed'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'guardian_middle_name'           => new sfValidatorPass(array('required' => false)),
      'guardian_nickname'              => new sfValidatorPass(array('required' => false)),
      'guardian_pager_email'           => new sfValidatorPass(array('required' => false)),
      'guardian_secondary_email'       => new sfValidatorPass(array('required' => false)),
      'guardian_suffix'                => new sfValidatorPass(array('required' => false)),
      'guardian_title'                 => new sfValidatorPass(array('required' => false)),
      'guardian_veteran'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pass_gender'                    => new sfValidatorPass(array('required' => false)),
      'pass_middle_name'               => new sfValidatorPass(array('required' => false)),
      'pass_nickname'                  => new sfValidatorPass(array('required' => false)),
      'pass_pager_email'               => new sfValidatorPass(array('required' => false)),
      'pass_secondary_email'           => new sfValidatorPass(array('required' => false)),
      'pass_suffix'                    => new sfValidatorPass(array('required' => false)),
      'pass_veteran'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'req_middle_name'                => new sfValidatorPass(array('required' => false)),
      'req_nickname'                   => new sfValidatorPass(array('required' => false)),
      'req_pager_email'                => new sfValidatorPass(array('required' => false)),
      'req_secondary_email'            => new sfValidatorPass(array('required' => false)),
      'req_suffix'                     => new sfValidatorPass(array('required' => false)),
      'req_veteran'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'lodging_phone_comment'          => new sfValidatorPass(array('required' => false)),
      'req_gender'                     => new sfValidatorPass(array('required' => false)),
      'guardian_gender'                => new sfValidatorPass(array('required' => false)),
      'agency_position'                => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('mission_request_temp_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'MissionRequestTemp';
  }

  public function getFields()
  {
    return array(
      'id'                             => 'Number',
      'request_date'                   => 'Date',
      'request_by'                     => 'Number',
      'request_on_behalf'              => 'Number',
      'appt_date'                      => 'Date',
      'return_date'                    => 'Date',
      'baggage_weight'                 => 'Number',
      'baggage_desc'                   => 'Text',
      'pass_title'                     => 'Text',
      'pass_first_name'                => 'Text',
      'pass_last_name'                 => 'Text',
      'pass_address1'                  => 'Text',
      'pass_address2'                  => 'Text',
      'pass_city'                      => 'Text',
      'pass_county'                    => 'Text',
      'pass_state'                     => 'Text',
      'pass_country'                   => 'Text',
      'pass_zipcode'                   => 'Text',
      'pass_day_phone'                 => 'Text',
      'pass_day_comment'               => 'Text',
      'pass_eve_phone'                 => 'Text',
      'pass_eve_comment'               => 'Text',
      'pass_mobile_phone'              => 'Text',
      'pass_mobile_comment'            => 'Text',
      'pass_pager_phone'               => 'Text',
      'pass_pager_comment'             => 'Text',
      'pass_other_phone'               => 'Text',
      'pass_other_comment'             => 'Text',
      'pass_email'                     => 'Text',
      'pass_date_of_birth'             => 'Date',
      'illness'                        => 'Text',
      'financial'                      => 'Text',
      'pass_weight'                    => 'Number',
      'releasing_physician'            => 'Text',
      'release_phone'                  => 'Text',
      'release_phone_comment'          => 'Text',
      'release_fax'                    => 'Text',
      'release_fax_comment'            => 'Text',
      'release_email'                  => 'Text',
      'treating_physician'             => 'Text',
      'treating_phone'                 => 'Text',
      'treating_phone_comment'         => 'Text',
      'treating_fax'                   => 'Text',
      'treating_fax_comment'           => 'Text',
      'req_title'                      => 'Text',
      'req_first_name'                 => 'Text',
      'req_last_name'                  => 'Text',
      'agency_name'                    => 'Text',
      'req_address1'                   => 'Text',
      'req_address2'                   => 'Text',
      'req_city'                       => 'Text',
      'req_county'                     => 'Text',
      'req_state'                      => 'Text',
      'req_country'                    => 'Text',
      'req_zipcode'                    => 'Text',
      'req_day_phone'                  => 'Text',
      'req_day_comment'                => 'Text',
      'req_eve_phone'                  => 'Text',
      'req_eve_comment'                => 'Text',
      'req_mobile_phone'               => 'Text',
      'req_mobile_comment'             => 'Text',
      'req_pager_phone'                => 'Text',
      'req_pager_comment'              => 'Text',
      'req_other_phone'                => 'Text',
      'req_other_comment'              => 'Text',
      'req_email'                      => 'Text',
      'origin_ident'                   => 'Text',
      'origin_id'                      => 'Number',
      'origin_city'                    => 'Text',
      'origin_state'                   => 'Text',
      'origin_zipcode'                 => 'Text',
      'dest_ident'                     => 'Text',
      'dest_id'                        => 'Number',
      'dest_city'                      => 'Text',
      'dest_state'                     => 'Text',
      'dest_zipcode'                   => 'Text',
      'com1_name'                      => 'Text',
      'com1_relationship'              => 'Text',
      'com1_date_of_birth'             => 'Date',
      'com1_weight'                    => 'Number',
      'com1_phone'                     => 'Text',
      'com1_comment'                   => 'Text',
      'com2_name'                      => 'Text',
      'com2_relationship'              => 'Text',
      'com2_date_of_birth'             => 'Date',
      'com2_weight'                    => 'Number',
      'com2_phone'                     => 'Text',
      'com2_comment'                   => 'Text',
      'com3_name'                      => 'Text',
      'com3_relationship'              => 'Text',
      'com3_date_of_birth'             => 'Date',
      'com3_weight'                    => 'Number',
      'com3_phone'                     => 'Text',
      'com3_comment'                   => 'Text',
      'com4_name'                      => 'Text',
      'com4_relationship'              => 'Text',
      'com4_date_of_birth'             => 'Date',
      'com4_weight'                    => 'Number',
      'com4_phone'                     => 'Text',
      'com4_comment'                   => 'Text',
      'lodging_name'                   => 'Text',
      'lodging_phone'                  => 'Text',
      'facility_name'                  => 'Text',
      'facility_phone'                 => 'Text',
      'facility_phone_comment'         => 'Text',
      'req_language_spoken'            => 'Text',
      'best_contact'                   => 'Text',
      'emergency_name'                 => 'Text',
      'emergency_phone1'               => 'Text',
      'emergency_phone2'               => 'Text',
      'emergency_phone1_comment'       => 'Text',
      'emergency_phone2_comment'       => 'Text',
      'comment'                        => 'Text',
      'processed_date'                 => 'Date',
      'session_id'                     => 'Number',
      'ip_address'                     => 'Text',
      'pass_fax_phone1'                => 'Text',
      'pass_fax_comment1'              => 'Text',
      'guar_first_name'                => 'Text',
      'guar_last_name'                 => 'Text',
      'guar_address1'                  => 'Text',
      'guar_address2'                  => 'Text',
      'guar_city'                      => 'Text',
      'guar_state'                     => 'Text',
      'guar_zipcode'                   => 'Text',
      'guar_day_phone'                 => 'Text',
      'guar_day_comment'               => 'Text',
      'guar_eve_phone'                 => 'Text',
      'guar_eve_comment'               => 'Text',
      'guar_fax_phone1'                => 'Text',
      'guar_fax_comment1'              => 'Text',
      'guar_mobile_phone'              => 'Text',
      'guar_mobile_comment'            => 'Text',
      'guar_pager_phone'               => 'Text',
      'guar_pager_comment'             => 'Text',
      'guar_other_phone'               => 'Text',
      'guar_other_comment'             => 'Text',
      'guar_guar_email'                => 'Text',
      'req_fax_phone1'                 => 'Text',
      'req_fax_comment1'               => 'Text',
      'pass_english'                   => 'Number',
      'pass_language'                  => 'Text',
      'appt_time'                      => 'Text',
      'requester_id'                   => 'Number',
      'passenger_id'                   => 'Number',
      'mission_id'                     => 'Number',
      'treating_email'                 => 'Text',
      'pass_height'                    => 'Number',
      'return_time'                    => 'Text',
      'pass_oxygen'                    => 'Number',
      'pass_medical'                   => 'Number',
      'referral_source_id'             => 'Number',
      'follow_up_contact_name'         => 'Text',
      'follow_up_contact_phone'        => 'Text',
      'follow_up_email'                => 'Text',
      'miss_req_originator_afa_org_id' => 'Number',
      'afa_org_id'                     => 'Number',
      'afa_org_mission_id'             => 'Number',
      'mission_request_type'           => 'Number',
      'last_page_processed'            => 'Number',
      'guardian_middle_name'           => 'Text',
      'guardian_nickname'              => 'Text',
      'guardian_pager_email'           => 'Text',
      'guardian_secondary_email'       => 'Text',
      'guardian_suffix'                => 'Text',
      'guardian_title'                 => 'Text',
      'guardian_veteran'               => 'Number',
      'pass_gender'                    => 'Text',
      'pass_middle_name'               => 'Text',
      'pass_nickname'                  => 'Text',
      'pass_pager_email'               => 'Text',
      'pass_secondary_email'           => 'Text',
      'pass_suffix'                    => 'Text',
      'pass_veteran'                   => 'Number',
      'req_middle_name'                => 'Text',
      'req_nickname'                   => 'Text',
      'req_pager_email'                => 'Text',
      'req_secondary_email'            => 'Text',
      'req_suffix'                     => 'Text',
      'req_veteran'                    => 'Number',
      'lodging_phone_comment'          => 'Text',
      'req_gender'                     => 'Text',
      'guardian_gender'                => 'Text',
      'agency_position'                => 'Text',
    );
  }
}
