<?php

require_once(sfConfig::get('sf_lib_dir').'/filter/base/BaseFormFilterPropel.class.php');

/**
 * Application filter form base class.
 *
 * @package    angelflight
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormFilterGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseApplicationFormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'ccard_number'                 => new sfWidgetFormFilterInput(),
      'ccard_code'                   => new sfWidgetFormFilterInput(),
      'ccard_expire'                 => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'member_id'                    => new sfWidgetFormPropelChoice(array('model' => 'Member', 'add_empty' => true)),
      'renewal'                      => new sfWidgetFormFilterInput(),
      'date'                         => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => false)),
      'vocation_class_id'            => new sfWidgetFormPropelChoice(array('model' => 'VocationClass', 'add_empty' => true)),
      'company'                      => new sfWidgetFormFilterInput(),
      'license_type'                 => new sfWidgetFormFilterInput(),
      'ifr'                          => new sfWidgetFormFilterInput(),
      'multi_engine'                 => new sfWidgetFormFilterInput(),
      'se_instructor'                => new sfWidgetFormFilterInput(),
      'me_instructor'                => new sfWidgetFormFilterInput(),
      'other_ratings'                => new sfWidgetFormFilterInput(),
      'total_hours'                  => new sfWidgetFormFilterInput(),
      'fbo'                          => new sfWidgetFormFilterInput(),
      'mission_orientation'          => new sfWidgetFormFilterInput(),
      'mission_coordination'         => new sfWidgetFormFilterInput(),
      'pilot_recruitment'            => new sfWidgetFormFilterInput(),
      'fund_raising'                 => new sfWidgetFormFilterInput(),
      'celebrity_contacts'           => new sfWidgetFormFilterInput(),
      'hospital_outreach'            => new sfWidgetFormFilterInput(),
      'member_meetings'              => new sfWidgetFormFilterInput(),
      'media_relations'              => new sfWidgetFormFilterInput(),
      'telephone_work'               => new sfWidgetFormFilterInput(),
      'computers'                    => new sfWidgetFormFilterInput(),
      'clerical'                     => new sfWidgetFormFilterInput(),
      'publicity'                    => new sfWidgetFormFilterInput(),
      'writing'                      => new sfWidgetFormFilterInput(),
      'speakers_bureau'              => new sfWidgetFormFilterInput(),
      'executive_board'              => new sfWidgetFormFilterInput(),
      'wing_team'                    => new sfWidgetFormFilterInput(),
      'graphic_arts'                 => new sfWidgetFormFilterInput(),
      'other_volunteer'              => new sfWidgetFormFilterInput(),
      't_shirt_size'                 => new sfWidgetFormFilterInput(),
      'dues_amount_paid'             => new sfWidgetFormFilterInput(),
      'method_of_payment'            => new sfWidgetFormFilterInput(),
      'check_number'                 => new sfWidgetFormFilterInput(),
      'donation_amount_paid'         => new sfWidgetFormFilterInput(),
      'title'                        => new sfWidgetFormFilterInput(),
      'first_name'                   => new sfWidgetFormFilterInput(),
      'last_name'                    => new sfWidgetFormFilterInput(),
      'address1'                     => new sfWidgetFormFilterInput(),
      'address2'                     => new sfWidgetFormFilterInput(),
      'city'                         => new sfWidgetFormFilterInput(),
      'state'                        => new sfWidgetFormFilterInput(),
      'zipcode'                      => new sfWidgetFormFilterInput(),
      'day_phone'                    => new sfWidgetFormFilterInput(),
      'day_comment'                  => new sfWidgetFormFilterInput(),
      'eve_phone'                    => new sfWidgetFormFilterInput(),
      'eve_comment'                  => new sfWidgetFormFilterInput(),
      'mobile_phone'                 => new sfWidgetFormFilterInput(),
      'mobile_comment'               => new sfWidgetFormFilterInput(),
      'pager_phone'                  => new sfWidgetFormFilterInput(),
      'pager_comment'                => new sfWidgetFormFilterInput(),
      'fax_phone1'                   => new sfWidgetFormFilterInput(),
      'fax_comment1'                 => new sfWidgetFormFilterInput(),
      'fax_phone2'                   => new sfWidgetFormFilterInput(),
      'fax_comment2'                 => new sfWidgetFormFilterInput(),
      'other_phone'                  => new sfWidgetFormFilterInput(),
      'other_comment'                => new sfWidgetFormFilterInput(),
      'email'                        => new sfWidgetFormFilterInput(),
      'spouse_first_name'            => new sfWidgetFormFilterInput(),
      'spouse_last_name'             => new sfWidgetFormFilterInput(),
      'applicant_pilot'              => new sfWidgetFormFilterInput(),
      'languages_spoken'             => new sfWidgetFormFilterInput(),
      'home_base'                    => new sfWidgetFormFilterInput(),
      'secondary_home_bases'         => new sfWidgetFormFilterInput(),
      'aircraft_primary_id'          => new sfWidgetFormFilterInput(),
      'aircraft_primary_own'         => new sfWidgetFormFilterInput(),
      'aircraft_primary_ice'         => new sfWidgetFormFilterInput(),
      'aircraft_primary_seats'       => new sfWidgetFormFilterInput(),
      'aircraft_primary_n_number'    => new sfWidgetFormFilterInput(),
      'aircraft_secondary_id'        => new sfWidgetFormFilterInput(),
      'aircraft_secondary_own'       => new sfWidgetFormFilterInput(),
      'aircraft_secondary_ice'       => new sfWidgetFormFilterInput(),
      'aircraft_secondary_seats'     => new sfWidgetFormFilterInput(),
      'aircraft_secondary_n_number'  => new sfWidgetFormFilterInput(),
      'pilot_certificate'            => new sfWidgetFormFilterInput(),
      'medical_class'                => new sfWidgetFormFilterInput(),
      'ifr_hours'                    => new sfWidgetFormFilterInput(),
      'multi_hours'                  => new sfWidgetFormFilterInput(),
      'other_hours'                  => new sfWidgetFormFilterInput(),
      'date_of_birth'                => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'height'                       => new sfWidgetFormFilterInput(),
      'weight'                       => new sfWidgetFormFilterInput(),
      'availability_weekdays'        => new sfWidgetFormFilterInput(),
      'availability_weeknights'      => new sfWidgetFormFilterInput(),
      'availability_weekends'        => new sfWidgetFormFilterInput(),
      'availability_notice'          => new sfWidgetFormFilterInput(),
      'availability_last_minute'     => new sfWidgetFormFilterInput(),
      'availability_copilot'         => new sfWidgetFormFilterInput(),
      'affirmation_agreed'           => new sfWidgetFormFilterInput(),
      'insurance_agreed'             => new sfWidgetFormFilterInput(),
      'volunteer_interest'           => new sfWidgetFormFilterInput(),
      'company_position'             => new sfWidgetFormFilterInput(),
      'company_match_funds'          => new sfWidgetFormFilterInput(),
      'company_business_category_id' => new sfWidgetFormFilterInput(),
      'referral_source'              => new sfWidgetFormPropelChoice(array('model' => 'RefSource', 'add_empty' => true)),
      'premium_choice'               => new sfWidgetFormFilterInput(),
      'premium_size'                 => new sfWidgetFormFilterInput(),
      'ccard_approval_number'        => new sfWidgetFormFilterInput(),
      'ccard_error_code'             => new sfWidgetFormFilterInput(),
      'ccard_avs_result'             => new sfWidgetFormFilterInput(),
      'processed_date'               => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'event_planning'               => new sfWidgetFormFilterInput(),
      'web_internet'                 => new sfWidgetFormFilterInput(),
      'foundation_contacts'          => new sfWidgetFormFilterInput(),
      'aviation_contacts'            => new sfWidgetFormFilterInput(),
      'printing'                     => new sfWidgetFormFilterInput(),
      'member_aopa'                  => new sfWidgetFormFilterInput(),
      'member_kiwanis'               => new sfWidgetFormFilterInput(),
      'member_rotary'                => new sfWidgetFormFilterInput(),
      'member_lions'                 => new sfWidgetFormFilterInput(),
      'novapointe_id'                => new sfWidgetFormFilterInput(),
      'premium_ship_date'            => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'premium_ship_method'          => new sfWidgetFormFilterInput(),
      'premium_ship_cost'            => new sfWidgetFormFilterInput(),
      'premium_ship_tracking_number' => new sfWidgetFormFilterInput(),
      'spouse_pilot'                 => new sfWidgetFormFilterInput(),
      'applicant_copilot'            => new sfWidgetFormFilterInput(),
      'pager_email'                  => new sfWidgetFormFilterInput(),
      'member_99s'                   => new sfWidgetFormFilterInput(),
      'member_wia'                   => new sfWidgetFormFilterInput(),
      'mission_email_optin'          => new sfWidgetFormFilterInput(),
      'hseats_interest'              => new sfWidgetFormFilterInput(),
      'master_application_id'        => new sfWidgetFormFilterInput(),
      'master_member_id'             => new sfWidgetFormFilterInput(),
      'referral_source_other'        => new sfWidgetFormFilterInput(),
      'secondary_email'              => new sfWidgetFormFilterInput(),
      'payment_transaction_id'       => new sfWidgetFormFilterInput(),
      'aircraft_third_ice'           => new sfWidgetFormFilterInput(),
      'aircraft_third_id'            => new sfWidgetFormFilterInput(),
      'aircraft_third_n_number'      => new sfWidgetFormFilterInput(),
      'aircraft_third_own'           => new sfWidgetFormFilterInput(),
      'aircraft_third_seats'         => new sfWidgetFormFilterInput(),
      'drivers_license_number'       => new sfWidgetFormFilterInput(),
      'drivers_license_state'        => new sfWidgetFormFilterInput(),
      'emergency_contact_name'       => new sfWidgetFormFilterInput(),
      'emergency_contact_phone'      => new sfWidgetFormFilterInput(),
      'country'                      => new sfWidgetFormFilterInput(),
      'middle_name'                  => new sfWidgetFormFilterInput(),
      'suffix'                       => new sfWidgetFormFilterInput(),
      'nickname'                     => new sfWidgetFormFilterInput(),
      'veteran'                      => new sfWidgetFormFilterInput(),
      'gender'                       => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'ccard_number'                 => new sfValidatorPass(array('required' => false)),
      'ccard_code'                   => new sfValidatorPass(array('required' => false)),
      'ccard_expire'                 => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'member_id'                    => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Member', 'column' => 'id')),
      'renewal'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'date'                         => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'vocation_class_id'            => new sfValidatorPropelChoice(array('required' => false, 'model' => 'VocationClass', 'column' => 'id')),
      'company'                      => new sfValidatorPass(array('required' => false)),
      'license_type'                 => new sfValidatorPass(array('required' => false)),
      'ifr'                          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'multi_engine'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'se_instructor'                => new sfValidatorPass(array('required' => false)),
      'me_instructor'                => new sfValidatorPass(array('required' => false)),
      'other_ratings'                => new sfValidatorPass(array('required' => false)),
      'total_hours'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fbo'                          => new sfValidatorPass(array('required' => false)),
      'mission_orientation'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mission_coordination'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pilot_recruitment'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fund_raising'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'celebrity_contacts'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'hospital_outreach'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'member_meetings'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'media_relations'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'telephone_work'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'computers'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'clerical'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'publicity'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'writing'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'speakers_bureau'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'executive_board'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'wing_team'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'graphic_arts'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_volunteer'              => new sfValidatorPass(array('required' => false)),
      't_shirt_size'                 => new sfValidatorPass(array('required' => false)),
      'dues_amount_paid'             => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'method_of_payment'            => new sfValidatorPass(array('required' => false)),
      'check_number'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'donation_amount_paid'         => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'title'                        => new sfValidatorPass(array('required' => false)),
      'first_name'                   => new sfValidatorPass(array('required' => false)),
      'last_name'                    => new sfValidatorPass(array('required' => false)),
      'address1'                     => new sfValidatorPass(array('required' => false)),
      'address2'                     => new sfValidatorPass(array('required' => false)),
      'city'                         => new sfValidatorPass(array('required' => false)),
      'state'                        => new sfValidatorPass(array('required' => false)),
      'zipcode'                      => new sfValidatorPass(array('required' => false)),
      'day_phone'                    => new sfValidatorPass(array('required' => false)),
      'day_comment'                  => new sfValidatorPass(array('required' => false)),
      'eve_phone'                    => new sfValidatorPass(array('required' => false)),
      'eve_comment'                  => new sfValidatorPass(array('required' => false)),
      'mobile_phone'                 => new sfValidatorPass(array('required' => false)),
      'mobile_comment'               => new sfValidatorPass(array('required' => false)),
      'pager_phone'                  => new sfValidatorPass(array('required' => false)),
      'pager_comment'                => new sfValidatorPass(array('required' => false)),
      'fax_phone1'                   => new sfValidatorPass(array('required' => false)),
      'fax_comment1'                 => new sfValidatorPass(array('required' => false)),
      'fax_phone2'                   => new sfValidatorPass(array('required' => false)),
      'fax_comment2'                 => new sfValidatorPass(array('required' => false)),
      'other_phone'                  => new sfValidatorPass(array('required' => false)),
      'other_comment'                => new sfValidatorPass(array('required' => false)),
      'email'                        => new sfValidatorPass(array('required' => false)),
      'spouse_first_name'            => new sfValidatorPass(array('required' => false)),
      'spouse_last_name'             => new sfValidatorPass(array('required' => false)),
      'applicant_pilot'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'languages_spoken'             => new sfValidatorPass(array('required' => false)),
      'home_base'                    => new sfValidatorPass(array('required' => false)),
      'secondary_home_bases'         => new sfValidatorPass(array('required' => false)),
      'aircraft_primary_id'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_primary_own'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_primary_ice'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_primary_seats'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_primary_n_number'    => new sfValidatorPass(array('required' => false)),
      'aircraft_secondary_id'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_secondary_own'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_secondary_ice'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_secondary_seats'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_secondary_n_number'  => new sfValidatorPass(array('required' => false)),
      'pilot_certificate'            => new sfValidatorPass(array('required' => false)),
      'medical_class'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ifr_hours'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'multi_hours'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'other_hours'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'date_of_birth'                => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'height'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'weight'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'availability_weekdays'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'availability_weeknights'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'availability_weekends'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'availability_notice'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'availability_last_minute'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'availability_copilot'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'affirmation_agreed'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'insurance_agreed'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'volunteer_interest'           => new sfValidatorPass(array('required' => false)),
      'company_position'             => new sfValidatorPass(array('required' => false)),
      'company_match_funds'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'company_business_category_id' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'referral_source'              => new sfValidatorPropelChoice(array('required' => false, 'model' => 'RefSource', 'column' => 'id')),
      'premium_choice'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'premium_size'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ccard_approval_number'        => new sfValidatorPass(array('required' => false)),
      'ccard_error_code'             => new sfValidatorPass(array('required' => false)),
      'ccard_avs_result'             => new sfValidatorPass(array('required' => false)),
      'processed_date'               => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'event_planning'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'web_internet'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'foundation_contacts'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aviation_contacts'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'printing'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'member_aopa'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'member_kiwanis'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'member_rotary'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'member_lions'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'novapointe_id'                => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'premium_ship_date'            => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'premium_ship_method'          => new sfValidatorPass(array('required' => false)),
      'premium_ship_cost'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'premium_ship_tracking_number' => new sfValidatorPass(array('required' => false)),
      'spouse_pilot'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'applicant_copilot'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pager_email'                  => new sfValidatorPass(array('required' => false)),
      'member_99s'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'member_wia'                   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'mission_email_optin'          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'hseats_interest'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'master_application_id'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'master_member_id'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'referral_source_other'        => new sfValidatorPass(array('required' => false)),
      'secondary_email'              => new sfValidatorPass(array('required' => false)),
      'payment_transaction_id'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_third_ice'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_third_id'            => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_third_n_number'      => new sfValidatorPass(array('required' => false)),
      'aircraft_third_own'           => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraft_third_seats'         => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'drivers_license_number'       => new sfValidatorPass(array('required' => false)),
      'drivers_license_state'        => new sfValidatorPass(array('required' => false)),
      'emergency_contact_name'       => new sfValidatorPass(array('required' => false)),
      'emergency_contact_phone'      => new sfValidatorPass(array('required' => false)),
      'country'                      => new sfValidatorPass(array('required' => false)),
      'middle_name'                  => new sfValidatorPass(array('required' => false)),
      'suffix'                       => new sfValidatorPass(array('required' => false)),
      'nickname'                     => new sfValidatorPass(array('required' => false)),
      'veteran'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'gender'                       => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('application_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Application';
  }

  public function getFields()
  {
    return array(
      'id'                           => 'Number',
      'ccard_number'                 => 'Text',
      'ccard_code'                   => 'Text',
      'ccard_expire'                 => 'Date',
      'member_id'                    => 'ForeignKey',
      'renewal'                      => 'Number',
      'date'                         => 'Date',
      'vocation_class_id'            => 'ForeignKey',
      'company'                      => 'Text',
      'license_type'                 => 'Text',
      'ifr'                          => 'Number',
      'multi_engine'                 => 'Number',
      'se_instructor'                => 'Text',
      'me_instructor'                => 'Text',
      'other_ratings'                => 'Text',
      'total_hours'                  => 'Number',
      'fbo'                          => 'Text',
      'mission_orientation'          => 'Number',
      'mission_coordination'         => 'Number',
      'pilot_recruitment'            => 'Number',
      'fund_raising'                 => 'Number',
      'celebrity_contacts'           => 'Number',
      'hospital_outreach'            => 'Number',
      'member_meetings'              => 'Number',
      'media_relations'              => 'Number',
      'telephone_work'               => 'Number',
      'computers'                    => 'Number',
      'clerical'                     => 'Number',
      'publicity'                    => 'Number',
      'writing'                      => 'Number',
      'speakers_bureau'              => 'Number',
      'executive_board'              => 'Number',
      'wing_team'                    => 'Number',
      'graphic_arts'                 => 'Number',
      'other_volunteer'              => 'Text',
      't_shirt_size'                 => 'Text',
      'dues_amount_paid'             => 'Number',
      'method_of_payment'            => 'Text',
      'check_number'                 => 'Number',
      'donation_amount_paid'         => 'Number',
      'title'                        => 'Text',
      'first_name'                   => 'Text',
      'last_name'                    => 'Text',
      'address1'                     => 'Text',
      'address2'                     => 'Text',
      'city'                         => 'Text',
      'state'                        => 'Text',
      'zipcode'                      => 'Text',
      'day_phone'                    => 'Text',
      'day_comment'                  => 'Text',
      'eve_phone'                    => 'Text',
      'eve_comment'                  => 'Text',
      'mobile_phone'                 => 'Text',
      'mobile_comment'               => 'Text',
      'pager_phone'                  => 'Text',
      'pager_comment'                => 'Text',
      'fax_phone1'                   => 'Text',
      'fax_comment1'                 => 'Text',
      'fax_phone2'                   => 'Text',
      'fax_comment2'                 => 'Text',
      'other_phone'                  => 'Text',
      'other_comment'                => 'Text',
      'email'                        => 'Text',
      'spouse_first_name'            => 'Text',
      'spouse_last_name'             => 'Text',
      'applicant_pilot'              => 'Number',
      'languages_spoken'             => 'Text',
      'home_base'                    => 'Text',
      'secondary_home_bases'         => 'Text',
      'aircraft_primary_id'          => 'Number',
      'aircraft_primary_own'         => 'Number',
      'aircraft_primary_ice'         => 'Number',
      'aircraft_primary_seats'       => 'Number',
      'aircraft_primary_n_number'    => 'Text',
      'aircraft_secondary_id'        => 'Number',
      'aircraft_secondary_own'       => 'Number',
      'aircraft_secondary_ice'       => 'Number',
      'aircraft_secondary_seats'     => 'Number',
      'aircraft_secondary_n_number'  => 'Text',
      'pilot_certificate'            => 'Text',
      'medical_class'                => 'Number',
      'ifr_hours'                    => 'Number',
      'multi_hours'                  => 'Number',
      'other_hours'                  => 'Number',
      'date_of_birth'                => 'Date',
      'height'                       => 'Number',
      'weight'                       => 'Number',
      'availability_weekdays'        => 'Number',
      'availability_weeknights'      => 'Number',
      'availability_weekends'        => 'Number',
      'availability_notice'          => 'Number',
      'availability_last_minute'     => 'Number',
      'availability_copilot'         => 'Number',
      'affirmation_agreed'           => 'Number',
      'insurance_agreed'             => 'Number',
      'volunteer_interest'           => 'Text',
      'company_position'             => 'Text',
      'company_match_funds'          => 'Number',
      'company_business_category_id' => 'Number',
      'referral_source'              => 'ForeignKey',
      'premium_choice'               => 'Number',
      'premium_size'                 => 'Number',
      'ccard_approval_number'        => 'Text',
      'ccard_error_code'             => 'Text',
      'ccard_avs_result'             => 'Text',
      'processed_date'               => 'Date',
      'event_planning'               => 'Number',
      'web_internet'                 => 'Number',
      'foundation_contacts'          => 'Number',
      'aviation_contacts'            => 'Number',
      'printing'                     => 'Number',
      'member_aopa'                  => 'Number',
      'member_kiwanis'               => 'Number',
      'member_rotary'                => 'Number',
      'member_lions'                 => 'Number',
      'novapointe_id'                => 'Number',
      'premium_ship_date'            => 'Date',
      'premium_ship_method'          => 'Text',
      'premium_ship_cost'            => 'Number',
      'premium_ship_tracking_number' => 'Text',
      'spouse_pilot'                 => 'Number',
      'applicant_copilot'            => 'Number',
      'pager_email'                  => 'Text',
      'member_99s'                   => 'Number',
      'member_wia'                   => 'Number',
      'mission_email_optin'          => 'Number',
      'hseats_interest'              => 'Number',
      'master_application_id'        => 'Number',
      'master_member_id'             => 'Number',
      'referral_source_other'        => 'Text',
      'secondary_email'              => 'Text',
      'payment_transaction_id'       => 'Number',
      'aircraft_third_ice'           => 'Number',
      'aircraft_third_id'            => 'Number',
      'aircraft_third_n_number'      => 'Text',
      'aircraft_third_own'           => 'Number',
      'aircraft_third_seats'         => 'Number',
      'drivers_license_number'       => 'Text',
      'drivers_license_state'        => 'Text',
      'emergency_contact_name'       => 'Text',
      'emergency_contact_phone'      => 'Text',
      'country'                      => 'Text',
      'middle_name'                  => 'Text',
      'suffix'                       => 'Text',
      'nickname'                     => 'Text',
      'veteran'                      => 'Number',
      'gender'                       => 'Text',
    );
  }
}
