<?php

require_once(sfConfig::get('sf_lib_dir').'/filter/base/BaseFormFilterPropel.class.php');

/**
 * RpMissionItinerary filter form base class.
 *
 * @package    angelflight
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormFilterGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseRpMissionItineraryFormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'Now'                              => new sfWidgetFormFilterInput(),
      'missionID'                        => new sfWidgetFormFilterInput(),
      'externalID'                       => new sfWidgetFormFilterInput(),
      'missionTypeID'                    => new sfWidgetFormFilterInput(),
      'missionDate'                      => new sfWidgetFormFilterInput(),
      'apptDate'                         => new sfWidgetFormFilterDate(array('from_date' => new sfWidgetFormDate(), 'to_date' => new sfWidgetFormDate(), 'with_empty' => true)),
      'flightTime'                       => new sfWidgetFormFilterInput(),
      'releasingPhysician'               => new sfWidgetFormFilterInput(),
      'releasingPhone'                   => new sfWidgetFormFilterInput(),
      'releasingFax'                     => new sfWidgetFormFilterInput(),
      'releasingFaxComment'              => new sfWidgetFormFilterInput(),
      'releasingEmail'                   => new sfWidgetFormFilterInput(),
      'lodging'                          => new sfWidgetFormFilterInput(),
      'lodgingPhone'                     => new sfWidgetFormFilterInput(),
      'lodging_phone_comment'            => new sfWidgetFormFilterInput(),
      'facilityName'                     => new sfWidgetFormFilterInput(),
      'facilityPhone'                    => new sfWidgetFormFilterInput(),
      'facilityPhoneComment'             => new sfWidgetFormFilterInput(),
      'publicConsiderations'             => new sfWidgetFormFilterInput(),
      'privateConsiderations'            => new sfWidgetFormFilterInput(),
      'illness'                          => new sfWidgetFormFilterInput(),
      'groundTransportationComment'      => new sfWidgetFormFilterInput(),
      'treatingPhysician'                => new sfWidgetFormFilterInput(),
      'treatingPhone'                    => new sfWidgetFormFilterInput(),
      'treatingFax'                      => new sfWidgetFormFilterInput(),
      'treatingFaxComment'               => new sfWidgetFormFilterInput(),
      'treatingEmail'                    => new sfWidgetFormFilterInput(),
      'languageSpoken'                   => new sfWidgetFormFilterInput(),
      'bestContactMethod'                => new sfWidgetFormFilterInput(),
      'emergencyContactName'             => new sfWidgetFormFilterInput(),
      'emergencyContactPrimaryPhone'     => new sfWidgetFormFilterInput(),
      'emergencyContactSecondaryPhone'   => new sfWidgetFormFilterInput(),
      'emergencyContactPrimaryComment'   => new sfWidgetFormFilterInput(),
      'emergencyContactSecondaryComment' => new sfWidgetFormFilterInput(),
      'passFirstName'                    => new sfWidgetFormFilterInput(),
      'passLastName'                     => new sfWidgetFormFilterInput(),
      'passCity'                         => new sfWidgetFormFilterInput(),
      'passState'                        => new sfWidgetFormFilterInput(),
      'passZipcode'                      => new sfWidgetFormFilterInput(),
      'passAge'                          => new sfWidgetFormFilterInput(),
      'passWeight'                       => new sfWidgetFormFilterInput(),
      'passDayPhone'                     => new sfWidgetFormFilterInput(),
      'passDayComment'                   => new sfWidgetFormFilterInput(),
      'passEvePhone'                     => new sfWidgetFormFilterInput(),
      'passEveComment'                   => new sfWidgetFormFilterInput(),
      'passPagerPhone'                   => new sfWidgetFormFilterInput(),
      'passPagerComment'                 => new sfWidgetFormFilterInput(),
      'passMobilePhone'                  => new sfWidgetFormFilterInput(),
      'passMobileComment'                => new sfWidgetFormFilterInput(),
      'passOtherPhone'                   => new sfWidgetFormFilterInput(),
      'passOtherComment'                 => new sfWidgetFormFilterInput(),
      'passFaxPhone1'                    => new sfWidgetFormFilterInput(),
      'passFax1Comment'                  => new sfWidgetFormFilterInput(),
      'passEmail'                        => new sfWidgetFormFilterInput(),
      'passAddressOne'                   => new sfWidgetFormFilterInput(),
      'passAddressTwo'                   => new sfWidgetFormFilterInput(),
      'comment'                          => new sfWidgetFormFilterInput(),
      'legNumber'                        => new sfWidgetFormFilterInput(),
      'passOnBoard'                      => new sfWidgetFormFilterInput(),
      'baggageWeight'                    => new sfWidgetFormFilterInput(),
      'baggageDesc'                      => new sfWidgetFormFilterInput(),
      'publicCNote'                      => new sfWidgetFormFilterInput(),
      'privateCNote'                     => new sfWidgetFormFilterInput(),
      'copilotWanted'                    => new sfWidgetFormFilterInput(),
      'fromAirportIdent'                 => new sfWidgetFormFilterInput(),
      'fromAirportName'                  => new sfWidgetFormFilterInput(),
      'fromAirportCity'                  => new sfWidgetFormFilterInput(),
      'fromAirportState'                 => new sfWidgetFormFilterInput(),
      'fromAirportGMTOffset'             => new sfWidgetFormFilterInput(),
      'fromAirportDSTOffset'             => new sfWidgetFormFilterInput(),
      'toAirportIdent'                   => new sfWidgetFormFilterInput(),
      'toAirportName'                    => new sfWidgetFormFilterInput(),
      'toAirportCity'                    => new sfWidgetFormFilterInput(),
      'toAirportState'                   => new sfWidgetFormFilterInput(),
      'toAirportGMTOffset'               => new sfWidgetFormFilterInput(),
      'toAirportDSTOffset'               => new sfWidgetFormFilterInput(),
      'pilotFirstName'                   => new sfWidgetFormFilterInput(),
      'pilotLastName'                    => new sfWidgetFormFilterInput(),
      'pilotDayPhone'                    => new sfWidgetFormFilterInput(),
      'pilotDayComment'                  => new sfWidgetFormFilterInput(),
      'pilotEvePhone'                    => new sfWidgetFormFilterInput(),
      'pilotEveComment'                  => new sfWidgetFormFilterInput(),
      'pilotFaxPhone'                    => new sfWidgetFormFilterInput(),
      'pilotFaxComment'                  => new sfWidgetFormFilterInput(),
      'pilotMobilePhone'                 => new sfWidgetFormFilterInput(),
      'pilotMobileComment'               => new sfWidgetFormFilterInput(),
      'pilotPagerPhone'                  => new sfWidgetFormFilterInput(),
      'pilotPagerComment'                => new sfWidgetFormFilterInput(),
      'pilotOtherPhone'                  => new sfWidgetFormFilterInput(),
      'pilotOtherComment'                => new sfWidgetFormFilterInput(),
      'pilotEmail'                       => new sfWidgetFormFilterInput(),
      'coPilotFirstName'                 => new sfWidgetFormFilterInput(),
      'coPilotLastName'                  => new sfWidgetFormFilterInput(),
      'CoPilotDayPhone'                  => new sfWidgetFormFilterInput(),
      'coPilotDayComment'                => new sfWidgetFormFilterInput(),
      'CoPilotEvePhone'                  => new sfWidgetFormFilterInput(),
      'coPilotEveComment'                => new sfWidgetFormFilterInput(),
      'CoPilotMobilePhone'               => new sfWidgetFormFilterInput(),
      'coPilotMobileComment'             => new sfWidgetFormFilterInput(),
      'CoPilotPagerPhone'                => new sfWidgetFormFilterInput(),
      'coPilotPagerComment'              => new sfWidgetFormFilterInput(),
      'CoPilotOtherPhone'                => new sfWidgetFormFilterInput(),
      'coPilotOtherComment'              => new sfWidgetFormFilterInput(),
      'CoPilotFaxPhone'                  => new sfWidgetFormFilterInput(),
      'coPilotFaxComment'                => new sfWidgetFormFilterInput(),
      'coPilotEmail'                     => new sfWidgetFormFilterInput(),
      'buPilotFirstName'                 => new sfWidgetFormFilterInput(),
      'buPilotLastName'                  => new sfWidgetFormFilterInput(),
      'buPilotDayPhone'                  => new sfWidgetFormFilterInput(),
      'buPilotDayComment'                => new sfWidgetFormFilterInput(),
      'buPilotEvePhone'                  => new sfWidgetFormFilterInput(),
      'buPilotEveComment'                => new sfWidgetFormFilterInput(),
      'buPilotMobilePhone'               => new sfWidgetFormFilterInput(),
      'buPilotMobileComment'             => new sfWidgetFormFilterInput(),
      'buPilotPagerPhone'                => new sfWidgetFormFilterInput(),
      'buPilotPagerComment'              => new sfWidgetFormFilterInput(),
      'buPilotOtherPhone'                => new sfWidgetFormFilterInput(),
      'buPilotOtherComment'              => new sfWidgetFormFilterInput(),
      'buPilotFaxPhone'                  => new sfWidgetFormFilterInput(),
      'buPilotFaxComment'                => new sfWidgetFormFilterInput(),
      'buPilotEmail'                     => new sfWidgetFormFilterInput(),
      'coordFirstName'                   => new sfWidgetFormFilterInput(),
      'coordLastName'                    => new sfWidgetFormFilterInput(),
      'coordDayPhone'                    => new sfWidgetFormFilterInput(),
      'coordDayComment'                  => new sfWidgetFormFilterInput(),
      'coordEvePhone'                    => new sfWidgetFormFilterInput(),
      'coordEveComment'                  => new sfWidgetFormFilterInput(),
      'coordMobilePhone'                 => new sfWidgetFormFilterInput(),
      'coordMobileComment'               => new sfWidgetFormFilterInput(),
      'coordPagerPhone'                  => new sfWidgetFormFilterInput(),
      'coordPagerComment'                => new sfWidgetFormFilterInput(),
      'coordOtherPhone'                  => new sfWidgetFormFilterInput(),
      'coordOtherComment'                => new sfWidgetFormFilterInput(),
      'coordFaxPhone'                    => new sfWidgetFormFilterInput(),
      'coordFaxComment'                  => new sfWidgetFormFilterInput(),
      'coordEmail'                       => new sfWidgetFormFilterInput(),
      'requesterName'                    => new sfWidgetFormFilterInput(),
      'reqFirstName'                     => new sfWidgetFormFilterInput(),
      'reqLastName'                      => new sfWidgetFormFilterInput(),
      'reqDayPhone'                      => new sfWidgetFormFilterInput(),
      'reqEvePhone'                      => new sfWidgetFormFilterInput(),
      'reqMobilePhone'                   => new sfWidgetFormFilterInput(),
      'reqPagerPhone'                    => new sfWidgetFormFilterInput(),
      'reqOtherPhone'                    => new sfWidgetFormFilterInput(),
      'reqFaxPhone'                      => new sfWidgetFormFilterInput(),
      'reqDayComment'                    => new sfWidgetFormFilterInput(),
      'reqEveComment'                    => new sfWidgetFormFilterInput(),
      'reqPagerComment'                  => new sfWidgetFormFilterInput(),
      'reqMobileComment'                 => new sfWidgetFormFilterInput(),
      'reqFaxComment'                    => new sfWidgetFormFilterInput(),
      'reqOtherComment'                  => new sfWidgetFormFilterInput(),
      'reqEmail'                         => new sfWidgetFormFilterInput(),
      'companionName'                    => new sfWidgetFormFilterInput(),
      'companionRelationship'            => new sfWidgetFormFilterInput(),
      'companionDOB'                     => new sfWidgetFormFilterInput(),
      'companionAge'                     => new sfWidgetFormFilterInput(),
      'companionWeight'                  => new sfWidgetFormFilterInput(),
      'companionPhone'                   => new sfWidgetFormFilterInput(),
      'companionPhoneComment'            => new sfWidgetFormFilterInput(),
      'pilotName'                        => new sfWidgetFormFilterInput(),
      'afaDayPhone'                      => new sfWidgetFormFilterInput(),
      'afaNightPhone'                    => new sfWidgetFormFilterInput(),
      'afaFaxPhone'                      => new sfWidgetFormFilterInput(),
      'afaPilotMobilePhone'              => new sfWidgetFormFilterInput(),
      'afaAircraft'                      => new sfWidgetFormFilterInput(),
      'afaNNumber'                       => new sfWidgetFormFilterInput(),
      'aircraftColor'                    => new sfWidgetFormFilterInput(),
      'etd'                              => new sfWidgetFormFilterInput(),
      'eta'                              => new sfWidgetFormFilterInput(),
      'afaOrgName'                       => new sfWidgetFormFilterInput(),
      'afaOrgPhone'                      => new sfWidgetFormFilterInput(),
      'fboName'                          => new sfWidgetFormFilterInput(),
      'fboPhone'                         => new sfWidgetFormFilterInput(),
      'fboFax'                           => new sfWidgetFormFilterInput(),
      'fboFuelDiscount'                  => new sfWidgetFormFilterInput(),
      'fboAirportIdent'                  => new sfWidgetFormFilterInput(),
      'aircraftSeats'                    => new sfWidgetFormFilterInput(),
      'aircraftNNumber'                  => new sfWidgetFormFilterInput(),
      'aircraftKnownIce'                 => new sfWidgetFormFilterInput(),
      'aircraftMake'                     => new sfWidgetFormFilterInput(),
      'aircraftModel'                    => new sfWidgetFormFilterInput(),
      'campName'                         => new sfWidgetFormFilterInput(),
      'campPhone'                        => new sfWidgetFormFilterInput(),
      'campPhoneComment'                 => new sfWidgetFormFilterInput(),
      'campLodgingName'                  => new sfWidgetFormFilterInput(),
      'campLodgingPhone'                 => new sfWidgetFormFilterInput(),
      'campLodgingPhoneComment'          => new sfWidgetFormFilterInput(),
      'campComment'                      => new sfWidgetFormFilterInput(),
      'flightInformation'                => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'Now'                              => new sfValidatorPass(array('required' => false)),
      'missionID'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'externalID'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'missionTypeID'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'missionDate'                      => new sfValidatorPass(array('required' => false)),
      'apptDate'                         => new sfValidatorDateRange(array('required' => false, 'from_date' => new sfValidatorDate(array('required' => false)), 'to_date' => new sfValidatorDate(array('required' => false)))),
      'flightTime'                       => new sfValidatorPass(array('required' => false)),
      'releasingPhysician'               => new sfValidatorPass(array('required' => false)),
      'releasingPhone'                   => new sfValidatorPass(array('required' => false)),
      'releasingFax'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'releasingFaxComment'              => new sfValidatorPass(array('required' => false)),
      'releasingEmail'                   => new sfValidatorPass(array('required' => false)),
      'lodging'                          => new sfValidatorPass(array('required' => false)),
      'lodgingPhone'                     => new sfValidatorPass(array('required' => false)),
      'lodging_phone_comment'            => new sfValidatorPass(array('required' => false)),
      'facilityName'                     => new sfValidatorPass(array('required' => false)),
      'facilityPhone'                    => new sfValidatorPass(array('required' => false)),
      'facilityPhoneComment'             => new sfValidatorPass(array('required' => false)),
      'publicConsiderations'             => new sfValidatorPass(array('required' => false)),
      'privateConsiderations'            => new sfValidatorPass(array('required' => false)),
      'illness'                          => new sfValidatorPass(array('required' => false)),
      'groundTransportationComment'      => new sfValidatorPass(array('required' => false)),
      'treatingPhysician'                => new sfValidatorPass(array('required' => false)),
      'treatingPhone'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'treatingFax'                      => new sfValidatorPass(array('required' => false)),
      'treatingFaxComment'               => new sfValidatorPass(array('required' => false)),
      'treatingEmail'                    => new sfValidatorPass(array('required' => false)),
      'languageSpoken'                   => new sfValidatorPass(array('required' => false)),
      'bestContactMethod'                => new sfValidatorPass(array('required' => false)),
      'emergencyContactName'             => new sfValidatorPass(array('required' => false)),
      'emergencyContactPrimaryPhone'     => new sfValidatorPass(array('required' => false)),
      'emergencyContactSecondaryPhone'   => new sfValidatorPass(array('required' => false)),
      'emergencyContactPrimaryComment'   => new sfValidatorPass(array('required' => false)),
      'emergencyContactSecondaryComment' => new sfValidatorPass(array('required' => false)),
      'passFirstName'                    => new sfValidatorPass(array('required' => false)),
      'passLastName'                     => new sfValidatorPass(array('required' => false)),
      'passCity'                         => new sfValidatorPass(array('required' => false)),
      'passState'                        => new sfValidatorPass(array('required' => false)),
      'passZipcode'                      => new sfValidatorPass(array('required' => false)),
      'passAge'                          => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'passWeight'                       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'passDayPhone'                     => new sfValidatorPass(array('required' => false)),
      'passDayComment'                   => new sfValidatorPass(array('required' => false)),
      'passEvePhone'                     => new sfValidatorPass(array('required' => false)),
      'passEveComment'                   => new sfValidatorPass(array('required' => false)),
      'passPagerPhone'                   => new sfValidatorPass(array('required' => false)),
      'passPagerComment'                 => new sfValidatorPass(array('required' => false)),
      'passMobilePhone'                  => new sfValidatorPass(array('required' => false)),
      'passMobileComment'                => new sfValidatorPass(array('required' => false)),
      'passOtherPhone'                   => new sfValidatorPass(array('required' => false)),
      'passOtherComment'                 => new sfValidatorPass(array('required' => false)),
      'passFaxPhone1'                    => new sfValidatorPass(array('required' => false)),
      'passFax1Comment'                  => new sfValidatorPass(array('required' => false)),
      'passEmail'                        => new sfValidatorPass(array('required' => false)),
      'passAddressOne'                   => new sfValidatorPass(array('required' => false)),
      'passAddressTwo'                   => new sfValidatorPass(array('required' => false)),
      'comment'                          => new sfValidatorPass(array('required' => false)),
      'legNumber'                        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'passOnBoard'                      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'baggageWeight'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'baggageDesc'                      => new sfValidatorPass(array('required' => false)),
      'publicCNote'                      => new sfValidatorPass(array('required' => false)),
      'privateCNote'                     => new sfValidatorPass(array('required' => false)),
      'copilotWanted'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fromAirportIdent'                 => new sfValidatorPass(array('required' => false)),
      'fromAirportName'                  => new sfValidatorPass(array('required' => false)),
      'fromAirportCity'                  => new sfValidatorPass(array('required' => false)),
      'fromAirportState'                 => new sfValidatorPass(array('required' => false)),
      'fromAirportGMTOffset'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fromAirportDSTOffset'             => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'toAirportIdent'                   => new sfValidatorPass(array('required' => false)),
      'toAirportName'                    => new sfValidatorPass(array('required' => false)),
      'toAirportCity'                    => new sfValidatorPass(array('required' => false)),
      'toAirportState'                   => new sfValidatorPass(array('required' => false)),
      'toAirportGMTOffset'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'toAirportDSTOffset'               => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pilotFirstName'                   => new sfValidatorPass(array('required' => false)),
      'pilotLastName'                    => new sfValidatorPass(array('required' => false)),
      'pilotDayPhone'                    => new sfValidatorPass(array('required' => false)),
      'pilotDayComment'                  => new sfValidatorPass(array('required' => false)),
      'pilotEvePhone'                    => new sfValidatorPass(array('required' => false)),
      'pilotEveComment'                  => new sfValidatorPass(array('required' => false)),
      'pilotFaxPhone'                    => new sfValidatorPass(array('required' => false)),
      'pilotFaxComment'                  => new sfValidatorPass(array('required' => false)),
      'pilotMobilePhone'                 => new sfValidatorPass(array('required' => false)),
      'pilotMobileComment'               => new sfValidatorPass(array('required' => false)),
      'pilotPagerPhone'                  => new sfValidatorPass(array('required' => false)),
      'pilotPagerComment'                => new sfValidatorPass(array('required' => false)),
      'pilotOtherPhone'                  => new sfValidatorPass(array('required' => false)),
      'pilotOtherComment'                => new sfValidatorPass(array('required' => false)),
      'pilotEmail'                       => new sfValidatorPass(array('required' => false)),
      'coPilotFirstName'                 => new sfValidatorPass(array('required' => false)),
      'coPilotLastName'                  => new sfValidatorPass(array('required' => false)),
      'CoPilotDayPhone'                  => new sfValidatorPass(array('required' => false)),
      'coPilotDayComment'                => new sfValidatorPass(array('required' => false)),
      'CoPilotEvePhone'                  => new sfValidatorPass(array('required' => false)),
      'coPilotEveComment'                => new sfValidatorPass(array('required' => false)),
      'CoPilotMobilePhone'               => new sfValidatorPass(array('required' => false)),
      'coPilotMobileComment'             => new sfValidatorPass(array('required' => false)),
      'CoPilotPagerPhone'                => new sfValidatorPass(array('required' => false)),
      'coPilotPagerComment'              => new sfValidatorPass(array('required' => false)),
      'CoPilotOtherPhone'                => new sfValidatorPass(array('required' => false)),
      'coPilotOtherComment'              => new sfValidatorPass(array('required' => false)),
      'CoPilotFaxPhone'                  => new sfValidatorPass(array('required' => false)),
      'coPilotFaxComment'                => new sfValidatorPass(array('required' => false)),
      'coPilotEmail'                     => new sfValidatorPass(array('required' => false)),
      'buPilotFirstName'                 => new sfValidatorPass(array('required' => false)),
      'buPilotLastName'                  => new sfValidatorPass(array('required' => false)),
      'buPilotDayPhone'                  => new sfValidatorPass(array('required' => false)),
      'buPilotDayComment'                => new sfValidatorPass(array('required' => false)),
      'buPilotEvePhone'                  => new sfValidatorPass(array('required' => false)),
      'buPilotEveComment'                => new sfValidatorPass(array('required' => false)),
      'buPilotMobilePhone'               => new sfValidatorPass(array('required' => false)),
      'buPilotMobileComment'             => new sfValidatorPass(array('required' => false)),
      'buPilotPagerPhone'                => new sfValidatorPass(array('required' => false)),
      'buPilotPagerComment'              => new sfValidatorPass(array('required' => false)),
      'buPilotOtherPhone'                => new sfValidatorPass(array('required' => false)),
      'buPilotOtherComment'              => new sfValidatorPass(array('required' => false)),
      'buPilotFaxPhone'                  => new sfValidatorPass(array('required' => false)),
      'buPilotFaxComment'                => new sfValidatorPass(array('required' => false)),
      'buPilotEmail'                     => new sfValidatorPass(array('required' => false)),
      'coordFirstName'                   => new sfValidatorPass(array('required' => false)),
      'coordLastName'                    => new sfValidatorPass(array('required' => false)),
      'coordDayPhone'                    => new sfValidatorPass(array('required' => false)),
      'coordDayComment'                  => new sfValidatorPass(array('required' => false)),
      'coordEvePhone'                    => new sfValidatorPass(array('required' => false)),
      'coordEveComment'                  => new sfValidatorPass(array('required' => false)),
      'coordMobilePhone'                 => new sfValidatorPass(array('required' => false)),
      'coordMobileComment'               => new sfValidatorPass(array('required' => false)),
      'coordPagerPhone'                  => new sfValidatorPass(array('required' => false)),
      'coordPagerComment'                => new sfValidatorPass(array('required' => false)),
      'coordOtherPhone'                  => new sfValidatorPass(array('required' => false)),
      'coordOtherComment'                => new sfValidatorPass(array('required' => false)),
      'coordFaxPhone'                    => new sfValidatorPass(array('required' => false)),
      'coordFaxComment'                  => new sfValidatorPass(array('required' => false)),
      'coordEmail'                       => new sfValidatorPass(array('required' => false)),
      'requesterName'                    => new sfValidatorPass(array('required' => false)),
      'reqFirstName'                     => new sfValidatorPass(array('required' => false)),
      'reqLastName'                      => new sfValidatorPass(array('required' => false)),
      'reqDayPhone'                      => new sfValidatorPass(array('required' => false)),
      'reqEvePhone'                      => new sfValidatorPass(array('required' => false)),
      'reqMobilePhone'                   => new sfValidatorPass(array('required' => false)),
      'reqPagerPhone'                    => new sfValidatorPass(array('required' => false)),
      'reqOtherPhone'                    => new sfValidatorPass(array('required' => false)),
      'reqFaxPhone'                      => new sfValidatorPass(array('required' => false)),
      'reqDayComment'                    => new sfValidatorPass(array('required' => false)),
      'reqEveComment'                    => new sfValidatorPass(array('required' => false)),
      'reqPagerComment'                  => new sfValidatorPass(array('required' => false)),
      'reqMobileComment'                 => new sfValidatorPass(array('required' => false)),
      'reqFaxComment'                    => new sfValidatorPass(array('required' => false)),
      'reqOtherComment'                  => new sfValidatorPass(array('required' => false)),
      'reqEmail'                         => new sfValidatorPass(array('required' => false)),
      'companionName'                    => new sfValidatorPass(array('required' => false)),
      'companionRelationship'            => new sfValidatorPass(array('required' => false)),
      'companionDOB'                     => new sfValidatorPass(array('required' => false)),
      'companionAge'                     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'companionWeight'                  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'companionPhone'                   => new sfValidatorPass(array('required' => false)),
      'companionPhoneComment'            => new sfValidatorPass(array('required' => false)),
      'pilotName'                        => new sfValidatorPass(array('required' => false)),
      'afaDayPhone'                      => new sfValidatorPass(array('required' => false)),
      'afaNightPhone'                    => new sfValidatorPass(array('required' => false)),
      'afaFaxPhone'                      => new sfValidatorPass(array('required' => false)),
      'afaPilotMobilePhone'              => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'afaAircraft'                      => new sfValidatorPass(array('required' => false)),
      'afaNNumber'                       => new sfValidatorPass(array('required' => false)),
      'aircraftColor'                    => new sfValidatorPass(array('required' => false)),
      'etd'                              => new sfValidatorPass(array('required' => false)),
      'eta'                              => new sfValidatorPass(array('required' => false)),
      'afaOrgName'                       => new sfValidatorPass(array('required' => false)),
      'afaOrgPhone'                      => new sfValidatorPass(array('required' => false)),
      'fboName'                          => new sfValidatorPass(array('required' => false)),
      'fboPhone'                         => new sfValidatorPass(array('required' => false)),
      'fboFax'                           => new sfValidatorPass(array('required' => false)),
      'fboFuelDiscount'                  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'fboAirportIdent'                  => new sfValidatorPass(array('required' => false)),
      'aircraftSeats'                    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraftNNumber'                  => new sfValidatorPass(array('required' => false)),
      'aircraftKnownIce'                 => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aircraftMake'                     => new sfValidatorPass(array('required' => false)),
      'aircraftModel'                    => new sfValidatorPass(array('required' => false)),
      'campName'                         => new sfValidatorPass(array('required' => false)),
      'campPhone'                        => new sfValidatorPass(array('required' => false)),
      'campPhoneComment'                 => new sfValidatorPass(array('required' => false)),
      'campLodgingName'                  => new sfValidatorPass(array('required' => false)),
      'campLodgingPhone'                 => new sfValidatorPass(array('required' => false)),
      'campLodgingPhoneComment'          => new sfValidatorPass(array('required' => false)),
      'campComment'                      => new sfValidatorPass(array('required' => false)),
      'flightInformation'                => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('rp_mission_itinerary_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'RpMissionItinerary';
  }

  public function getFields()
  {
    return array(
      'Now'                              => 'Text',
      'missionID'                        => 'Number',
      'externalID'                       => 'Number',
      'missionTypeID'                    => 'Number',
      'missionDate'                      => 'Text',
      'apptDate'                         => 'Date',
      'flightTime'                       => 'Text',
      'releasingPhysician'               => 'Text',
      'releasingPhone'                   => 'Text',
      'releasingFax'                     => 'Number',
      'releasingFaxComment'              => 'Text',
      'releasingEmail'                   => 'Text',
      'lodging'                          => 'Text',
      'lodgingPhone'                     => 'Text',
      'lodging_phone_comment'            => 'Text',
      'facilityName'                     => 'Text',
      'facilityPhone'                    => 'Text',
      'facilityPhoneComment'             => 'Text',
      'publicConsiderations'             => 'Text',
      'privateConsiderations'            => 'Text',
      'illness'                          => 'Text',
      'groundTransportationComment'      => 'Text',
      'treatingPhysician'                => 'Text',
      'treatingPhone'                    => 'Number',
      'treatingFax'                      => 'Text',
      'treatingFaxComment'               => 'Text',
      'treatingEmail'                    => 'Text',
      'languageSpoken'                   => 'Text',
      'bestContactMethod'                => 'Text',
      'emergencyContactName'             => 'Text',
      'emergencyContactPrimaryPhone'     => 'Text',
      'emergencyContactSecondaryPhone'   => 'Text',
      'emergencyContactPrimaryComment'   => 'Text',
      'emergencyContactSecondaryComment' => 'Text',
      'passFirstName'                    => 'Text',
      'passLastName'                     => 'Text',
      'passCity'                         => 'Text',
      'passState'                        => 'Text',
      'passZipcode'                      => 'Text',
      'passAge'                          => 'Number',
      'passWeight'                       => 'Number',
      'passDayPhone'                     => 'Text',
      'passDayComment'                   => 'Text',
      'passEvePhone'                     => 'Text',
      'passEveComment'                   => 'Text',
      'passPagerPhone'                   => 'Text',
      'passPagerComment'                 => 'Text',
      'passMobilePhone'                  => 'Text',
      'passMobileComment'                => 'Text',
      'passOtherPhone'                   => 'Text',
      'passOtherComment'                 => 'Text',
      'passFaxPhone1'                    => 'Text',
      'passFax1Comment'                  => 'Text',
      'passEmail'                        => 'Text',
      'passAddressOne'                   => 'Text',
      'passAddressTwo'                   => 'Text',
      'comment'                          => 'Text',
      'id'                               => 'Number',
      'legNumber'                        => 'Number',
      'passOnBoard'                      => 'Number',
      'baggageWeight'                    => 'Number',
      'baggageDesc'                      => 'Text',
      'publicCNote'                      => 'Text',
      'privateCNote'                     => 'Text',
      'copilotWanted'                    => 'Number',
      'fromAirportIdent'                 => 'Text',
      'fromAirportName'                  => 'Text',
      'fromAirportCity'                  => 'Text',
      'fromAirportState'                 => 'Text',
      'fromAirportGMTOffset'             => 'Number',
      'fromAirportDSTOffset'             => 'Number',
      'toAirportIdent'                   => 'Text',
      'toAirportName'                    => 'Text',
      'toAirportCity'                    => 'Text',
      'toAirportState'                   => 'Text',
      'toAirportGMTOffset'               => 'Number',
      'toAirportDSTOffset'               => 'Number',
      'pilotFirstName'                   => 'Text',
      'pilotLastName'                    => 'Text',
      'pilotDayPhone'                    => 'Text',
      'pilotDayComment'                  => 'Text',
      'pilotEvePhone'                    => 'Text',
      'pilotEveComment'                  => 'Text',
      'pilotFaxPhone'                    => 'Text',
      'pilotFaxComment'                  => 'Text',
      'pilotMobilePhone'                 => 'Text',
      'pilotMobileComment'               => 'Text',
      'pilotPagerPhone'                  => 'Text',
      'pilotPagerComment'                => 'Text',
      'pilotOtherPhone'                  => 'Text',
      'pilotOtherComment'                => 'Text',
      'pilotEmail'                       => 'Text',
      'coPilotFirstName'                 => 'Text',
      'coPilotLastName'                  => 'Text',
      'CoPilotDayPhone'                  => 'Text',
      'coPilotDayComment'                => 'Text',
      'CoPilotEvePhone'                  => 'Text',
      'coPilotEveComment'                => 'Text',
      'CoPilotMobilePhone'               => 'Text',
      'coPilotMobileComment'             => 'Text',
      'CoPilotPagerPhone'                => 'Text',
      'coPilotPagerComment'              => 'Text',
      'CoPilotOtherPhone'                => 'Text',
      'coPilotOtherComment'              => 'Text',
      'CoPilotFaxPhone'                  => 'Text',
      'coPilotFaxComment'                => 'Text',
      'coPilotEmail'                     => 'Text',
      'buPilotFirstName'                 => 'Text',
      'buPilotLastName'                  => 'Text',
      'buPilotDayPhone'                  => 'Text',
      'buPilotDayComment'                => 'Text',
      'buPilotEvePhone'                  => 'Text',
      'buPilotEveComment'                => 'Text',
      'buPilotMobilePhone'               => 'Text',
      'buPilotMobileComment'             => 'Text',
      'buPilotPagerPhone'                => 'Text',
      'buPilotPagerComment'              => 'Text',
      'buPilotOtherPhone'                => 'Text',
      'buPilotOtherComment'              => 'Text',
      'buPilotFaxPhone'                  => 'Text',
      'buPilotFaxComment'                => 'Text',
      'buPilotEmail'                     => 'Text',
      'coordFirstName'                   => 'Text',
      'coordLastName'                    => 'Text',
      'coordDayPhone'                    => 'Text',
      'coordDayComment'                  => 'Text',
      'coordEvePhone'                    => 'Text',
      'coordEveComment'                  => 'Text',
      'coordMobilePhone'                 => 'Text',
      'coordMobileComment'               => 'Text',
      'coordPagerPhone'                  => 'Text',
      'coordPagerComment'                => 'Text',
      'coordOtherPhone'                  => 'Text',
      'coordOtherComment'                => 'Text',
      'coordFaxPhone'                    => 'Text',
      'coordFaxComment'                  => 'Text',
      'coordEmail'                       => 'Text',
      'requesterName'                    => 'Text',
      'reqFirstName'                     => 'Text',
      'reqLastName'                      => 'Text',
      'reqDayPhone'                      => 'Text',
      'reqEvePhone'                      => 'Text',
      'reqMobilePhone'                   => 'Text',
      'reqPagerPhone'                    => 'Text',
      'reqOtherPhone'                    => 'Text',
      'reqFaxPhone'                      => 'Text',
      'reqDayComment'                    => 'Text',
      'reqEveComment'                    => 'Text',
      'reqPagerComment'                  => 'Text',
      'reqMobileComment'                 => 'Text',
      'reqFaxComment'                    => 'Text',
      'reqOtherComment'                  => 'Text',
      'reqEmail'                         => 'Text',
      'companionName'                    => 'Text',
      'companionRelationship'            => 'Text',
      'companionDOB'                     => 'Text',
      'companionAge'                     => 'Number',
      'companionWeight'                  => 'Number',
      'companionPhone'                   => 'Text',
      'companionPhoneComment'            => 'Text',
      'pilotName'                        => 'Text',
      'afaDayPhone'                      => 'Text',
      'afaNightPhone'                    => 'Text',
      'afaFaxPhone'                      => 'Text',
      'afaPilotMobilePhone'              => 'Number',
      'afaAircraft'                      => 'Text',
      'afaNNumber'                       => 'Text',
      'aircraftColor'                    => 'Text',
      'etd'                              => 'Text',
      'eta'                              => 'Text',
      'afaOrgName'                       => 'Text',
      'afaOrgPhone'                      => 'Text',
      'fboName'                          => 'Text',
      'fboPhone'                         => 'Text',
      'fboFax'                           => 'Text',
      'fboFuelDiscount'                  => 'Number',
      'fboAirportIdent'                  => 'Text',
      'aircraftSeats'                    => 'Number',
      'aircraftNNumber'                  => 'Text',
      'aircraftKnownIce'                 => 'Number',
      'aircraftMake'                     => 'Text',
      'aircraftModel'                    => 'Text',
      'campName'                         => 'Text',
      'campPhone'                        => 'Text',
      'campPhoneComment'                 => 'Text',
      'campLodgingName'                  => 'Text',
      'campLodgingPhone'                 => 'Text',
      'campLodgingPhoneComment'          => 'Text',
      'campComment'                      => 'Text',
      'flightInformation'                => 'Text',
    );
  }
}
