read:
  is_secure:   off       # All users can request the read action

update:
  is_secure:   off        # The update action is only for authenticated users

delete:
  is_secure:   off        # Only for authenticated users
  #credentials: admin     # With the admin credential

all:
  is_secure:  off        # off is the default value anyway

