<?php

global $state_list;

$state_list = array('Alabama'=>"AL",
'Alaska'=>"AK",
'American Samoa'=>"AS",
'Arizona'=>"AZ",
'Arkansas'=>"AR",
'California'=>"CA",
'Colorado'=>"CO",
'Connecticut'=>"CT",
'Delaware'=>"DE",
'District Of Columbia'=>"DC",
"Federated States Of Micronesia"=>"FM",
'Florida'=>"FL",
'Georgia'=>"GA",
'Guam' => "GU",
'Hawaii'=>"HI",
'Idaho'=>"ID",
'Illinois'=>"IL",
'Indiana'=>"IN",
'Iowa'=>"IA",
'Kansas'=>"KS",
'Kentuky'=>"KY",
'Louisiana'=>"LA",
'Maine'=>"ME",
'Marshall Islands'=>"MH",
'Maryland'=>"MD",
'Massachusetts'=>"MA",
'Michigan'=>"MI",
'Minnesota'=>"MN",
'Mississippi'=>"MS",
'Missouri'=>"MO",
'Montana'=>"MT",
'Nebraska'=>"NE",
'Nevada'=>"NV",
'New Hampshire'=>"NH",
'New Jersey'=>"NJ",
'New Mexico'=>"NM",
'New York'=>"NY",
'North Carolina'=>"NC",
'North Dakota'=>"ND",
"Northern Mariana Islands"=>"MP",
'Ohio'=>"OH",
'Oklahoma'=>"OK",
'Oregon'=>"OR",
"Palau"=>"PW",
'Pennsylvania'=>"PA",
'Rhode Island'=>"RI",
'South Carolina'=>"SC",
'South Dakota'=>"SD",
'Tennessee'=>"TN",
'Texas'=>"TX",
'Utah'=>"UT",
'Vermont'=>"VT",
'Virgin Islands' => "VI",
'Virginia'=>"VA",
'Washington'=>"WA",
'West Virginia'=>"WV",
'Wisconsin'=>"WI",
'Wyoming'=>"WY");

$month_list = array('January'=>1,
'February'=>2,
'March'=>3,
'April'=>4,
'May'=>5,
'June'=>6,
'July'=>7,
'August'=>8,
'September'=>9,
'October'=>10,
'November'=>11,
'December'=>12);

$month_abbr = array('Jan'=>1,
'Feb'=>2,
'Mar'=>3,
'Apr'=>4,
'May'=>5,
'Jun'=>6,
'Jul'=>7,
'Aug'=>8,
'Sep'=>9,
'Oct'=>10,
'Nov'=>11,
'Dec'=>12);
?>